### ISSUE TITLE
PC players sinking into ground when viewed from PE client

### ISSUE THREAD

**Issue by ashquarky** [DragonetMC/Dragonet-Legacy#10]
Hi guys! Just a small bug I found.

When a PC player is walking around, anyone looking at them from a PE client will see them jittering in and out of the ground. It seems to happen mostly on gravel but I've seen it happen on grass near gravel as well.

Here's a gif of it:

![Gif of sinking player](http://connorsstuff.hostzi.com/Picturs/GitHub/dragonet1.gif)

Specs of all involved machines:
- PE Client: iPod Touch 4th Gen (MC540ZP) running iOS 6.0.1 (10A523) and MCPE v0.10.4
  - Jailbroken, but in safe mode at time of recording
- PC Client: AMD Athlon (2.8Ghz) w/ 4GB RAM running Windows 7 Ultimate SP1 and MC 1.8.0 on Java 1.8.0_25
  - Minecraft has [LiteLoader](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1290155-liteloader-for-minecraft-1-7-10) and the [Macros Mod](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1275039-macro-keybind-mod-0-10-12) installed.
- Server: Pentium D (2.66Ghz) w/ 2GB RAM running Ubuntu 14.04.1 LTS and Dragonet 0.0.2-preR1 (w/ Bukkit 1.8-R0.1-SNAPSHOT) on OpenJDK 1.7.0_65

Bugs can be annoying, but it's still an amazing piece of software!

**Comment by DefinitlyEvil** [comment]
I know this bug, I am still trying to fix it. xD

**Comment by fe1a** [comment]
@QuarkTheAwesome Do you see yourself underground on the PC Client or you look completley fine

**Comment by optrusty** [comment]
:( @DefinitlyEvil Why did you discontinue the project

**Comment by ashquarky** [comment]
@optrusty Nah, on the PC client it's fine.

**Comment by DefinitlyEvil** [comment]
@optrusty @QuarkTheAwesome I think it's a MCPE bug.

**Comment by TheMCPEGamer** [comment]
Seems that this is a Glowstone bug (https://github.com/GlowstoneMC/Glowstone/issues/485)

**Comment by gdude2002** [comment]
Can confirm that this has nothing to do with that Glowstone ticket, which is a bug in Minecraft's PC version (clients jumping at a specific angle towards an overhead block can push them through the ground).

**Comment by DefinitlyEvil** [comment]
@gdude2002 Thanks. ;) I think Mojang will fix this in the future(maybe).

**Comment by DefinitlyEvil** [comment]
That was a Minecraft PC client's problem, now fixed by Mojang. :D ( Thanks to @Dinnerbone ).
