### ISSUE TITLE
Raknet

### ISSUE THREAD

**Issue by RazvanDu** [DragonetMC/Dragonet-Legacy#100]
You could change some of the functions in the jraklib library to make it more tailored for your project which would result in a better performance.

**Comment by DefinitlyEvil** [comment]
Such as?

**Comment by RazvanDu** [comment]
I'll make a PR as soon as I manage to import the project lol

**Comment by RazvanDu** [comment]
Btw, I found another issue, the client crashes every once in a while.

**Comment by DefinitlyEvil** [comment]
1. Thanks. 
2. That problem didn't happened to me using iPhone 4s.

**Comment by RazvanDu** [comment]
1. I've had the issue when I was working on my server and I'm pretty sure it's the raklib not splitting the packets corretly, I'll also fix that.
2. I still can't get the project imported ;c

**Comment by DefinitlyEvil** [comment]
First you have to clone this repo with its submodules. Then you need NetBeans, just open this repo as a Maven project. No need further changes. Before build you have to build the dependencies in GlowstonePlusPlus folder (i.e. Bukkit API).

**Comment by RazvanDu** [comment]
Meh, too late, I've already figured it out like 30mins ago, lol, btw I'm using InteliiJ not NetBeans

**Comment by RazvanDu** [comment]
I've rewritten a huge chunk of the raknet library already, lol.

**Comment by DefinitlyEvil** [comment]
@SenanYT I used @MagicDroidX 's port of RakLib it works incredibly nice!

**Comment by alejzeis** [comment]
Yeah sorry I couldnt help, I'm really busy.

**Comment by DefinitlyEvil** [comment]
@jython234 Okay, dude. xD

**Comment by RazvanDu** [comment]
I know what library you've used, it's actually very similar to jython's raknet library, just slightly differnet lol

**Comment by DefinitlyEvil** [comment]
@SenanYT They are all ported from PocketMine's work.

**Comment by RazvanDu** [comment]
@DefinitlyEvil Yea, I know.

**Comment by RazvanDu** [comment]
I'm getting a ton of errors of already loaded chunks trying to be loaded when a PE player joins, have I caused that or is it a known thing?

**Comment by RazvanDu** [comment]
I've made a pullrequest which removed a ton of bulk from the raklib which in my opinion is completly useless, keep in mind it still needs some testing and tweaking!

**Comment by RazvanDu** [comment]
Nvm the pull request I've made although the performance is better I don't think it would work well with huge amounts of players, anyways, I would like to contribute to the project as much as I can from now on.

**Comment by RazvanDu** [comment]
Actually I think it won't make a difference for huge amounts of players.

**Comment by DefinitlyEvil** [comment]
Probably. xD

**Comment by DefinitlyEvil** [comment]
I guess this issue can be closed now?
