### ISSUE TITLE
Can't see Korean on MCPE

### ISSUE THREAD

**Issue by U-siro** [DragonetMC/Dragonet-Legacy#102]
working perfectly any, but i can't see korean(example:안녕하세요) on MCPE.

**Comment by DefinitlyEvil** [comment]
Will be checked ASAP. :) Thx for reporting.

**Comment by RazvanDu** [comment]
As I was excepting I'm 90% sure the issue is caused by the binary writer/reader which is supposed to write and read the string using the charset "UTF-8".  This should be easy to fix.

**Comment by RazvanDu** [comment]
Also if the issue is caused by that colors probably don't work in the chat either

**Comment by KangYui** [comment]
Korean is support UTF-8, Should no problem..

**Comment by RazvanDu** [comment]
No what I meant is that Dragonet does not support UTF-8 I'll make a PR shortly

**Comment by RazvanDu** [comment]
Since I have already made a PR and apparently I can't update it or make a new one, since the changes are really small, just add this to the project:
https://github.com/SenanYT/Dragonet/commit/29a68d86ee33eaea1ce2c6e5cd57a2afc226809a

**Comment by RazvanDu** [comment]
That should also add support for colors in the chat which I feel like weren't possible before, although I may be wrong.

**Comment by DefinitlyEvil** [comment]
@SenanYT I will add you to the org since you seems likes our project. ;P

**Comment by KangYui** [comment]
Thanks for resolving this problem.

**Comment by DefinitlyEvil** [comment]
@KangYui Cool! More bug reports are appreciated! :P

**Comment by RazvanDu** [comment]
@DefinitlyEvil Thanks, I definitely like the project ;p
