### ISSUE TITLE
Huge lagspike

### ISSUE THREAD

**Issue by RazvanDu** [DragonetMC/Dragonet-Legacy#103]
There's a huge lagspike for the MCPE client when you join the game(I'm not sure if it's an issue related to Dragonet but I think it is).

**Comment by DefinitlyEvil** [comment]
Your phone CPU is too slow to render the chunks I think. xD

**Comment by RazvanDu** [comment]
Lol, I don't think so, every other MCPE server works extremely well ( I have a LG G3 ).

**Comment by DefinitlyEvil** [comment]
@SenanYT You mean server lags? But you wrote your client lags.

**Comment by RazvanDu** [comment]
The clients lags, lol.

**Comment by RazvanDu** [comment]
It's not a huge issue and it may not be due to dragonet, let's focus on this later.

**Comment by DefinitlyEvil** [comment]
@SenanYT Not happened on me though. xD
