### ISSUE TITLE
I'll opening demo test server

### ISSUE THREAD

**Issue by KangYui** [DragonetMC/Dragonet-Legacy#105]
I current opening Dragonet Test Server, you can add it to README.md?

my server address is "server-test-yg70i5x3.cloudapp.net"

**Comment by DefinitlyEvil** [comment]
24/7 for ever?

**Comment by KangYui** [comment]
Yep by Microsoft Azure.

**Comment by james58899** [comment]
You can let the server address shorter?
MCPE can not copy and paste

**Comment by Castar** [comment]
lolirs.com
2015년 12월 3일 (목) 오전 5:00, 鄭仁翔 <notifications@github.com>님이 작성:

**Comment by DefinitlyEvil** [comment]
Unable to connect. What is the port?

**Comment by pitapun** [comment]
I can connect and saw some fire :)

**Comment by DefinitlyEvil** [comment]
@pitapun Okay, maybe my network sucks. Lol.

**Comment by DefinitlyEvil** [comment]
Okay I forgot the 'server-test' part of the domain. LOL!!

**Comment by DefinitlyEvil** [comment]
It is cool that you got a unique-IP server.

**Comment by KangYui** [comment]
I am small hosting company owner! If you need another server, just tell to me.

**Comment by DefinitlyEvil** [comment]
@KangYui You can be a community sponsor. XD We already got BytePowered as our sponsor company.

**Comment by KangYui** [comment]
Use my server for now. BytePowered demo server is still "UPDATING" status.

**Comment by DefinitlyEvil** [comment]
@KangYui He is preparing the server.

**Comment by DefinitlyEvil** [comment]
@KangYui Before he is ready would you mind lend me a VPS(dedicated IP so I can set 'demo.dragonet.org' to it) for the test server?

**Comment by KangYui** [comment]
OK, Please allow a minutes.

**Comment by KangYui** [comment]
Please send your email, because I will send connect information to your emai.

**Comment by DefinitlyEvil** [comment]
@KangYui theevildays@gmail.com

**Comment by DefinitlyEvil** [comment]
Please, use Debian x64. ;) I prefer this than other linux forks. xD

**Comment by KangYui** [comment]
Oh.. this is configured using Windows Server. if you need linux, please wait more minutes(or 1 hour?)

**Comment by DefinitlyEvil** [comment]
It's okay, please take your time. I think windows is not suitable for servers because MS even doesn't use their product on their servers. xD

**Comment by DefinitlyEvil** [comment]
Please give it more RAM cuz Dragonet eats RAM. ;P

**Comment by DefinitlyEvil** [comment]
@KangYui Let us go on Gitter.

**Comment by ethsmith** [comment]
@DefinitlyEvil Yes Ram and Dragonet uses up the a cpu like noones business. Maybe that's fixed with the new MCPE update not sure I suggest monitoring the CPU usage

**Comment by mastercoms** [comment]
Do you think it is Glowstone++'s fault?

**Comment by ethsmith** [comment]
@mastercoms I'm 95% sure its something with dragonet because Glowstone++ and Dragonet were both on a machine I monitored at one point and I don't think I had the problem with Glowstone++. After Glowstone++'s new code is pushed and I can get a Jar out of it. I will remonitor the CPU with it on a server for a couple weeks to make sure G++ is good.

**Comment by DefinitlyEvil** [comment]
@TekkitCommando Maybe I should check with VisualVM.

**Comment by TekkitCommando** [comment]
@DefinitlyEvil Works for me

**Comment by DefinitlyEvil** [comment]
@TekkitCommando I mean check its CPU and RAM usage.

**Comment by ethsmith** [comment]
@DefinitlyEvil I know xD

**Comment by DefinitlyEvil** [comment]
@TekkitCommando So what specifically eats CPU/RAM?

**Comment by ethsmith** [comment]
@DefinitlyEvil Like in general with servers or specifically with Dragonet?

**Comment by DefinitlyEvil** [comment]
@TekkitCommando Dragonet

**Comment by ethsmith** [comment]
http://openjdk.java.net/tools/svc/jconsole/

**Comment by ethsmith** [comment]
May try checking that out

**Comment by DefinitlyEvil** [comment]
okay

**Comment by mastercoms** [comment]
I would recommend https://visualvm.java.net/

**Comment by DefinitlyEvil** [comment]
@mastercoms Yeah, I like that too.

**Comment by fe1a** [comment]
Idk if this works I set it as a CNAME :? server-test-yg70i5x3.cloudapp.net --> drago.shrt.eu.org
its more shorter

**Comment by jlirochon** [comment]
Hey, I finished working on Docker image today.

It could be used to run test servers with minimal setup, and make auto-update as simple as possible.

**Comment by ethsmith** [comment]
@RealIron maybe have an SRV so we can do like demo.dragonet.org @DefinitlyEvil

**Comment by DefinitlyEvil** [comment]
@TekkitCommando Why can't I access `demo.cgrp.co.kr:25565`? 
It is hosting on Azure and shared IP and seems using a SSH redirector to redirect SSH connections to the virtual machine by username. But I can access `server-test-yg70i5x3.cloudapp.net` on UDP port 19132. I don't know the reason why it happening. :(

**Comment by ethsmith** [comment]
Not sure. I was pretty sure azure was for web app hosting

**Comment by jlirochon** [comment]
who pays for this server instance ?

**Comment by mastercoms** [comment]
Azure is like aws or google cloud platform. It is a server.

**Comment by DefinitlyEvil** [comment]
@jlirochon This guy @KangYui paid for them.
