### ISSUE TITLE
MCPE can't rejoin

### ISSUE THREAD

**Issue by KangYui** [DragonetMC/Dragonet-Legacy#106]
if mcpe client is exit, (maybe) not marked on dragonet as offline

then can't rejoin..

17:26:31 [INFO] Accepted connection by [LPOPME].
17:26:32 [INFO] LPOPME kicked: You logged in from another location.
17:26:32 [INFO] LPOPME [/39.127.241.142:19132] connected from Minecraft PE, UUID
: 8f0ce261-aafb-3645-bc7b-f297f75d2a8a
17:26:32 [INFO] LPOPME joined the game
17:26:37 [INFO] Received Packet: BatchPacket
17:26:37 [INFO] Received Packet: LoginPacket
17:26:37 [INFO] Accepted connection by [LPOPME].
17:26:37 [INFO] LPOPME kicked: You logged in from another location.
17:26:37 [INFO] LPOPME [/39.127.241.142:19132] connected from Minecraft PE, UUID
: 8f0ce261-aafb-3645-bc7b-f297f75d2a8a
17:26:37 [INFO] LPOPME joined the game

**Comment by DefinitlyEvil** [comment]
Added.
