### ISSUE TITLE
MCPE iOS v0.1.3.0 does not list Dragonet servers of the same LAN

### ISSUE THREAD

**Issue by jlirochon** [DragonetMC/Dragonet-Legacy#107]
If the server is on the client's LAN, it should be detected and listed by the client.

This works with https://github.com/PocketMine/PocketMine-MP/tree/mcpe-0.13 for example, so I think the bug is in the server.

I can confirm that client and server are exchanging some broadcast packets, server response may be invalid and dropped by the client ?

**Comment by DefinitlyEvil** [comment]
Yea, I'm sure maybe server's respond is outdated.

**Comment by DefinitlyEvil** [comment]
Note: RakNet Interface implementation class.

**Comment by DefinitlyEvil** [comment]
Added in the to-do list.
