### ISSUE TITLE
Picking up items had a BUG.

### ISSUE THREAD

**Issue by ghost** [DragonetMC/Dragonet-Legacy#109]
The PE player to pick up the PC player threw items, and hear the sound of pick up succes, but does not display properly in the PE player's inventory.
So I think this maybe a bug for server. :)

**Comment by DefinitlyEvil** [comment]
Player inventory packet need to be updated. ;) Will be fixed ASAP.

**Comment by DefinitlyEvil** [comment]
Added in the to-do list.
