### ISSUE TITLE
MCPE can not display the server list information

### ISSUE THREAD

**Issue by ghost** [DragonetMC/Dragonet-Legacy#110]
Unable to display the server status(Even if the server has been opened). And always keep the search status. Just look like server does not open.
I think this is a bug. :)

**Comment by RazvanDu** [comment]
This bug has already been fixed.

**Comment by ghost** [comment]
@SenanYT Oh, sorry, I did not see so soon to update (a few minutes ago), Thank you!

**Comment by RazvanDu** [comment]
Np, lol
