### ISSUE TITLE
Player movement.

### ISSUE THREAD

**Issue by RazvanDu** [DragonetMC/Dragonet-Legacy#111]
If there are 2 players logged in from PE and they both move they get stuck and whenever one of them moves the other one follows.

I'm pretty sure this bug is cause by wrong entity IDs.

**Comment by ghost** [comment]
YES I find this bug, Just ready to submit issues...

**Comment by RazvanDu** [comment]
Lol, I'll try to fix it really soon.

**Comment by ghost** [comment]
Okay, I'll go look for more BUGGG.

**Comment by RazvanDu** [comment]
Good, the more bugs you find, the faster Dragonet will progress :)

**Comment by DefinitlyEvil** [comment]
Added in the to-do list #98
