### ISSUE TITLE
The number of online player display error.

### ISSUE THREAD

**Issue by ghost** [DragonetMC/Dragonet-Legacy#112]
My test server maximum number of online player is 20, correct display should be 0/20, but...It displays became -1/-1 ... So this is definitely a BUG...

**Comment by RazvanDu** [comment]
This is not a bug, rather this is a feature that hasn't been implemented yet, since the server list has only been fixed today, no-one took the time to make the players show there so it display -1 and -1, I'll fix this rather soon tho.

**Comment by RazvanDu** [comment]
I didn't mean to close this lol I'll close it when it's fixed

**Comment by RazvanDu** [comment]
The issue has been fixed, although the amount of players still doesn't update it shows the max players correctly!

**Comment by DefinitlyEvil** [comment]
-1/-1 is just a placeholder, I didn't update it every tick so...
