### ISSUE TITLE
But why MCPE no online player list?

### ISSUE THREAD

**Issue by ghost** [DragonetMC/Dragonet-Legacy#113]
I inadvertently discovered MCPE actually did not display a list of online players... !!! And this is a bug, too.

**Comment by RazvanDu** [comment]
If you mean the list of players in the exit menu, this issue is related to the fireball skin bug and I've already fixed it like 30mins ago.

**Comment by DefinitlyEvil** [comment]
So I will close this since @SenanYT fixed it?
