### ISSUE TITLE
Under survival mode, MCPE players destroy items too fast.

### ISSUE THREAD

**Issue by ghost** [DragonetMC/Dragonet-Legacy#114]
Almost like the creation mode and the destruction speed of all the items are similar.
But the most serious is, when I try destructing a leaf, and the other leaves also inexplicable destruction.
I don't know of other items' case.
This is simply too terrible. :(

**Comment by RazvanDu** [comment]
Yea I've noticed this already I don't think it's really high priority tho since we've got some other stuff to fix but this should be fixed soon

**Comment by ethsmith** [comment]
@SenanYT Put the bug tag on these issues in the future xD

**Comment by RazvanDu** [comment]
@TekkitCommando Okay lol, sorry ;p

**Comment by ethsmith** [comment]
@SenanYT Its cool :P

**Comment by DefinitlyEvil** [comment]
Oops, a huge huge.
