### ISSUE TITLE
Several bugs.

### ISSUE THREAD

**Issue by RazvanDu** [DragonetMC/Dragonet-Legacy#117]
- [ ] Sometimes the server swaps the PE player entities and when you move it moves the other players lol.
- [ ] When a PC player rotates his head it doesn't update on PE.
- [ ] Sometimes PE sees the skins as transparent.

**Comment by RazvanDu** [comment]
- [ ] Also the world time isn't synced between PE and PC players.

**Comment by ethsmith** [comment]
Thank you for finding all these bugs

**Comment by RazvanDu** [comment]
- [x] Another bug, the player spawns about 2 blocks in the ground!

**Comment by jlirochon** [comment]
I created a separate issue for each bug and I'm closing this one
