### ISSUE TITLE
Rouge thread from UDP socket - Possible fix?

### ISSUE THREAD

**Issue by ashquarky** [DragonetMC/Dragonet-Legacy#12]
Hey guys!

I've noticed that when shutting down Dragonet, there's a rouge thread which appears to be the UDP socket. After looking at the source code, I think I've tracked it to these lines:
(Lines 93-97 in NonBlockUDPSocket.java)

``` javascript
    public void end() {
        running = false;
        //this.socket.close();
        this.interrupt();
    }
```

As you can see, the middle line is commented out. In my testing, uncommenting that line fixes the rouge thread with no other consequences.
The reason I submitted this as an issue and not a pull request is because I'm not sure whether it's meant to be like that or not (Git versioning says that this line has both been there and commented since "Clients can join now"). So, there you go. Is it meant to be commented? Why?

**Comment by DefinitlyEvil** [comment]
This is not a error. This happenss because the UDP socket in class NomBlockUDpsOcket is actually a blocked socket, it won't continue the loop until a packet is received. So it can't be coded perperly, for now let's just ignore that message. :P

**Comment by ashquarky** [comment]
However, the server appears to work perfectly with this line uncommented... Is there some issue I'm missing with it?

**Comment by DefinitlyEvil** [comment]
Nope, I think.
