### ISSUE TITLE
Release management improvement proposal

### ISSUE THREAD

**Issue by jlirochon** [DragonetMC/Dragonet-Legacy#120]
Having all bugs referenced as checkboxes in a single issue is not very clean.

I think each bug should have it's own issue, but we still need some "ToDo list" feature to manage milestones and releases.

We could take benefit of more powerful tools. For example https://www.zenhub.io/ is free and integrates directly in GitHub ([screenshot](http://snag.gy/bsyez.jpg)).

**Comment by RazvanDu** [comment]
I think we should do this.

**Comment by ethsmith** [comment]
I like this idea too

**Comment by mastercoms** [comment]
I think we should have individual issues, and then make a Todo milestone to keep track.

**Comment by DefinitlyEvil** [comment]
@mastercoms I have never used Milestone stuff before. ;P What does it do anyways?

**Comment by mastercoms** [comment]
It keeps track of and groups multiple issues together.

**Comment by DefinitlyEvil** [comment]
@mastercoms Oh so it is like a to-do list with issues, nice!

**Comment by mastercoms** [comment]
I guess we can close this now, since we have made a milestone for 0.0.3.

**Comment by jlirochon** [comment]
Cool :shipit:
