### ISSUE TITLE
Player disconnect

### ISSUE THREAD

**Issue by RazvanDu** [DragonetMC/Dragonet-Legacy#122]
Although the current disconnect thing works fine it's quite hacky and I think we should redo it later.

**Comment by jlirochon** [comment]
For the long story, @SenanYT fixed a disconnect bug in this commit: f2e3ee5ab6436d24f70fc9606a1669e71cfa5c04

@SenanYT

> I added a hacky thing
> The issue is that it was always giving an error
> So I made it so that it doesn't display the error
> I'm not sure what that error was all about
