### ISSUE TITLE
New website.

### ISSUE THREAD

**Issue by RazvanDu** [DragonetMC/Dragonet-Legacy#124]
I think we should get a new and improved website+forum for Dragonet since the actual website doesn't look that good lol.

**Comment by jlirochon** [comment]
~~Actually it seems the official site is down~~ it's up again !

To everyone: at your opinion, what feature do we need on such a website ?

**Comment by jlirochon** [comment]
There are many places that sells cheap minecraft website templates, like this one for example: https://gametemplates.org/game/minecraft

**Comment by ethsmith** [comment]
Why do that when you could design your own :) or just get a Minecraft template from me if you like it

**Comment by jlirochon** [comment]
Lol, because I'm not a designer, better spend $5 than spend 2 days on doing something I can't do.

@TekkitCommando are you a designer ?

**Comment by ethsmith** [comment]
@jlirochon yeah I guess but I like web development more then web design :P I got this template that you can have if you like it https://gametemplates.org/p/10009

**Comment by jlirochon** [comment]
Thanks for your offer @TekkitCommando ! Do you have a browsable version ? I can't tell if the template handles media queries.

By the way, it's not my decision. We are in the process of determining whether the project needs a new website, and if it is the case, which feature would we need.

Anyone could have his point of view, especially @DefinitlyEvil

**Comment by ethsmith** [comment]
@jlirochon I don't have a live preview atm but I can set one up and @DefinitlyEvil probly wouldn't even care as long as someone else was working on it xD

**Comment by ethsmith** [comment]
@jlirochon and yes it handles media queries

**Comment by ethsmith** [comment]
@jlirochon http://www.bytepowered.com/mc-demo ofc changes will need to be made, but replace our current website files on GitHub with these and I can make the changes on my own and send a pr

**Comment by ethsmith** [comment]
IT could end up looking quite fancy

**Comment by jlirochon** [comment]
Looks like we have a forum here http://forums.dragonet.org/

**Comment by DefinitlyEvil** [comment]
@jlirochon That forum just sucks. I want a website like http://Bukkit.org , it is a website with forums but we have to pay for XenForo. Any good ideas?

**Comment by ethsmith** [comment]
@DefinitlyEvil Maybe discourse but it has quite a few dependencies I think

**Comment by DefinitlyEvil** [comment]
@TekkitCommando Sure it has, but those extensions won't cost much either time or money.

**Comment by ethsmith** [comment]
@DefinitlyEvilit is all free so back to the original point of things, do we make a new website or not xD

**Comment by DefinitlyEvil** [comment]
@TekkitCommando If we had a PHP website space. xD

**Comment by ethsmith** [comment]
@DefinitlyEvil Need more then php installed

**Comment by DefinitlyEvil** [comment]
@TekkitCommando ??

**Comment by ethsmith** [comment]
@DefinitlyEvil I think it uses redis and other things as well

**Comment by jlirochon** [comment]
They have a Docker version, just launch it with Docker and forget about the dependencies. A Docker container comes with the dependencies included.

**Comment by jlirochon** [comment]
https://github.com/discourse/discourse/blob/master/docs/INSTALL-cloud.md

**Comment by mastercoms** [comment]
@jlirochon Yes, but the problem is getting a server.

**Comment by jlirochon** [comment]
Maybe start a fundraising campaign ?

**Comment by ethsmith** [comment]
I don't want to be negative but we don't have too many active supporters :P

**Comment by ethsmith** [comment]
Live stream event for fundraising! :P

**Comment by DefinitlyEvil** [comment]
Nice idea! XD We dong have many supporters cuz only few people know us.

**Comment by jlirochon** [comment]
We have a hosting service in France which provides micro bare metal servers for 3EUR / month. https://www.scaleway.com/
