### ISSUE TITLE
Breaking a block on PE

### ISSUE THREAD

**Issue by CAmadeusA** [DragonetMC/Dragonet-Legacy#125]
Breaking a block on PE does not register to the server, nor drop the block after recieving the removeblock packet. 

Suggested solution from a newbie; in the removeblockpackettranslator, under the non-creative section, theres no handling for wether the block is harvestable, or setting the block to air and dropping the proper item/block.

**Comment by RazvanDu** [comment]
Lol, I'll try to look into this tomorrow.

**Comment by DefinitlyEvil** [comment]
Thx. @SenanYT.

**Comment by DefinitlyEvil** [comment]
@SenanYT Any clew?

**Comment by RazvanDu** [comment]
@DefinitlyEvil I haven't had quite the time to check this yet :C, maybe you can try to figure it out

**Comment by DefinitlyEvil** [comment]
@SenanYT Already did, I translated end breaking packet into PC one and past it to G++ but it seems not handling it.
