### ISSUE TITLE
Testing server

### ISSUE THREAD

**Issue by Creeperface01** [DragonetMC/Dragonet-Legacy#126]
Hi i can host dragonet demo server  on my VPS. 
If you want, please write commands to install java And start.sh file.

**Comment by jlirochon** [comment]
Hi @Creeperface01 !

Do you have a Linux VPS ? Which distribution and version did you install ?

**Comment by Creeperface01** [comment]
Ubuntu 15

**Comment by Creeperface01** [comment]
Ubuntu server 15

**Comment by U-siro** [comment]
He recommend Debian x64.
2015년 12월 7일 (월) 오후 3:10, Creeperface01 notifications@github.com님이 작성:

**Comment by DefinitlyEvil** [comment]
Ubuntu is a enhanced versio of Debian. ;)

**Comment by jlirochon** [comment]
I don't know if you can install Docker on a VPS, but it's an easy way to get Dragonet running. Here are [the instructions](https://github.com/DragonetMC/Dragonet#docker-image). Here come the demonstration:

[![asciicast](https://asciinema.org/a/9mfyow2z0frrtenhhvnwt7dvj.png)](https://asciinema.org/a/9mfyow2z0frrtenhhvnwt7dvj)

If you can't install Docker, I can still help ;)

**Comment by gaoyichuan** [comment]
I have several vps running CentOS 6.x , I can help too.

**Comment by fe1a** [comment]
I have at least 5 vps servers that can run ubuntu, debian, centos or any other stuff. And I have a local PC running VMWare ESXi that has a 1TB HD, 12GB RAM, but a slow internet connection(5mb down/1mb up.) If any of those servers will help anyway.

**Comment by DefinitlyEvil** [comment]
@RealIronDev Please contact me over Skype: DefinitlyEvil.

**Comment by fe1a** [comment]
@DefinitlyEvil k, I sent you a message
