### ISSUE TITLE
PE player doesn't see other player head tilt until the player moves

### ISSUE THREAD

**Issue by jlirochon** [DragonetMC/Dragonet-Legacy#127]
I'm connected with a PC and a PE, face to face.

When PE tilts his head, PC sees the change immediately.

When PC tilts his head, PE won't see any changes until PC moves.

**Comment by RazvanDu** [comment]
#117..

**Comment by jlirochon** [comment]
Yes sorry, that's a duplicate :/

May I split #117 into several tickets ?

**Comment by jlirochon** [comment]
The additional information here is that the head rotation applies when the player moves.

**Comment by RazvanDu** [comment]
I think the information in #117 is clear enough, do as you want.
