### ISSUE TITLE
Unable to make and load a start.command file (for Mac)

### ISSUE THREAD

**Issue by ghost** [DragonetMC/Dragonet-Legacy#136]
I'm currently using the latest build at the moment which would be #272, yet whenever I try to load up the jar with a .command file (can't run .bat files), I always get this error in the terminal:

Unrecognized option: -
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

If someone could provide me with a proper start file, it would be much appreciated.

**Comment by mastercoms** [comment]
What is your command file? There is an extra - somewhere.

**Comment by DefinitlyEvil** [comment]
Maybe because he tried allocate too much memory for the JVM. ;P

**Comment by jlirochon** [comment]
Hi @ManticorCC,

Please try the following:
- copy the content of the script below into a `Dragonet.command` file
- set executable mode on the file: `chmod u+x Dragonet.command`
- place `dragonet-0.0.3-preR2.jar` in the same directory

``` bash
#!/bin/bash
cd "$(dirname "$0")"
JAR=$(find . -name "dragonet-*.jar" | sort -r | head -n1)

echo "Launching $JAR..."
java -Xms256M -Xmx768M -jar $JAR
```

**Comment by mastercoms** [comment]
@DefinitlyEvil It says`Unrecognized option: -`, so there is an extra `-` somewhere.

**Comment by ghost** [comment]
Thanks @jlirochon, the script worked. I can join the server on my mac w/ version 1.8.9, yet I am unable to find my server on iPhone playing PE. By the way, I also have a rack mount server running Ubuntu Server that I'd like host dragonet on as well; I'm assuming I can't use the same script? Sorry, but I have very little to no coding experience...

Edit: PE version is obviously 0.13.0

**Comment by jlirochon** [comment]
The Mac and the iPhone must be on the same network, otherwise the server won't be listed. You can try to add a server manually in PE to test if you can join. If you can't, check your firewall rules. You need to open UDP port 19132 (on your Mac)

**Comment by mastercoms** [comment]
@jlirochon Those memory values are a bit low, I think.

**Comment by jlirochon** [comment]
@mastercoms what would you recommend ?

Honestly I don't know the exact purpose of those values. As a non-Java developer, It seems to me that Java will always grow bigger than the values you choose.

**Comment by DefinitlyEvil** [comment]
@ManticorCC You should check out the brand new `DragonProxy`.

**Comment by mastercoms** [comment]
@jlirochon I haven't profiled Dragonet to find optimal memory values, but I think 768 - 1024 would be good for it.  The JVM will listen to Java flags.
