### ISSUE TITLE
Should we stop developing Dragonet?

### ISSUE THREAD

**Issue by DefinitlyEvil** [DragonetMC/Dragonet-Legacy#137]
So `DragonProxy` is more reliable and easier to use so should we stop making Dragonet?

**Comment by sgdc3** [comment]
The proxy is more interesting and usable everywhere ;)

**Comment by MrPowerGamerBR** [comment]
I think DragonProxy should be more stable (with almost every current issue
fixed) before abandoning Dragonet.
Em 17 de jan de 2016 09:21, "The Evil Man" notifications@github.com
escreveu:

**Comment by DefinitlyEvil** [comment]
Okay. xD

**Comment by MrPowerGamerBR** [comment]
Also, did you announce the project (Dragonproxy) on SpigotMC? Announcing
there could get some interested people, or even someone who wants to help
with the Dragpnproxy project.
Em 17 de jan de 2016 11:14, "The Evil Man" notifications@github.com
escreveu:

**Comment by ethsmith** [comment]
I saw it on Sponge when I was viewing the forum threads.

**Comment by ethsmith** [comment]
@MrPowerGamerBR I could make a spigot thread post, all I do is watch over the servers and look over the progress of this project so I got time xD

**Comment by MrPowerGamerBR** [comment]
If you can create, then do it.

It would be better to do a good topic tho, with screenshots (NEW
SCREENSHOTS, the ones in the readme is very old), test servers, some info,
etc.

(Create on the off topic section)
Em 17 de jan de 2016 11:40, "Ethan Smith" notifications@github.com
escreveu:

**Comment by MrPowerGamerBR** [comment]
I can setup some test servers too, if it is needed. (Just say some good PC
servers to add as a test servers)
Em 17 de jan de 2016 11:40, "Ethan Smith" notifications@github.com
escreveu:

**Comment by ethsmith** [comment]
@MrPowerGamerBR Some good pc servers, maybe like Hypixel, Mineplex, or Avalon Kingdoms

As far a screenshots go I don't have anything to take screenshots with atm.

**Comment by MrPowerGamerBR** [comment]
I'm traveling at the moment, when I get home I will create the test servers
(in about 1-2 hours)

I can create the topic, if you want to. (Since I can take screenshots)
Em 17 de jan de 2016 11:58 AM, "Ethan Smith" notifications@github.com
escreveu:

**Comment by ethsmith** [comment]
@MrPowerGamerBR If we need screenshots, you better do the topic or just take em, and send me a link to a zip via dropbox whatever works for you :P

**Comment by MrPowerGamerBR** [comment]
I'm now at home, now I can create the thread and create some fancy test servers

**Comment by sgdc3** [comment]
Wait, a proxy can't be more stable, but it's more useful! ;)

**Comment by Creeperface01** [comment]
Proxy can be more stable

**Comment by sgdc3** [comment]
Why? Protocol alteration may cause glitch.

**Comment by DaMatrix** [comment]
just tried out the prer2 and it's awesome. Keep it up!!

**Comment by TheDiamondYT1** [comment]
Get the fuck did of if lmao

@TekkitCommando I  posted on sponge

**Comment by ethsmith** [comment]
@RandomAltThingy oh ok xD

**Comment by TheDiamondYT1** [comment]
Rid*

**Comment by S0N-0F-A-S0N** [comment]
NO

**Comment by S0N-0F-A-S0N** [comment]
Keep up development

**Comment by TheDiamondYT1** [comment]
No there is no point java is slower than C# so [MiNET is faster](https://github.com/niclasolofsson/minet). DragonProxy allows you to connect to any of server with pc and doesn't require a new server software.

**Comment by ethsmith** [comment]
@RandomAltThingy it really depends on how efficient the code is in the first place. C# isn't always faster it's a matter of how well the product is coded.

**Comment by mastercoms** [comment]
lol java is slower. when will this myth end?

**Comment by MrPowerGamerBR** [comment]
@mastercoms yeah, people associate Java = slower just because Minecraft is laggy, Minecraft is laggy because of the amount of legacy code in it, and because Notch wasn't planning in Minecraft becoming big as it is now, so the code he made isn't the best.

**Comment by ethsmith** [comment]
@MrPowerGamerBR correct :P

**Comment by TheDiamondYT1** [comment]
@TekkitCommando Incorrect :P

It's fact. Unless you can write really good java code.

**Comment by Pet0203** [comment]
I think that DragonProxy is more interesting because it allows you to join whatever server you want to join. So i think that we should stop dragonet development for now

**Comment by ethsmith** [comment]
It's not a fact, it's biast based on people's favorite language. That's like me saying Windows is better then Linux. It's a preference xD

**Comment by TheDiamondYT1** [comment]
@TekkiCommando My favourite language is java but if I were to code something like a whole server software it would be in C# as I'm not that good at C++

**Comment by MrPowerGamerBR** [comment]
@RandomAltThingy while you can't do this because the three platforms are still in development, when Nukkit (Java), MiNET (C#) and ImagicalMine (PHP), are stable, then do a benchmark on the three to find what "programming language" is the "best". (even tho it won't be a fair benchmark because they aren't the same code, and Nukkit is really just a Java clone of PocketMine-MP (which it isn't a bad thing))

**Comment by ethsmith** [comment]
How did C++ sneak it's way in xD

**Comment by TheDiamondYT1** [comment]
It's the fastest language along with C according to tests

**Comment by TheDiamondYT1** [comment]
And Nukkit is a clone of PM

**Comment by Pet0203** [comment]
Isn't this getting off topic? xD

**Comment by sgdc3** [comment]
Stop talking about C and C++! D is the future! xD http://dlang.org/

**Comment by ethsmith** [comment]
Cool languages only please, lol jk xD Ok yeah let's get back on topic

**Comment by Pet0203** [comment]
Maybe we should vote about stopping or continuing development of dragonet?

**Comment by TheDiamondYT1** [comment]
Let me make a strawpoll

**Comment by TheDiamondYT1** [comment]
@DragonetMC/developers Post this link on twitter, Facebook, everywhere. Explain in the post a short description of what to do. And vote.

http://strawpoll.me/6607076

**Comment by ethsmith** [comment]
Not really sure anybody would have the team or one guy or girl has the time to take over Dragonet, but good idea adding that option :P

**Comment by Pet0203** [comment]
DragonProxy is clearly winning, I dont think there is any point in developing dragonet when dragonproxy already has the same functions AND allows you to connect to other servers.

**Comment by S0N-0F-A-S0N** [comment]
so we going to go by the poll?

On Wed, Jan 20, 2016 at 4:44 PM, Pet0203 notifications@github.com wrote:

> DragonProxy is clearly winning
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DragonetMC/Dragonet/issues/137#issuecomment-173386191
> .

## 

This communication is intended for the use of the individual or entity to
which it is addressed and may contain information that is privileged,
confidential, and/or exempt from disclosure under applicable laws. If the
reader of this communication is not the intended recipient or the employee
or agent responsible for delivering the communication to the intended
recipient, you are hereby notified that any dissemination, distribution or
copying of this communication is strictly prohibited. If you have received
this communication in error, please notify the sender immediately. This
notice applies to the original message, and all subsequent messages,
including without limitation replies, forwards, and copies.

_Elijah Keane_
http://www.s0ncraft.com/_http://www.s0ncraft.com/_
http://www.s0ncraft.com/

**Comment by TheDiamondYT1** [comment]
Idk maybe

**Comment by S0N-0F-A-S0N** [comment]
we should

On Fri, Jan 22, 2016 at 4:17 AM, Luke notifications@github.com wrote:

> Idk maybe
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DragonetMC/Dragonet/issues/137#issuecomment-173870135
> .

## 

This communication is intended for the use of the individual or entity to
which it is addressed and may contain information that is privileged,
confidential, and/or exempt from disclosure under applicable laws. If the
reader of this communication is not the intended recipient or the employee
or agent responsible for delivering the communication to the intended
recipient, you are hereby notified that any dissemination, distribution or
copying of this communication is strictly prohibited. If you have received
this communication in error, please notify the sender immediately. This
notice applies to the original message, and all subsequent messages,
including without limitation replies, forwards, and copies.

_Elijah Keane_
http://www.s0ncraft.com/_http://www.s0ncraft.com/_
http://www.s0ncraft.com/

**Comment by DefinitlyEvil** [comment]
Okay, Dragonet is abandoned.

**Comment by TheDiamondYT1** [comment]
I changed my mind. We should work on Dragonet as a side project.

We will restart the whole repo and make Dragonet the most efficient.

**Comment by TheDiamondYT1** [comment]
If you don't then I will work on some of it

**Comment by TheDiamondYT1** [comment]
Just a regular PE server software this time tho

**Comment by MrPowerGamerBR** [comment]
Why reinvent the wheel? Dragonet was special because it supported PE and PC
on the same server, if you are just going to create a PE server platform
then it is better to just use Nukkit (Java), ImagicalMine (PHP) or MiNET
(C#)
Em 27 de jan de 2016 9:42 AM, "Luke (TheDiamondYT)" <
notifications@github.com> escreveu:

**Comment by TheDiamondYT1** [comment]
ImagicalMine is just a fork of PocketMine, and its in PHP so that's a downside.

Nukkit is an (almost) exact copy of PocketMine done in Java

MiNET has a completely different API and is way faster but the API could do with ALOT of work and it isint in development much

I would prefer to make a server software in C# but nobdoy here seems to know C# so I wouldn't really get any help with it.....
It's very similar to java in some aspects, you can should try learn it. 

The reason I don't use MiNET is because
A) the developer hates me and blocked me on everything
B) its not under very much development
C) its only aimed at Windows
D) it needs a better and easier to use API

**Comment by TheDiamondYT1** [comment]
And why settle for what's there? We have 9 people (I think?) In this organization, and I'm sure others would contribute too. We could create the new best server software if we get off our asses and stop with small projects and work on this big one together.

Sure, everyone loves DragonProxy - don't stop developing that but why not have an actual server software with the same features as MCPE? Every other server software is always missing stuff.

PocketMine - Missing Hunger, Falling blocks, mobs, animals and alot more.
ImagicalMine - Basically the same but it has Hunger and a few more things
Nukkit - its basically missing same as PocketMine, but I think it has Hunger and basic Entity AI
MiNET - Its missing fall damage, Hunger, Entity AI (but has entity spawning), most block drops, most item uses, and more.

**Comment by MrPowerGamerBR** [comment]
Nukkit development is going strong (I follow Nukkit development because
probably I will create a MCPE Survival Server, and the developer implements
and fixed issues quickly), it would be better to help them than create a
new platform.
Em 27 de jan de 2016 11:29 AM, "Luke (TheDiamondYT)" <
notifications@github.com> escreveu:

**Comment by TheDiamondYT1** [comment]
You guys are just too lazy to do it yourself. Obviously not do a whole software yourself get a friend or a small team to help but if we all work together we can make Dragonet in C# (Because C# is well Quicker)

**Comment by MrPowerGamerBR** [comment]
Well, then do it, don't let your dreams be dreams.
Em 27 de jan de 2016 11:44 AM, "Luke (TheDiamondYT)" <
notifications@github.com> escreveu:

**Comment by S0N-0F-A-S0N** [comment]
JUST DO IT

On Wed, Jan 27, 2016 at 7:52 AM, MrPowerGamerBR notifications@github.com
wrote:

> Well, then do it, don't let your dreams be dreams.
> Em 27 de jan de 2016 11:44 AM, "Luke (TheDiamondYT)" <
> notifications@github.com> escreveu:
> 
> > You guys are just too lazy to do it yourself. Obviously not do a whole
> > software yourself get a friend or a small team to help but if we all work
> > together we can make Dragonet in C# (Because C# is well Quicker)
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/DragonetMC/Dragonet/issues/137#issuecomment-175633463>
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DragonetMC/Dragonet/issues/137#issuecomment-175636773
> .

## 

This communication is intended for the use of the individual or entity to
which it is addressed and may contain information that is privileged,
confidential, and/or exempt from disclosure under applicable laws. If the
reader of this communication is not the intended recipient or the employee
or agent responsible for delivering the communication to the intended
recipient, you are hereby notified that any dissemination, distribution or
copying of this communication is strictly prohibited. If you have received
this communication in error, please notify the sender immediately. This
notice applies to the original message, and all subsequent messages,
including without limitation replies, forwards, and copies.

_Elijah Keane_
http://www.s0ncraft.com/_http://www.s0ncraft.com/_
http://www.s0ncraft.com/

**Comment by TheDiamondYT1** [comment]
With @DefinitlyEvil's permission, I would like to restart Dragonet in C#. People on twitter voted on my poll and also would like it. You would need to restart the repo though.

**Comment by TheDiamondYT1** [comment]
And I need his permission as I can't delete a repo and recreate it.

**Comment by S0N-0F-A-S0N** [comment]
just create a new one?

On Wed, Jan 27, 2016 at 10:02 AM, Luke (TheDiamondYT) <
notifications@github.com> wrote:

> And I need his permission as I can't delete a repo and recreate it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DragonetMC/Dragonet/issues/137#issuecomment-175708937
> .

## 

This communication is intended for the use of the individual or entity to
which it is addressed and may contain information that is privileged,
confidential, and/or exempt from disclosure under applicable laws. If the
reader of this communication is not the intended recipient or the employee
or agent responsible for delivering the communication to the intended
recipient, you are hereby notified that any dissemination, distribution or
copying of this communication is strictly prohibited. If you have received
this communication in error, please notify the sender immediately. This
notice applies to the original message, and all subsequent messages,
including without limitation replies, forwards, and copies.

_Elijah Keane_
http://www.s0ncraft.com/_http://www.s0ncraft.com/_
http://www.s0ncraft.com/

**Comment by TheDiamondYT1** [comment]
I don't have permission for that

**Comment by TheDiamondYT1** [comment]
I could just **fork** MiNET, that never occurred to me xD

**Comment by TheDiamondYT1** [comment]
@DefinitlyEvil Can you fork https://github.com/niclasolofsson/minet

**Comment by ethsmith** [comment]
Why C# you may think it's faster but bro when it gets down to its based on how well the application was developed, if you are better at C# go for it but no point in struggling because someone told you it was supposedly faster. I have no interest in C# tbh I will stick with Python, Java, and PHP that basically suffices all my needs for programming and I'd rather improve my skills on a language I already know then learn another if there is no reason to xD just my 2 cents

**Comment by mastercoms** [comment]
i know c#. it is an awful language to me. also, i would love to see benchmarks proving c# is faster

**Comment by mastercoms** [comment]
of course, thats just my opinion. i prefer to use something that isnt c#. but if you like it, use it. but dont go around claiming its the best language when there really isnt a difference. c# has its uses, and java does as well. there is no one best language.

**Comment by TheDiamondYT1** [comment]
Nvm

**Comment by Pet0203** [comment]
So dragonet plugins are going to be on C# too?

**Comment by TheDiamondYT1** [comment]
I said nvm read it

**Comment by TheDiamondYT1** [comment]
@DefinitlyEvil Why can't we create a new Dragonet repo (To clear commits, issues and PRs) and just make a branch with the old code which is here? 

I think we can mirror it so the old branch would have same commits as here somehow idk how

**Comment by DefinitlyEvil** [comment]
@RandomAltThingy I am gonna make the old one a history. Or, we rename it to `Dragonet-Legacy`.

**Comment by TheDiamondYT1** [comment]
@DefinitlyEvil

1) People don't care about history (Well most people)
2) Make it Dragonet-OLD

**Comment by DefinitlyEvil** [comment]
@RandomAltThingy Okay.

**Comment by mastercoms** [comment]
There's literally no reason not to keep it. GitHub gives you unlimited free repos.

**Comment by DefinitlyEvil** [comment]
@mastercoms I just wanna keep my work. DO NOT DELETE IT please.
