### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by dancing-ipsum** [DragonetMC/Dragonet-Legacy#138]
Feature enhancement: Implementing Modded Spigot into Dragonet (TBWO)

**Comment by DefinitlyEvil** [comment]
We are sorry but we are stopped supporting Dragonet and we've switched to DragonProxy(much more better).

**Comment by dancing-ipsum** [comment]
DragonProxy is a proxy that lets you connect to PC servers, not PE and PC cross platform multiplay.

**Comment by MrPowerGamerBR** [comment]
@MCPEGamerJPatGitHub well, it is cross platform multiplayer if you use the proxy.

**Comment by S0N-0F-A-S0N** [comment]
gay

On Friday, January 22, 2016, MrPowerGamerBR <notifications@github.com>
wrote:

> @MCPEGamerJPatGitHub <https://github.com/MCPEGamerJPatGitHub> well, it is
> cross platform multiplayer if you use the proxy.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DragonetMC/Dragonet/issues/138#issuecomment-174018255>
> .
>


-- 
This communication is intended for the use of the individual or entity to
which it is addressed and may contain information that is privileged,
confidential, and/or exempt from disclosure under applicable laws. If the
reader of this communication is not the intended recipient or the employee
or agent responsible for delivering the communication to the intended
recipient, you are hereby notified that any dissemination, distribution or
copying of this communication is strictly prohibited. If you have received
this communication in error, please notify the sender immediately. This
notice applies to the original message, and all subsequent messages,
including without limitation replies, forwards, and copies.

*Elijah Keane*
<http://www.s0ncraft.com/>*http://www.s0ncraft.com/*
<http://www.s0ncraft.com/>

**Comment by fe1a** [comment]
@S0N-0F-A-S0N Don't use words like that

**Comment by ghost** [comment]
lol

**Comment by TheDiamondYT1** [comment]
I deleted his comment xD
