### ISSUE TITLE
Delete this repository and restart

### ISSUE THREAD

**Issue by TheDiamondYT1** [DragonetMC/Dragonet-Legacy#139]
Delete it and recreate with access for me I didn't like this project because 70% of the code was glowstone code. It's better to just make our own and optimize for PE. I will recreate it, in java, and hopefully we can get more people contributing to both this and the proxy.

**Comment by sgdc3** [comment]
why delete? just rename it to -legacy

**Comment by sgdc3** [comment]
Never delete something ;) How can you think to the future without the knowledges of the past?

**Comment by TheDiamondYT1** [comment]
Why would we not delete and start again? Who cares about old versions if you can have new ones.

**Comment by sgdc3** [comment]
yeah but you can keep also old deprecated versions, it's free, why not? It may be useful in the future, who knows?

**Comment by TheDiamondYT1** [comment]
Nah.

It is for an older version of MCPE, it uses an older, forked version of GlowStonePlusPlus, too many bugs.

It's abandoned so I am starting it again

**Comment by sgdc3** [comment]
yeah but keep the old source online! xD forgot about them, but keep them

**Comment by TheDiamondYT1** [comment]
No

**Comment by DefinitlyEvil** [comment]
@RandomAltThingy I will not delete my works because I put so much effort into it, I will just rename it as @sgdc3 said.

**Comment by TheDiamondYT1** [comment]
:(

**Comment by TheDiamondYT1** [comment]
@DefinitlyEvil I'm such an idiot. I could just change the master branch!

Can you rename it back please?

**Comment by DefinitlyEvil** [comment]
@RandomAltThingy It's a separate project(from zero) so it should be re-created.

**Comment by TheDiamondYT1** [comment]
@DefinitlyEvil Not neccercarily. It's the same project in the same coding language just a new version that's different in some ways

**Comment by DefinitlyEvil** [comment]
Well.... I am just renaming it back and you have to take care of it. xD

**Comment by TheDiamondYT1** [comment]
@DefinitltEvil It would be easier to give me admin access to the organization, as ive realised another problem so I will start the project in a new repo.

(The problem is there is already over 200 issues and pull requests so restarting it might be a problem. Or not, I could continue in this repo but I would still need admin access/an admin to change some settings for me.)

**Comment by DefinitlyEvil** [comment]
@RandomAltThingy No, sorry I can't let you mess things up. xD

**Comment by TheDiamondYT1** [comment]
@DefinitlyEvil I think I know what I'm doing

**Comment by DefinitlyEvil** [comment]
@RandomAltThingy Do not delete the repo.

**Comment by TheDiamondYT1** [comment]
Yeah yeah

**Comment by Pet0203** [comment]
@RandomAltThingy so you are going to re-develop dragonet?
