### ISSUE TITLE
0.10.5 PE support.

### ISSUE THREAD

**Issue by bennasar99** [DragonetMC/Dragonet-Legacy#14]
First of all I have to say I really like the idea of an "universal server". Thank you for trying this and keep going.

It seems I cannot login using MCPE 0.10.5? I read it supports 0.10.x but it doesn't seem to work with 0.10.5

**Comment by herenickname** [comment]
I like to, becouse BigBrother not have update.
Dragonet better than pocketmine.

**Comment by DefinitlyEvil** [comment]
@TheMCPEGamer :)

**Comment by L3ice** [comment]
Ehm they changed nothing in the protocol for 0.10.5...
Pocketmine also only changed the versionnumber to 0.10.5

**Comment by wordandahalf** [comment]
@tonibm19 I am looking into this issue, may just be a version-ing issue, but you never know.

**Comment by wordandahalf** [comment]
Weird... In the code, the version supports 0.10.5...

**Comment by wordandahalf** [comment]
Just tested it and it worked fine.
