### ISSUE TITLE
Like To Take Over

### ISSUE THREAD

**Issue by EdwardHamHam** [DragonetMC/Dragonet-Legacy#140]
Hi, I am a PocketMine plugin developer, and I know Java as well. I would like to take this project over, and work on it with my team.

**Comment by S0N-0F-A-S0N** [comment]
Lol

**Comment by EdwardHamHam** [comment]
What?

**Comment by MrPowerGamerBR** [comment]
@Edwardthedog2 Dragonet isn't developed anymore, and DragonProxy... well, I don't know what they are doing with it.

Well, you don't need permission to take over, just fork and continue the project if you want to.

**Comment by EdwardHamHam** [comment]
Okay.

**Comment by S0N-0F-A-S0N** [comment]
obv

On Wed, Mar 2, 2016 at 5:16 PM, Edwardthedog2 <notifications@github.com>
wrote:

> Okay.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DragonetMC/Dragonet-Dusty/issues/140#issuecomment-191488628>
> .
>



-- 
This communication is intended for the use of the individual or entity to
which it is addressed and may contain information that is privileged,
confidential, and/or exempt from disclosure under applicable laws. If the
reader of this communication is not the intended recipient or the employee
or agent responsible for delivering the communication to the intended
recipient, you are hereby notified that any dissemination, distribution or
copying of this communication is strictly prohibited. If you have received
this communication in error, please notify the sender immediately. This
notice applies to the original message, and all subsequent messages,
including without limitation replies, forwards, and copies.

*Elijah Keane*
<http://www.s0ncraft.com/>*http://www.s0ncraft.com/*
<http://www.s0ncraft.com/>

**Comment by mastercoms** [comment]
In the readme it says to create an issue if you want to take over this project.

I can't believe that this innocent issue would get such a response.

**Comment by S0N-0F-A-S0N** [comment]
lol

On Thu, Mar 3, 2016 at 2:53 PM, mastercoms <notifications@github.com> wrote:

> In the readme it says to create an issue if you want to take over this
> project.
>
> I can't believe that this innocent issue would get such a response.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DragonetMC/Dragonet-Dusty/issues/140#issuecomment-191957835>
> .
>



-- 
This communication is intended for the use of the individual or entity to
which it is addressed and may contain information that is privileged,
confidential, and/or exempt from disclosure under applicable laws. If the
reader of this communication is not the intended recipient or the employee
or agent responsible for delivering the communication to the intended
recipient, you are hereby notified that any dissemination, distribution or
copying of this communication is strictly prohibited. If you have received
this communication in error, please notify the sender immediately. This
notice applies to the original message, and all subsequent messages,
including without limitation replies, forwards, and copies.

*Elijah Keane*
<http://www.s0ncraft.com/>*http://www.s0ncraft.com/*
<http://www.s0ncraft.com/>

**Comment by TheDiamondYT1** [comment]
Hi, 

First please show us some of your previous work in Java. After that, @DefinitlyEvil can decide whether to invite you to the organization or not.

Thanks for taking an interest in developing Dragonet!

**Comment by ethsmith** [comment]
He does not need to show his skill, he can fork it and work on it. If he wants us to transfer ownership of this repo then maybe he could send a few PR's first to show he is actually motivated to update this but he can always fork this. I imagine if anything he would want the repo transferred to his account instead of joining this org but maybe not

**Comment by DefinitlyEvil** [comment]
@TekkitCommando Agree.

**Comment by EdwardHamHam** [comment]
Okay, I think I'll just fork it.

**Comment by EdwardHamHam** [comment]
Okay, I am now developing a third-party build of it at: [here](https://github.com/EurekaMineTeam/EurekaMine-MP)

**Comment by TheDiamondYT1** [comment]
please invite me to the GitHub org @Edwardthedog2

**Comment by EdwardHamHam** [comment]
@TheDiamondYT1 Okay, I have added you.

**Comment by ethsmith** [comment]
@Edwardthedog2 Add me to just in case you decide to work with the PHP stuff.
