### ISSUE TITLE
Glowstone license text removed 

### ISSUE THREAD

**Issue by dequis** [DragonetMC/Dragonet-Legacy#15]
Hey! I noticed this is a fork of glowstone but the license text was removed, and replaced with LGPL license.

The MIT license under which glowstone is distributed has a single requirement "The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software":

https://github.com/GlowstoneMC/Glowstone/blob/master/LICENSE

Also, if you intend to keep the LGPL license, you need to specify what files are under the MIT license and copyrighted by spacemaniac et al, and what files are under the LGPL and copyrighted by your team.

**Comment by gdude2002** [comment]
+1 can confirm

**Comment by DefinitlyEvil** [comment]
I am so sorry about this mistake. So what should we do? Just copy a MIT licence file into this repo? I want to keep the Glowstone's licence and only apply LGPL licence to our code, but I don't know how to do it. xD

**Comment by DefinitlyEvil** [comment]
@TheMCPEGamer

**Comment by DefinitlyEvil** [comment]
@dequis @gdude2002 Oh I got your means, I will add it right away! :)

**Comment by DefinitlyEvil** [comment]
done, please reply if it's fine and then I can close the issue. :)

**Comment by gdude2002** [comment]
This may be better explained by @SpaceManiac or @turt2live, but I don't believe what you've done is correct. Some relevant info [here](https://en.wikipedia.org/wiki/Multi-licensing), but IANAL.

**Comment by turt2live** [comment]
From my understanding, you've incorrectly referenced Glowstone in several ways. Not to mention I'm not 100% sure you can include MIT code in a LGPL project (you may be able to if this project were GPL). I suggest contacting a lawyer as I have no legal obligation or standing to represent the licensing claims.

**Comment by SpaceManiac** [comment]
Hi! It's always nice to see people doing interesting things with Minecraft, and your project looks spiffy.

The MIT license is very permissive, and you may distribute/sublicense/etc. the Glowstone code freely.

The license does, however, requires including a copy of the LICENSE file along with any substantial portions of the Glowstone source code. My request is that you include the entire contents of Glowstone's `LICENSE` file in your repository, perhaps under the name `LICENSE-Glowstone` or something similar. If you wish, you may also precede it with a note describing which packages portions of the code are from Glowstone, as in:

```
<your text here>

<copy-pasted LICENSE from Glowstone>
```

I do not know what the LGPL requires with regards to linking - you should consult with the text of the LGPL or a lawyer to figure that out. The MIT license that Glowstone is under should not be causing any problems directly.

**Comment by wordandahalf** [comment]
Will do shortly

**Comment by wordandahalf** [comment]
Done. Please re-open this issue if I did not do it correctly.

**Comment by gdude2002** [comment]
From the LGPL:

```
A “Combined Work” is a work produced by combining or linking an Application with
the Library. The particular version of the Library with which the Combined Work was
made is also called the “Linked Version”.

[...]

You may convey a Combined Work under terms of your choice that, taken together,
effectively do not restrict modification of the portions of the Library contained in the
Combined Work and reverse engineering for debugging such modifications, if you
also do each of the following:
```

Definitely recommend reading it.

By the way, if you close someone's ticket, they can't open it again, just fyi.

**Comment by DefinitlyEvil** [comment]
@TheMCPEGamer

**Comment by wordandahalf** [comment]
@gdude2002 I honestly cannot understand the wording of the snippet, did I fix it correctly, or did I do something stupid?

**Comment by gdude2002** [comment]
@TheMCPEGamer The problem is I'm not entirely sure myself, lol. There are several ways to do this, though.
- Be specific about what license applies to what
- Use git submodules to avoid having to reupload the Glowstone stuff in the first place (recommended)
- Relicense your project to match Glowstone's

The snipped I pasted was actually part of the LGPL, which I also found in [this StackOverflow question](https://stackoverflow.com/questions/2506916/lgpl-to-mit-license)

**Comment by wordandahalf** [comment]
@gdude2002 Thanks, I will most likely do the first one

**Comment by gdude2002** [comment]
@TheMCPEGamer I seriously recommend submodules, but hey, it's your project, right? :P

**Comment by wordandahalf** [comment]
@gdude2002  xD
If you see no more issues, I'll just go ahead and close this

**Comment by wordandahalf** [comment]
Closed.
