### ISSUE TITLE
Is it stable enough to run MCPE Worlds Only?

### ISSUE THREAD

**Issue by yungtechboy1** [DragonetMC/Dragonet-Legacy#16]
I want to use this solely for MCPE Minecraft not MC PC Version.
Can I do this?

**Comment by yungtechboy1** [comment]
Also COuld you Make a Java MCPE Launcher only?

**Comment by Creeperface01** [comment]
Dragonet is for PC edition and MCPE, but you can import only PC maps.

**Comment by Creeperface01** [comment]
Option for join only from MCPE will maybe added later.

**Comment by wordandahalf** [comment]
@yungtechboy1 The purpose of this server software is to unite the PC/PE experience, if you want a server solely for MC:PE clients I recommend using PocketMine (https://www.pocketmine.net/).
