### ISSUE TITLE
Projects Transfer Back

### ISSUE THREAD

**Issue by DefinitlyEvil** [DragonetMC/Dragonet-Legacy#17]
Let's transfer those projects back to DragonetMC organization. 
It is more formal. 
First, you transfer to me and I transfer to the orgainzation account. Also the domain will work that way. :) 
@TheMCPEGamer

**Comment by wordandahalf** [comment]
OK

**Comment by DefinitlyEvil** [comment]
Have you done that yet? :O

**Comment by wordandahalf** [comment]
@DefinitlyEvil I've requested it.
