### ISSUE TITLE
[Complete - Beta] Allow DAPISes to create their own functions and methods

### ISSUE THREAD

**Issue by ashquarky** [DragonetMC/Dragonet-Legacy#22]
So, I was having a look at #21, and I came up with a really cool idea: what about allowing scripts to create their own functions and methods? Something like this:

``` javascript
var Scripts = new ScriptAPI();

function onInit() { //or something like that, it'll have to be added...
    Scripts.addFunction("onOver9000", this); //("name of function OTHER scripts will implement", actual function itself (not too sure how Rhino handles this so just "this" for now))
    Scripts.addMethod("removePineapples", "removePineapples_handle", this) //("Method other scripts can call", "what to do when this happens", this)

    //Now we can demonstrate "onOver9000" use
    Scripts.callCustomFunction("onOver9000");
    //All scripts implementing onOver9000 will now have it called
}

function removePineapples_handle() {
    //Whatever we want to do when another script calls "removePineapples"
    int i = 6;
    i = i - 1000;
    super(i);
}
```

Now here's an example of a script that uses these methods:

``` javascript
var Scripts = new ScriptAPI();

function onOver9000() {
    Scripts.callCustomMethod("removePineapples");
}
```

I think this could result in an incredibly versatile system: If a method hasn't been made yet, someone can just create a script that does it (by calling various org.bukkit.whatever methods) instead of everyone having to do it themselves. Someone could take such a system and make something almost like Vault out of it. Other uses include chat filters being able to allow other scripts to mess with their whitelists, permissions scripts (Ooh, that's an idea), and a whole range of other stuff.
It wouldn't be that hard to do, since Rhino is heavily dependent on strings; there could just be a Java class to keep track of who has what function, and then the ScriptAPI class can just call runFunction(str). If we do it right, it could rival Bukkit's plugin system.

So, what do you think? Cool? A waste of time? I'd like to know before I start sinking hours into it ;3

**Comment by wordandahalf** [comment]
@QuarkTheAwesome Great idea! I'll see if I can do this after I change all the functions!

**Comment by ashquarky** [comment]
Thanks! I can lend a hand if you want.

**Comment by wordandahalf** [comment]
@QuarkTheAwesome If you could work on the ScriptAPI, that would be great!

**Comment by ashquarky** [comment]
@TheMCPEGamer Sure, I'll stick it on a branch of my fork. 
https://github.com/QuarkTheAwesome/Dragonet/tree/scriptAPI , perhaps? I'll work on it when I get home.

**Comment by wordandahalf** [comment]
That'll work!
