### ISSUE TITLE
A New Thread on MinecraftForums?

### ISSUE THREAD

**Issue by DefinitlyEvil** [DragonetMC/Dragonet-Legacy#23]
Since I quit, I lost my account's password on MinecraftForums and you should probably make another new thread to tell the world this awesome project.

**Comment by Creeperface01** [comment]
OK :) and have you given me permissions to dragonet addon repository?

**Comment by ashquarky** [comment]
@DefinitlyEvil Can't you just send a password reset email? Other than that, I agree that the current thread does need a bit of a redo...

**Comment by wordandahalf** [comment]
@Creeperface01 I'll make a logo for Dragonet if you want :smile:

**Comment by Creeperface01** [comment]
Thanks :)

**Comment by DefinitlyEvil** [comment]
@QuarkTheAwesome I will try that.

**Comment by DefinitlyEvil** [comment]
Done!

**Comment by wordandahalf** [comment]
@Creeperface01 Does this look good? ![Dragonet Logo](http://i.imgur.com/5sxA9c1.png)

**Comment by DefinitlyEvil** [comment]
You should find something special for the word Dragonet.
