### ISSUE TITLE
Add getServer() method to DSAPI.

### ISSUE THREAD

**Issue by DefinitlyEvil** [DragonetMC/Dragonet-Legacy#24]
You can add a `getServer()` method to the DSAPI so developers can do whatever they want to the server. 
They can do:
`getServer().shutdown()` to stop server. 
`getServer().getPluginManager().getPlugin("Essentials")` to interact with Bukkit plugins. 
and more...

**Comment by ashquarky** [comment]
Support. Totally need getPlugin ;3

**Comment by DefinitlyEvil** [comment]
@QuarkTheAwesome Just need to add a single getServer() method, and you should let Script class extends PluginBase to make it a plugin.

**Comment by wordandahalf** [comment]
I added it in commit 18a1019.
