### ISSUE TITLE
Website: 404 on dragonet.org

### ISSUE THREAD

**Issue by ashquarky** [DragonetMC/Dragonet-Legacy#26]
Hiya!

So, recently I went on the site (http://dragonet.org/) and found that it wasn't working anymore! http://themcpegamer.github.io/Dragonet/ still works as expected and stats.dragonet.org works just fine (in dire need of some CSS theming, but working none the less), but the root domain looks like it's broken. It does get through to GitHub (they've provided the 404) but it doesn't find its way to the gh-pages branch.

Just wondering what's going on and if you guys need a hand with it.

-Ash

**Comment by wordandahalf** [comment]
@QuarkTheAwesome I think it's because the domain is linked to the old Dragonet repository, which does not exist anymore.

**Comment by DefinitlyEvil** [comment]
Dude transfer the projects back to the organisation's account and domain will work. :)

**Comment by wordandahalf** [comment]
The domain now works :D
