### ISSUE TITLE
Friend

### ISSUE THREAD

**Issue by mindcoding** [DragonetMC/Dragonet-Legacy#27]
My friend is making a MCPE and I recommended Dragonet to her but she had questions that I could not answer.

1) Can you use a MCPC world?

2) Do you need to buy a MCPE server or MCPC server?

3) Is it buggy for PE or PC players?

4) How do you set it up step by step?

Thanks,
MindcraftminD

**Comment by Creeperface01** [comment]
1) yes! 
2) you can host dragonet on your PC
3) yes :/ for nos
4) look on glowstone tutorials

**Comment by mindcoding** [comment]
Thank you
