### ISSUE TITLE
Domains

### ISSUE THREAD

**Issue by mindcoding** [DragonetMC/Dragonet-Legacy#28]
How will you use domains?

**Comment by ashquarky** [comment]
You'd set up a domain just as you would with any other Glowstone/Bukkit server. You just have to remember to allow both ports 25565 _and_ 19132. Simply direct those 2 into the same server box and you'll be good to go.

As for hosting services like MCProHosting, you'll have to send them a support email. I think you can do it with a dedicated IP (one of the extras they do) but I'd check with them before splashing out on one.

**Comment by DefinitlyEvil** [comment]
You can ask them for sponsorship.

**Comment by wordandahalf** [comment]
Since this isn't really an issue with Dragonet, I'm going to close it
