### ISSUE TITLE
Essentials

### ISSUE THREAD

**Issue by mindcoding** [DragonetMC/Dragonet-Legacy#29]
Essentials is giving a weird error that without Dragonet would not occur.

**Comment by wordandahalf** [comment]
What is the error?

**Comment by DefinitlyEvil** [comment]
Glowstone's issue. Seems to be the guava version's problem. 
@gdude2002

**Comment by mastercoms** [comment]
Just use https://hub.spigotmc.org/jenkins/job/Spigot-Essentials/

**Comment by ethsmith** [comment]
^

**Comment by gdude2002** [comment]
@DefinitlyEvil Why do you highlight me on all these tickets? There's a bunch of stuff you could just link to directly, if you actually took the time to search our tickets.

**Comment by mastercoms** [comment]
Didn't realize you were subscribed, sorry for bumping this, and filling up your inbox.

**Comment by DefinitlyEvil** [comment]
@gdude2002 I'm sorry about that, you may click unsubsribe button to ignore messages on this issue. xD

**Comment by ethsmith** [comment]
I just moved and I am back Wednesday, and as soon as I get back I am have two meetings I have to attend, and I have to brief a group of new entrepreneurs on what is accepted in our work environment, Always Busy with work (MC Server Bank) xD

**Comment by DefinitlyEvil** [comment]
@TekkitCommando Okay, have a nice day. :3

**Comment by ethsmith** [comment]
@DefinitlyEvil Thanks xD
