### ISSUE TITLE
Chat lagging

### ISSUE THREAD

**Issue by mindcoding** [DragonetMC/Dragonet-Legacy#33]
It takes about 4 minutes before I see some chat I send 4 minutes before.

**Comment by ashquarky** [comment]
We keep telling you that this is a problem with your internet/wifi speeds. You'll have to fix this yourself (although 4 minutes seems a bit much)

**Comment by mindcoding** [comment]
I know and I am sorry but I believe it is to many packets for the server to handle because it goes through each packet at .04 seconds also my friend had very similar results.

**Comment by mindcoding** [comment]
I also think it has something todo with UDP to TCP

**Comment by wordandahalf** [comment]
@mindcoding I've been using the PC version, and it works fine, but I'm not sure about the PE version though

**Comment by mindcoding** [comment]
Yeah I was getting same results PC is good PE is bad. Any fixes besides my internet.

**Comment by mindcoding** [comment]
Final point before you respond should you host it on pc/pe

**Comment by mindcoding** [comment]
Bump

**Comment by wordandahalf** [comment]
You should host the server on a PC/Mac, as Minecraft servers require at least 2 GB of RAM to run smoothly

**Comment by mindcoding** [comment]
Ok any suggestions with packets overloading the server?

**Comment by DefinitlyEvil** [comment]
No idea why is it happening.

**Comment by mindcoding** [comment]
Do you want to the logs

**Comment by wordandahalf** [comment]
@mindcoding Yea, that'll help.

**Comment by mindcoding** [comment]
Here is a section of the logs that shows what is happening @TheMCPEGamer 

29.03 13:54:30 [Multicraft] Skipped 2106 lines due to rate limit (100/s)
29.03 13:54:18 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:54:18 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:54:18 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:54:18 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:54:18 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:54:18 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:54:18 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:54:18 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:54:18 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:54:18 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:54:18 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:54:18 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:54:18 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:54:18 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:54:18 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:54:18 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:54:18 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:54:18 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:54:18 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:54:18 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:54:18 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:54:18 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:54:18 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:54:18 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:54:18 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:54:18 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:54:18 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:54:18 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:54:18 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:54:18 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:54:18 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:54:18 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:54:18 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:54:18 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:54:18 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:54:18 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:54:18 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:54:18 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:54:18 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:54:18 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:54:18 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:54:18 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:54:18 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:54:18 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:54:18 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:54:18 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:54:18 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:54:18 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:54:18 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:54:18 [Server] INFO PE player [MindcraftminD] has spawned. 
29.03 13:53:39 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:53:39 [Server] INFO Sending queued: MovePlayerPacket
29.03 13:53:39 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:53:39 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:53:39 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:53:39 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:53:39 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:53:38 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:53:38 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:53:38 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:53:38 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:53:38 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:53:38 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:53:38 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:53:38 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:53:38 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:53:38 [Server] INFO Sending queued: UpdateBlockPacket
29.03 13:53:38 [Server] INFO Sending queued: AnimatePacket
29.03 13:53:38 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:53:38 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:53:38 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:53:38 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:53:38 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:53:38 [Server] INFO Sending queued: PlayerEquipmentPacket
29.03 13:53:38 [Server] INFO Sending queued: AddPlayerPacket
29.03 13:53:38 [Server] INFO Sending queued: SetEntityMotionPacket
29.03 13:53:38 [Server] INFO Sending queued: AddItemEntityPacket
29.03 13:53:38 [Server] INFO Sending queued: UpdateBlockPacket
29.03 13:53:38 [Server] INFO Sending queued: MessagePacket
29.03 13:53:38 [Server] INFO Sending queued: SetHealthPacket
29.03 13:53:38 [Server] INFO Sending queued: SetSpawnPositionPacket
29.03 13:53:38 [Server] INFO Sending queued: WindowItemsPacket
29.03 13:53:38 [Server] INFO Sending queued: WindowItemsPacket
29.03 13:53:38 [Server] INFO Sending queued: SetEntityMotionPacket

**Comment by mindcoding** [comment]
Bump

**Comment by mindcoding** [comment]
Bump

**Comment by Creeperface01** [comment]
I have sending messages fast and my friends too. You have slow internet conection.

**Comment by mindcoding** [comment]
That was from a paid server. So I do not see your point.

**Comment by ashquarky** [comment]
Did you build from source or just download off the website? 

That packet stream looks like what happens when a player joins, is it constant?

**Comment by mindcoding** [comment]
1) The 0.0.1-beta from website
2) Yes

**Comment by ashquarky** [comment]
0.0.1-beta isn't the latest version, can you use Gradle to build from source? [You should end up with 0.0.2-preR1 or something]

**Comment by mindcoding** [comment]
Can you send me the link?

**Comment by ashquarky** [comment]
[On Windows] Download the source code (https://github.com/DragonetMC/Dragonet/archive/master.zip) then download gradle (https://services.gradle.org/distributions/gradle-2.3-all.zip). After unzipping both of these, go into Dragonet/dragonet-master [there should be an etc and src folder, and a bunch of files]. Hold shift and right-click, then click "Open command window here". Then open gradle/gradle/bin [Files: gradle and gradle.bat, nothing else] and drag that into your command window. Hit enter and the build should begin!

Once it's done, go into Dragonet/dragonet-master/build/libs. Dragonet-0.0.2-preR1-**all**.jar is your server software.

**Comment by mindcoding** [comment]
Thanks

**Comment by mindcoding** [comment]
30.03 17:33:17 [Server] INFO turtlecubed left the game
30.03 17:33:17 [Server] INFO turtlecubed [null] lost connection
30.03 17:33:16 [Server] INFO Reverted movement! 
30.03 17:33:16 [Server] INFO Reverted movement! 
30.03 17:33:16 [Server] INFO Reverted movement! 
30.03 17:33:16 [Server] INFO Reverted movement! 
30.03 17:33:16 [Server] INFO Reverted movement! 
30.03 17:33:16 [Server] INFO Reverted movement! 
30.03 17:33:16 [Server] INFO Reverted movement! 
30.03 17:33:16 [Server] INFO Reverted movement! 
30.03 17:33:16 [Server] INFO Reverted movement! 
30.03 17:33:16 [Server] INFO Reverted movement! 
30.03 17:33:16 [Server] INFO Reverted movement! 
30.03 17:33:16 [Server] INFO Reverted movement! 
30.03 17:33:16 [Server] INFO Reverted movement! 
30.03 17:33:16 [Server] INFO Reverted movement! 
30.03 17:33:16 [Server] INFO Reverted movement! 
30.03 17:33:16 [Server] INFO Reverted movement! 
30.03 17:33:16 [Server] INFO Reverted movement! 
30.03 17:33:15 [Server] INFO Reverted movement! 
30.03 17:33:15 [Server] INFO Reverted movement! 
30.03 17:33:15 [Server] INFO Reverted movement! 
30.03 17:33:15 [Server] INFO Reverted movement! 
30.03 17:33:15 [Server] INFO Reverted movement! 
30.03 17:33:15 [Server] INFO Reverted movement! 
30.03 17:33:15 [Server] INFO Reverted movement! 
30.03 17:33:15 [Server] INFO Reverted movement! 
30.03 17:33:15 [Server] INFO Reverted movement! 
30.03 17:33:15 [Server] INFO Reverted movement! 
30.03 17:33:15 [Server] INFO Reverted movement! 
30.03 17:33:15 [Server] INFO Reverted movement! 
30.03 17:33:15 [Server] INFO Reverted movement! 
30.03 17:33:15 [Server] INFO Reverted movement! 
30.03 17:33:15 [Server] INFO Reverted movement! 
30.03 17:33:15 [Server] INFO Reverted movement! 
30.03 17:33:15 [Server] INFO Reverted movement! 
30.03 17:33:15 [Server] INFO Reverted movement! 
30.03 17:33:15 [Server] INFO Reverted movement! 
30.03 17:33:15 [Server] INFO Reverted movement! 
30.03 17:33:15 [Server] INFO Reverted movement! 
30.03 17:33:14 [Server] INFO Reverted movement! 
30.03 17:33:14 [Server] INFO Reverted movement! 
30.03 17:33:14 [Server] INFO Reverted movement! 
30.03 17:33:14 [Server] INFO Reverted movement! 
30.03 17:33:14 [Server] INFO Reverted movement! 
30.03 17:33:14 [Server] INFO Reverted movement! 
30.03 17:33:14 [Server] INFO Reverted movement! 
30.03 17:33:14 [Server] INFO Reverted movement! 
30.03 17:33:14 [Server] INFO Reverted movement! 
30.03 17:33:14 [Server] INFO Reverted movement! 
30.03 17:33:12 [Server] INFO Reverted movement! 
30.03 17:33:12 [Server] INFO Reverted movement! 
30.03 17:33:12 [Server] INFO Reverted movement! 
30.03 17:33:12 [Server] INFO Reverted movement! 
30.03 17:33:12 [Server] INFO Reverted movement! 
30.03 17:33:12 [Server] INFO Reverted movement! 
30.03 17:33:12 [Server] INFO Reverted movement! 
30.03 17:33:12 [Server] INFO Reverted movement! 
30.03 17:33:12 [Server] INFO Reverted movement! 
30.03 17:33:12 [Server] INFO Reverted movement! 
30.03 17:33:12 [Server] INFO Reverted movement! 
30.03 17:33:12 [Server] INFO Reverted movement! 
30.03 17:33:12 [Server] INFO Reverted movement! 
30.03 17:33:12 [Server] INFO Reverted movement! 
30.03 17:33:12 [Server] INFO Reverted movement! 
30.03 17:33:12 [Server] INFO Reverted movement! 
30.03 17:33:12 [Server] INFO Reverted movement! 
30.03 17:33:12 [Server] INFO Reverted movement! 
30.03 17:33:12 [Server] INFO Reverted movement! 
30.03 17:33:12 [Server] INFO Reverted movement! 
30.03 17:33:12 [Server] INFO Reverted movement! 
30.03 17:33:12 [Server] INFO Reverted movement! 
30.03 17:33:12 [Server] INFO Reverted movement! 
30.03 17:33:12 [Server] INFO Reverted movement! 
30.03 17:33:12 [Server] INFO Reverted movement! 
30.03 17:33:11 [Server] INFO Reverted movement! 
30.03 17:33:11 [Server] INFO Reverted movement! 
30.03 17:33:11 [Server] INFO Reverted movement! 
30.03 17:33:11 [Server] INFO Reverted movement! 
30.03 17:33:11 [Server] INFO Reverted movement! 
30.03 17:33:09 [Server] INFO Reverted movement! 
30.03 17:33:09 [Server] INFO Reverted movement! 
30.03 17:33:09 [Server] INFO Reverted movement! 
30.03 17:33:09 [Server] INFO Reverted movement! 
30.03 17:33:09 [Server] INFO Reverted movement! 
30.03 17:33:09 [Server] INFO Reverted movement! 
30.03 17:33:09 [Server] INFO Reverted movement! 
30.03 17:33:09 [Server] INFO Reverted movement! 
30.03 17:33:09 [Server] INFO Reverted movement! 
30.03 17:33:09 [Server] INFO Reverted movement! 
30.03 17:33:09 [Server] INFO Reverted movement! 
30.03 17:33:09 [Server] INFO Reverted movement! 
30.03 17:33:09 [Server] INFO Reverted movement! 
30.03 17:33:09 [Server] INFO Reverted movement! 
30.03 17:33:09 [Server] INFO Reverted movement! 
30.03 17:33:09 [Server] INFO Reverted movement! 
30.03 17:33:09 [Server] INFO Reverted movement! 
30.03 17:33:09 [Server] INFO Reverted movement! 
30.03 17:33:09 [Server] INFO Reverted movement! 
30.03 17:33:08 [Server] INFO Reverted movement! 
30.03 17:33:08 [Server] INFO Reverted movement! 
30.03 17:33:08 [Server] INFO Reverted movement! 
30.03 17:33:08 [Server] INFO Reverted movement! 
30.03 17:33:08 [Server] INFO Reverted movement! 
30.03 17:33:08 [Server] INFO Reverted movement! 
30.03 17:33:08 [Server] INFO Reverted movement! 
30.03 17:33:08 [Server] INFO Reverted movement! 
30.03 17:33:08 [Server] INFO Reverted movement! 
30.03 17:33:08 [Server] INFO Reverted movement! 
30.03 17:33:08 [Server] INFO Reverted movement! 
30.03 17:33:08 [Server] INFO Reverted movement! 
30.03 17:33:08 [Server] INFO Reverted movement! 
30.03 17:33:08 [Server] INFO Reverted movement! 
30.03 17:33:08 [Server] INFO Reverted movement! 
30.03 17:33:08 [Server] INFO Reverted movement! 
30.03 17:33:08 [Server] INFO Reverted movement! 
30.03 17:33:08 [Server] INFO Reverted movement! 
30.03 17:33:08 [Server] INFO Reverted movement! 
30.03 17:33:08 [Server] INFO Reverted movement! 
30.03 17:33:07 [Server] INFO Reverted movement! 
30.03 17:33:07 [Server] INFO Reverted movement! 
30.03 17:33:07 [Server] INFO Reverted movement! 
30.03 17:33:07 [Server] INFO Reverted movement! 
30.03 17:33:07 [Server] INFO Reverted movement! 
30.03 17:33:07 [Server] INFO Reverted movement! 
30.03 17:33:07 [Server] INFO Reverted movement! 
30.03 17:33:07 [Server] INFO Reverted movement! 
30.03 17:33:07 [Server] INFO Reverted movement! 
30.03 17:33:07 [Server] INFO Reverted movement! 
30.03 17:33:07 [Server] INFO Reverted movement! 
30.03 17:33:07 [Server] INFO Reverted movement! 
30.03 17:33:07 [Server] INFO Reverted movement! 
30.03 17:33:07 [Server] INFO Reverted movement! 
30.03 17:33:07 [Server] INFO Reverted movement! 
30.03 17:33:07 [Server] INFO Reverted movement! 
30.03 17:33:07 [Server] INFO Reverted movement! 
30.03 17:33:07 [Server] INFO Reverted movement! 
30.03 17:33:07 [Server] INFO Reverted movement! 
30.03 17:33:07 [Server] INFO Reverted movement! 
30.03 17:33:06 [Server] INFO Reverted movement! 
30.03 17:33:06 [Server] INFO Reverted movement! 
30.03 17:33:06 [Server] INFO Reverted movement! 
30.03 17:33:06 [Server] INFO Reverted movement! 
30.03 17:33:06 [Server] INFO Reverted movement! 
30.03 17:33:06 [Server] INFO Reverted movement! 
30.03 17:33:06 [Server] INFO Reverted movement! 
30.03 17:33:06 [Server] INFO Reverted movement! 
30.03 17:33:06 [Server] INFO Reverted movement! 
30.03 17:33:06 [Server] INFO Reverted movement! 
30.03 17:33:06 [Server] INFO Reverted movement! 
30.03 17:33:06 [Server] INFO Reverted movement! 
30.03 17:33:06 [Server] INFO Reverted movement! 
30.03 17:33:06 [Server] INFO Reverted movement! 
30.03 17:33:06 [Server] INFO Reverted movement! 
30.03 17:33:06 [Server] INFO Reverted movement! 
30.03 17:33:06 [Server] INFO Reverted movement! 
30.03 17:33:06 [Server] INFO Reverted movement! 
30.03 17:33:06 [Server] INFO Reverted movement! 
30.03 17:33:06 [Server] INFO Reverted movement! 
30.03 17:33:05 [Server] IN..

**Comment by DefinitlyEvil** [comment]
I guess sometimes sessions don't get removed. XD

**Comment by wordandahalf** [comment]
@mindcoding I just tested it on my Kindle Fire HD with the server running on my computer (i7-3770, 16GB RAM with a 20MB/sec WiFi connection) and it works like a charm

**Comment by mindcoding** [comment]
Results?

**Comment by wordandahalf** [comment]
@mindcoding  Please go to http://www.speedtest.net/ and see what your network speed is, and post back here

**Comment by mindcoding** [comment]
Ok

**Comment by TheMCPEGamer** [comment]
It works like a charm

**Comment by mindcoding** [comment]
http://www.speedtest.net/my-result/4253596251

**Comment by wordandahalf** [comment]
Hmm... your Internet seem fine.

**Comment by mindcoding** [comment]
Ok is it client or server?

**Comment by wordandahalf** [comment]
@mindcoding Most likely the client (MC:PE)

**Comment by mindcoding** [comment]
Why do the logs show the packets and I am not the only ones with these problems.

**Comment by wordandahalf** [comment]
@mindcoding The logs show the packets for debug purposes, and I have not see anyone else complain about this **yet**.

**Comment by wordandahalf** [comment]
@mindcoding And the problem is that I can't fix a big that I can't reproduce.

**Comment by mindcoding** [comment]
Fair point.

**Comment by mindcoding** [comment]
However is think it is a packet handling problem.

**Comment by wordandahalf** [comment]
@mindcoding Maybe, but I can't see to reproduce it, and I can't fix a bug I can't find.
