### ISSUE TITLE
0.11.x Support. 

### ISSUE THREAD

**Issue by DefinitlyEvil** [DragonetMC/Dragonet-Legacy#36]
This has to be done asap.

**Comment by wordandahalf** [comment]
@DefinitlyEvil Mkay, I'll try to get an APK.... somehow...

**Comment by DefinitlyEvil** [comment]
Just look into PocketMine's code and grab the packet definitions, and then put them into the translator one by one.

**Comment by ashquarky** [comment]
@TheMCPEGamer You could probably use an android emulator (I hear 
BlueStacks is pretty good) for testing.

**Comment by DefinitlyEvil** [comment]
Anybody gets the apk?

**Comment by DefinitlyEvil** [comment]
Nevermind, I got myself a MCPE 0.11.0 build 6 APK file somehow, tell me if you want that.

**Comment by L3ice** [comment]
Somehow Bluestacks does not work with 0.11 :/

**Comment by Creeperface01** [comment]
Yes MCPE doesn't work in bluestacks emulator.

**Comment by DefinitlyEvil** [comment]
I already got the 0.11.0 build 6 on my Galaxy S2, lol.

**Comment by Creeperface01** [comment]
Yes and it's a lot better for multiplayer!!!! So mobs can be added to multiplayer!

**Comment by DefinitlyEvil** [comment]
Ikr, and I just added potion effect support to dragonet and I am updating the RakNet protocol implmentation.

**Comment by Creeperface01** [comment]
Good ;) i must make GUIs but maybe it won't work on server :/

**Comment by DefinitlyEvil** [comment]
But the client doesnt send the LoginPacket after ClientHandshakePacket, that's weird, there must be something wrong.

**Comment by wordandahalf** [comment]
@DefinitlyEvil If you could send me a Dropbox link or something of the sort via email, that would be great!

**Comment by DefinitlyEvil** [comment]
Okay, what's your email?

**Comment by TheMCPEGamer** [comment]
mail2ryanjones@gmail.com
(I'm going to remove the address in an hour and a half for security reasons)

**Comment by DefinitlyEvil** [comment]
Mail sent! :)

**Comment by wordandahalf** [comment]
We should start adding entities as well, starting with PC support and then PE support

**Comment by DefinitlyEvil** [comment]
PC support is not our business, Glowstone team will do them. @gdude2002

**Comment by gdude2002** [comment]
Yeah, Dragonet has a [Glowstone](https://github.com/GlowstoneMC/Glowstone/) base, we'll eventually have entities support but it's a pretty difficult ticket, and our project lead has been extremely busy for some time now.

If one of you wants to do it, why not [submit a pull request](https://github.com/GlowstoneMC/Glowstone/pulls)?

**Comment by DefinitlyEvil** [comment]
@gdude2002 I will try. But I am suck at math so I can not do the AI part. XD

**Comment by wordandahalf** [comment]
@DefinitlyEvil I'm pretty good at math, but you never know XD

**Comment by wordandahalf** [comment]
@gdude2002 I believe that there already is a PR for entities (https://github.com/GlowstoneMC/Glowstone/pull/599)

**Comment by wordandahalf** [comment]
Actually, I could implement entities using the PR above, but we would have to downgrade the PC version from 1.8 to 1.7.10, because the client crashes in 1.8 when a mob is spawned

**Comment by DefinitlyEvil** [comment]
@TheMCPEGamer It must be a protocol problem.

**Comment by wordandahalf** [comment]
@DefinitlyEvil It's because the mob's rider & the mob that the mob is riding is not defined

**Comment by DefinitlyEvil** [comment]
@TheMCPEGamer So just go to http://wiki.vg and fix the code. Btw, you may have to send a PR instead of push commits directly. Because it is not a simple work. xD

**Comment by wordandahalf** [comment]
![Entity support!](http://i.imgur.com/sYC9QEA.png)

Finally!

**Comment by DefinitlyEvil** [comment]
Cool, you can send a PR to Glowstone and we should tell @gdude2002 . ;)

**Comment by wordandahalf** [comment]
There already is a PR, I posted about it above
