### ISSUE TITLE
Out of memory Exception in UDPSocket Thread 

### ISSUE THREAD

**Issue by willotheblessed** [DragonetMC/Dragonet-Legacy#39]
While playing with two PC clients and one PE client, we got this exception twice. Both times it resulted in making the game unplayable for the PE, not able to detect or log back onto the server. 
2015/05/21 14:56:20 [WARNING] 
Exception in thread "UDPSocket" 
2015/05/21 14:56:20 [WARNING] 
java.lang.OutOfMemoryError: Java heap space
2015/05/21 14:56:20 [WARNING]
org.dragonet.net.NonBlockUDPSocket.run
(NonBlockUDPSocket.java:50) 

We were at the time doing normal things, such as walking around, trying to craft.

**Comment by DefinitlyEvil** [comment]
You may try to increase your Java memory size by adding an option to the command line: 
-Xmx1024M
Where 1024M can be other sizes such as 512M,1G, depends on your computer RAM. And btw you should add it before -jar option.

**Comment by willotheblessed** [comment]
thank you that helped.

**Comment by DefinitlyEvil** [comment]
@willotheblessed You're welcome. Btw please tell your friends and everyone this awesome software. ;)
