### ISSUE TITLE
Glowstone Official Commit Apply Status

### ISSUE THREAD

**Issue by DefinitlyEvil** [DragonetMC/Dragonet-Legacy#4]
Next apply: 
`January 5th, 2015 until now`

**Comment by DefinitlyEvil** [comment]
@TheMCPEGamer The steps to apply new changes: 
1. `Download the latest Glowstone source code.`
2. `Backup the old Dragonet code.`
3. `Delete old glowstone source and replace with the latest source.`
4. `Open ChangedClasses.txt and add the changes one by one to the new glowstone source.`
`(Changes are started with //DRAGONET-Add or //DRAGONET-xxx)`

**Comment by wordandahalf** [comment]
Will do this weekend!

**Comment by DefinitlyEvil** [comment]
@TheMCPEGamer Remember, ALWAYS MAKE A BACKUP OF THE OLD CODE. :) Good luck!

**Comment by TheMCPEGamer** [comment]
Did this a few days ago...

**Comment by DefinitlyEvil** [comment]
@TheMCPEGamer No this issue should be always open. You have to put when you last applied the code.

**Comment by TheMCPEGamer** [comment]
@DefinitlyEvil Ok, sorry

**Comment by wordandahalf** [comment]
Latest apply: `4/22/2015`

**Comment by DefinitlyEvil** [comment]
Due to base switched, this should be closed.

**Comment by DefinitlyEvil** [comment]
Thanks to @TekkitCommando , he will keep our sourse updated with @GlowstonePlusPlus .
