### ISSUE TITLE
Switch to Spigot-based Server (Cancelled)

### ISSUE THREAD

**Issue by DefinitlyEvil** [DragonetMC/Dragonet-Legacy#40]
I decided to use spigot (improved CraftBukkit) server as our code base. And we won't let people download the pre-compiled jar due to the DCMA (you saw what CraftBukkit's repo got). But we will release a BuildTool as same as clever Spigot team did! :D 
- [ ] Cloning the CraftBukkit repo. 
- [ ] Cloning the Spigot repo. 
- [ ] Move the Dragonet's code to Spigot
- [ ] Make auto-build tool. 
- [ ] Release

PS: Cancelled.

**Comment by herenickname** [comment]
Good news for me & my plugins.

**Comment by DefinitlyEvil** [comment]
@seria2 Lol. Thanks for supporting.

**Comment by wordandahalf** [comment]
@DefinitlyEvil I don't think that using Spigot is a very good idea, the last thing we want is to get into legal issues

**Comment by RandomAltThing** [comment]
I renamed the label  *Question* to *Possible legal issues* since we probably won't be using that. We could also use *Possible legal issues* with other things.

**Comment by RandomAltThing** [comment]
@TheMCPEGamer I can get in touch with them on behalf on Dragonet.

**Comment by DefinitlyEvil** [comment]
@RandomAltThing Oh thanks, I think you can tell them about this and maybe let them help us a bit. ;)

**Comment by herenickname** [comment]
Qq again. Maybe make dragonet how plugin for Bukkit platforms?

**Comment by ashquarky** [comment]
@seria2 AFAIK Dragonet actually does support Bukkit plugins (but I'm not sure anymore - what's all this GlowKit stuff?)

**Comment by DefinitlyEvil** [comment]
Cancelled!

**Comment by RandomAltThing** [comment]
So you wanted to use spigot code?

**Comment by DefinitlyEvil** [comment]
I was, but now I'm not. ;)
