### ISSUE TITLE
[Suggestion] Resolve Bukkit dependency error (add Spigot Nexus repo to pom.xml)

### ISSUE THREAD

**Issue by ashquarky** [DragonetMC/Dragonet-Legacy#42]
Hi guys!

So I tried to build Dragonet and found that since you guys moved over to Maven (at least I think that's what's happened) there's a few dependency issues surrounding Bukkit itself. Looks like Bukkit was referenced in pom.xml but the repo it comes from wasn't added, meaning that people who don't already have the Bukkit snapshot downloaded from another project won't be able to build.

This is a pretty simple fix - all you need to do is add a few lines to pom.xml:

``` xml
    <repositories>
        <repository> <!-- All this was already here -->
            <id>sonatype</id>
            <name>Sonatype Nexus</name>
            <layout>default</layout>
            <url>https://oss.sonatype.org/content/repositories/public/</url>
        </repository>
        <repository> <!-- Here's the Bukkit repo -->
            <id>bukkit</id>
            <name>Bukkit</name>
            <layout>default</layout>
            <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
        </repository>
    </repositories>
```

I know you guys are trying to avoid Spigot, but unfortunately they're the only ones hosting Bukkit now, so there really isn't another option.

**Comment by DefinitlyEvil** [comment]
@QuarkTheAwesome We are using the `git subtree` to track the remote git repo.

**Comment by ashquarky** [comment]
So then why won't Eclipse or the Maven command-line build it? Are you 
starting a CI or something?

**Comment by DefinitlyEvil** [comment]
Double click on `setup.sh` is all you need to do. Make sure you have Maven installed and in your `PATH` already. ;)

**Comment by RandomAltThing** [comment]
Actually *SpigotMC* have nothing to do with bukkit whatsoever. https://github.com/SpigotMC/Spigot . You can see bukkit doesn't want anything to do with them as it has been caught up in the **DMCA Takedown**. You can find the bukkit code at

https://github.com/bukkit/bukkit

**Comment by L3ice** [comment]
@RandomAltThing 
Did you even read that what I linked u?
No you didnt.

**Comment by RandomAltThing** [comment]
@L3ice I am part of this organisation I read all links to make sure they're not spam.

**Comment by DefinitlyEvil** [comment]
Guys please stop arguing.

**Comment by ashquarky** [comment]
Okay, after a bit too much work, I finally got a semi-successful build. Unfortunately, it failed the self-tests and so I _still_ can't get the latest Dragonet working.

The exception message is long and annoying, so I decided to upload it (along with my surefire-reports folder) to Dropbox so you can take a look at it, but it seems to me that something about the new compilation process is causing Glowstone to build wrong. The other possible source of the error (AFAIK) is that (maybe) GlowKit doesn't include the classes listed as "missing" by the tests. Anyway, it's up to you...

[Here's the test results.](https://www.dropbox.com/s/c5d1q4fs6xfzhtv/surefire-reports.zip?dl=1)

Update: I found your CircleCI page and that one lists all of the recent builds as fails too, so it isn't just me...

**Comment by DefinitlyEvil** [comment]
Well, I can succesfully build it on my PC. Idk why.

**Comment by S0N-0F-A-S0N** [comment]
DefinitelyEvil, get your ass on Skype! (And/or give me another means to contact you.)

**Comment by RandomAltThing** [comment]
@SON-OF-A-SON Watch your language

**Comment by ashquarky** [comment]
I know we already closed this, but the issue hasn't actually been fixed. However, I think I have a fix (not involving Bukkit, sorry for not reading into Glowkit more before passing it off as useless). I'm looking into it now, if it works I'll set up a pull request.

**Comment by ashquarky** [comment]
Just before I do that, would you guys be trusting of a certain repo.turt2live.com? I'm pretty sure I've seen that repo before while dealing with Bukkit plugins, but I'm not sure.

**Comment by DefinitlyEvil** [comment]
Turt2Live.com seems to be a domain of a member in @Glowstone team.

**Comment by ashquarky** [comment]
Okay, I've got the fix done and it seems to be working just fine (even CircleCI will build it!) _but_ as soon as I added SpongeAPI back in (it got removed in my weird troubleshooting process) the whole thing broke. You guys now have a choice - merge the code now but without Sponge, or you can wait until I figure out a way of fixing Maven up. You can check out the CircleCI page [here](https://circleci.com/gh/QuarkTheAwesome/Dragonet/tree/issue42and45) and decide for yourself - build 9 has a fully working artifact, while build 11 has the Sponge error.

**Comment by DefinitlyEvil** [comment]
@QuarkTheAwesome Hmm, people may choose Sponge plugins in the future so we have to support in any way possible. xD

**Comment by ashquarky** [comment]
@DefinitlyEvil Well, looks like I finally got it working - build 12 ran through fine and I can confirm it _does_ have the Sponge classes. Trouble now is merging through the commits you made since then - I'll work on it.

**Comment by DefinitlyEvil** [comment]
@QuarkTheAwesome Nice! :D
