### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by yungtechboy1** [DragonetMC/Dragonet-Legacy#44]
Is their any way I can pay you guys to make a Java Version that is for Pocketmine Only?

**Comment by fe1a** [comment]
@yungtechboy1 lol

**Comment by RandomAltThing** [comment]
Nope :P

**Comment by fe1a** [comment]
@yungtechboy1 I don't understand the question anyway

**Comment by RandomAltThing** [comment]
Yes, this makes no sense. "**Can you guys make a Java aversion only for pocletmine?**"

**Comment by DefinitlyEvil** [comment]
@RandomAltThing :+1:

**Comment by RandomAltThing** [comment]
Lol ignore my spelling
