### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by sebmaynard** [DragonetMC/Dragonet-Legacy#45]
Hi,
Trying to build this from source so I can add 0.11.1 support; getting a load of errors about missing files/symbols:

package org.bukkit.title does not exist

Presumably because I've not added something bukkit related to my build classpath... any pointers?

Thanks!

**Comment by ashquarky** [comment]
I had a similar issue (see #42) and the general response seems to be 
"it's fine for me". Kinda sucks, tbh. I'm waiting for the next release 
version to come out - the build method genuinely does seem completely 
broken.

**Comment by sebmaynard** [comment]
Hmm. In that case, maybe someone with a successful build can give us a file
listing of their local build dir to see what we're missing? Thanks in
advance!

**Comment by sebmaynard** [comment]
Goong

**Comment by sebmaynard** [comment]
(apologies for the last accidental comment...)

**Comment by DefinitlyEvil** [comment]
I will release one but it works very bad, some packets are processing very slow.

**Comment by sebmaynard** [comment]
Great thanks; if you could help us out with build instructions, that would
be great too - then maybe we can help improve it in the future!

**Comment by DefinitlyEvil** [comment]
Thanks for paying attention to our project. And you can just easily cilck ok `setup.sh` to compile everything and make the remapped jar file.

**Comment by DefinitlyEvil** [comment]
And I just uploaded that jar to our website. ;)

**Comment by RandomAltThing** [comment]
Issue is fixed, **locked**
