### ISSUE TITLE
MCPC and MCPE

### ISSUE THREAD

**Issue by danielhyuuga** [DragonetMC/Dragonet-Legacy#47]
Say if I use dragonet, does MCPE clients will be in the same world as MCPC clients, or they will have separate worlds? since MCPE doesnt have what MCPC have

**Comment by RandomAltThing** [comment]
They will be in the same worlds. There is a ModPE script for block launcher which you need to install then you get most of the PC features and items. Dragonet is designed with code from bukkit and glow stone, with its own code for MCPE. This means that MCPC and MCPE clients can come together on Dragonet basically.
