### ISSUE TITLE
Please change the download sources of the libraries.

### ISSUE THREAD

**Issue by gaoyichuan** [DragonetMC/Dragonet-Legacy#53]
Now the download of sqllite-jdbc and mysql-connector-java all return http status code 403. So it's time to change the sources.
Two sources I found:
sqlite-jdbc 3.7.2: https://bitbucket.org/xerial/sqlite-jdbc/downloads/sqlite-jdbc-3.7.2.jar
mysql-connector-java 5.1.34:
http://mirrors.ibiblio.org/maven2/mysql/mysql-connector-java/5.1.34/mysql-connector-java-5.1.34.jar

**Comment by DefinitlyEvil** [comment]
We will have to use repo address instead of Jar link, but you could create a folder called `lib` and put those two files in, everything will be smoothly.

**Comment by gaoyichuan** [comment]
These two sources are usable. But I'm not sure whether they will work forever. So if possible, you had better run a mirror in github pages instead.

**Comment by gaoyichuan** [comment]
@DefinitlyEvil Why repo must? I think it's possible to use jar links. Putting the two files maually is ~~two~~ **too**  laggy. :)

**Comment by ethsmith** [comment]
How is it laggy? It only takes a few secs to load them or whatever :P Might be a PC Issue with lag when loading manually

**Comment by DefinitlyEvil** [comment]
@TekkitCommando It seems that @gaoyichuan is in China, China has the worst Internet in the world so we can not blame on him. xD

**Comment by mastercoms** [comment]
The problem was that this commit was not merged: https://github.com/GlowstonePlusPlus/GlowstonePlusPlus/commit/7c6b61db1e43f0433146605b6b3ca58b4986c5bd. Now that this commit is merged, it will work. Please update Dragonet.

**Comment by ethsmith** [comment]
@DefinitlyEvil xD

**Comment by gaoyichuan** [comment]
@DefinitlyEvil I'm in really in China, xD.

**Comment by DefinitlyEvil** [comment]
@gaoyichuan Cool!

**Comment by mastercoms** [comment]
I have no idea what is going on. I had this problem occur to me on the new test server, but not on my home server, my VPS, or my dedicated server. I can access the files in my web browser too. Tried using wget. Returned HTTP status code 200.

**Comment by DefinitlyEvil** [comment]
@mastercoms I got 404. :( And I tried even without HTTPS.

**Comment by mastercoms** [comment]
What URL are you going to?

**Comment by DefinitlyEvil** [comment]
@mastercoms Same in the code.

**Comment by mastercoms** [comment]
Very strange. I can download http://repo.therealms.us/repo/content/groups/public/mysql/mysql-connector-java/5.1.34/mysql-connector-java-5.1.34.jar just fine.

**Comment by vvzar** [comment]
Using browser - yes.
But dragonet in console shows errors on same link

**Comment by mastercoms** [comment]
Which is very strange. Maybe https is the problem?

**Comment by DefinitlyEvil** [comment]
Maybe some places denied packet routing to your server. xD
