### ISSUE TITLE
PocketMine Source and Bukkit Source is GNU License.

### ISSUE THREAD

**Issue by BasixKOR** [DragonetMC/Dragonet-Legacy#54]
so, your project have to change license to GNU.

**Comment by BasixKOR** [comment]
sorry for my bad english.

**Comment by ethsmith** [comment]
If the code belongs to you it Can be any license you want, bukkit is licensed properly and dragonet code can be licensed at whatever

**Comment by ashquarky** [comment]
AFAIK Dragonet's packet handling stuff is simply 'inspired' by Pocketmine and Bukkit is its own separate package.

**Comment by DefinitlyEvil** [comment]
So what's the solution? @TekkitCommando @QuarkTheAwesome

**Comment by ashquarky** [comment]
In theory you don't have to do anything. You could, however, credit PocketMine (but I'm unsure how you'd carry over the license) and add an extra license for Bukkit/Glowkit (like what you did for Glowstone). But as I said before, theoretically you don't need to do anything at all.

**Comment by BasixKOR** [comment]
I'm sorry.

**Comment by RandomAltThing** [comment]
Add multiple licenses named <code>DRAGONET LICENSE</code>
<code>POCKETMINE LICENSE</code> or something to do with this.

If you would like, @DefinitlyEvil, I can commit the licenses when I get out of France and back to jersey. Should be about 2 - 3 hours.

**Comment by DefinitlyEvil** [comment]
@RandomAltThing Yes please, and thanks. ;)

**Comment by mastercoms** [comment]
Just make a new repo for Glowkit, DragonetMC/Glowkit, move everything out of the Dragonet-core to the root folder of this repo, and then make Glowkit a submodule for this repo.

**Comment by ethsmith** [comment]
@mastercoms I fixed my PC so gonna try to get Glowstone++ into eclipse today

**Comment by DefinitlyEvil** [comment]
@mastercoms That will be a little bit complex, I think I will just add license files. xD

**Comment by RandomAltThing** [comment]
OK I will fork and commit changes now

**Comment by DefinitlyEvil** [comment]
Awesome! @RandomAltThing Thanks!

**Comment by RandomAltThing** [comment]
Quick question: what about the pocketmine license? We don't have any of their code, do we?

**Comment by RandomAltThing** [comment]
Done
