### ISSUE TITLE
Made the Hosting Account

### ISSUE THREAD

**Issue by ethsmith** [DragonetMC/Dragonet-Legacy#55]
I added an account to the hosting for Dragonet, idk your email you wanted

tell me the new email you would like and i will give you the login details :)

**Comment by RandomAltThing** [comment]
Do you have kik or twitter?

**Comment by RandomAltThing** [comment]
@TekkitCommando DM me the details on twitter: @TheDiamondYT , kik: goldowl37 , email: goldowl37@gmail.com because it looks like @DeginitlyEvil is busy right now.

**Comment by ethsmith** [comment]
Since DefinitlyEvil is the one who requested the account, I have to give it to him for Privacy Reasons. He can give you the login but I can't

**Comment by RandomAltThing** [comment]
@TekkitCommando Alright. @DefinitlyEvil Get your ****king arse here and get the details :3

**Comment by DefinitlyEvil** [comment]
@TekkitCommando You may tell me through skype. And email is theevildays@gmail.com  . Tell me when you're done, I am gonna remove the email from this comment.

**Comment by ethsmith** [comment]
you can delete it :)

**Comment by ethsmith** [comment]
I will send it over skype

**Comment by DefinitlyEvil** [comment]
Okay.

**Comment by ethsmith** [comment]
This Can Be Closed
