### ISSUE TITLE
Player will get hurt when staying in a opening door.

### ISSUE THREAD

**Issue by keuin** [DragonetMC/Dragonet-Legacy#56]
When I staying in a opening oakwood door, I will get hurt. Like stay in a stone.

**Comment by mastercoms** [comment]
This has already been fixed in Glowstone++: https://github.com/GlowstonePlusPlus/GlowstonePlusPlus/commit/077f36e6dd616c4c720e44a4c91c0dcc4736538b

**Comment by mastercoms** [comment]
Why close this issue? It has not been resolved in Dragonet.

**Comment by DefinitlyEvil** [comment]
@TekkitCommando Please help to merge. xD

**Comment by mastercoms** [comment]
We can't really help you merge until you separate the Glowkit and Dragonet repos.

Only way we can work around it is some weird git thing that involves rewriting history and doing really complicated regex stuff. I don't want to do that, since separating the repos would be easier.

**Comment by DefinitlyEvil** [comment]
@mastercoms Okay. :( Since I am pretty busy these days I will merge later. xD
