### ISSUE TITLE
MCPE Networking Talk 

### ISSUE THREAD

**Issue by alejzeis** [DragonetMC/Dragonet-Legacy#60]
This issue has been left open so developers can talk about the networking. For the original issue, please see below.

---

_I'm a new member to the team, and this project seems really cool. It could use some additions though. I noticed that there were packet issues, and I'm not sure if this has been tested with a bad network (packet loss). I propose we migrate the RakNet handling code over to my library (JRakLib). It's released under the GPL v3 (never mind, I have to change it to LGPL) as it is a port of PocketMine's RakLib. There should not be any legal issues as long as you give credit to PM and me._

**Comment by jython234** [comment]
The integration should fix #48

**Comment by RandomAltThing** [comment]
Lol you are in the org

@DefinitlyEvil Can I be in the owners team so I can add more repositories or remove them?

**Comment by TekkitCommando** [comment]
No, You don't need to be an owner, just make a group like lead developers and give them write access

**Comment by jython234** [comment]
Why a new repository?

On Wednesday, August 5, 2015, TekkitCommando <notifications@github.com>
wrote:

> No, You don't need to be an owner, just make a group like lead developers
> and give them write access
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DragonetMC/Dragonet/issues/60#issuecomment-128044746>.
>


--

**Comment by TekkitCommando** [comment]
@jython234 idk @RandomAltThing likes to experiment

**Comment by RandomAltThing** [comment]
I deserve owner -_- I've Been here quite long

**Comment by RandomAltThing** [comment]
@jython134 I don't have much time right now, could you please build dragonet (current commit) and send me the jar please.

**Comment by RandomAltThing** [comment]
@jython234 ^^

**Comment by jython234** [comment]
I'm on mobile :/ I didn't even push yet, I wanted to get approval from the
team first.

On Wednesday, August 5, 2015, RandomAltThing <notifications@github.com>
wrote:

> @jython234 <https://github.com/jython234> ^^
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DragonetMC/Dragonet/issues/60#issuecomment-128046860>.
>


--

**Comment by RandomAltThing** [comment]
@jython235 :+1: I'm on mobile too. I can build using AIDE (it don't create a jar) but then I can just zip the class files and change it to .jar. It actually freaking works.

**Comment by TekkitCommando** [comment]
@RandomAltThing Ehh Just saying there were other ways :P I hope you get owner like you want :)

**Comment by RandomAltThing** [comment]
@jython234 ^^ I can never type your name

**Comment by RandomAltThing** [comment]
@jython234 @DefinitlyEvil Damn AIDE doesn't recognize it as a java project because it is missing <code>.project</code> and <code>.classpath</code>

**Comment by mastercoms** [comment]
Why a new repo to test things? Why not a branch?

**Comment by jython234** [comment]
@mastercoms I am really confused. This was supposed to be about JRakLib.

**Comment by TekkitCommando** [comment]
I agree with @mastercoms

**Comment by mastercoms** [comment]
jython234 commented:
> Why a new repository?

And I was saying we should make a new branch instead of a repository that adds JRakLib integration.

**Comment by mastercoms** [comment]
Ok, now back to the actual discussion we haven't been having for the past 16 comments.

I think JRakLib would be a great addition, since it is written in Java, and we could possibly integrate it better in Dragonet.

**Comment by jython234** [comment]
@mastercoms I forgot one detail, JRakLib only works with java 8.

**Comment by DefinitlyEvil** [comment]
@jython234 That's okay because Dragonet only supports java 8. ;)

**Comment by jython234** [comment]
Alright nice :)

On Wednesday, August 5, 2015, The Evil Man <notifications@github.com> wrote:

> @jython234 <https://github.com/jython234> That's okay because Dragonet
> only supports java 8. ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DragonetMC/Dragonet/issues/60#issuecomment-128198928>.
>


--

**Comment by TekkitCommando** [comment]
Yes, luckily we had all our machines upgraded to java 8 a few months before we started hosting Dragonet and Glowstone++ or that would have caused a little annoyance xD

**Comment by jython234** [comment]
Heh xD.

On Wednesday, August 5, 2015, TekkitCommando <notifications@github.com>
wrote:

> Yes, luckily we had all our machines upgraded to java 8 a few months
> before we started hosting Dragonet and Glowstone++ or that would have
> caused a little annoyance xD
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DragonetMC/Dragonet/issues/60#issuecomment-128211293>.
>


--

**Comment by DefinitlyEvil** [comment]
I am start working around with MCPE 0.12 now. ;)

**Comment by jython234** [comment]
@DefinitlyEvil, @mastercoms https://github.com/DragonetMC/Dragonet/commit/d4ca56f9b892f1767e31abf839caaeeb1c7a0060 I need help with migrating packet handling and session issues to use the JRakLibInterface.

**Comment by DefinitlyEvil** [comment]
@jython234 Don't worry about that, I will do it once I finish updating to MCPE 0.12.

**Comment by DefinitlyEvil** [comment]
@jython234 I think I solved the integration issue. We can merge them when no errors appears. ;)

**Comment by DNx5** [comment]
JRakLib build in Java 8.
So, it can't run on Java 7 servers

**Comment by DefinitlyEvil** [comment]
@DNx5 Dragonet is also in Java 8, so don't worry, if you can't run Dragonet before, you will still unable to run. xD

**Comment by DNx5** [comment]
but my server use Java 7. It can't run because JRakLib compiled with Java 8 :cry:

**Comment by DefinitlyEvil** [comment]
@DNx5 Then upgrade to Java 8. ;)

**Comment by jython234** [comment]
Advertising on local network is not implemented correctly, in JRakLibInterface handleRaw is not called for 0x01 or 0x02. Use handler.sendOption("name", [raw MCPE string]);

**Comment by DefinitlyEvil** [comment]
@jython234 When do I send?

**Comment by jython234** [comment]
In the constructor, you only need to do it once (maybe more to update
player count)

On Monday, August 24, 2015, The Evil Man <notifications@github.com> wrote:

> @jython234 <https://github.com/jython234> When do I send?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DragonetMC/Dragonet/issues/60#issuecomment-134259231>.
>


--

**Comment by DefinitlyEvil** [comment]
Okay. Now I know why players can't find the server. XD

**Comment by jython234** [comment]
xD.

On Tuesday, August 25, 2015, The Evil Man <notifications@github.com> wrote:

> Okay. Now I know why players can't find the server. XD
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DragonetMC/Dragonet/issues/60#issuecomment-134773354>.
>


--

**Comment by DefinitlyEvil** [comment]
@jython234 Hi. Do you have any new progress?

**Comment by jython234** [comment]
@DefinitlyEvil I'm sorry, but school just started and I already have a lot
of assignments. I'll try to see if I can do something when I get home.

On Thursday, September 3, 2015, The Evil Man <notifications@github.com>
wrote:

> @jython234 <https://github.com/jython234> Hi. Do you have any new
> progress?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DragonetMC/Dragonet/issues/60#issuecomment-137408815>.
>


--

**Comment by DefinitlyEvil** [comment]
@jython234 Okay. xD Study is important buddy.

**Comment by DefinitlyEvil** [comment]
@jython234 I just updated protocol to 34, that should be working with latest build of MCPE.

**Comment by DefinitlyEvil** [comment]
Which is available here: https://circle-artifacts.com/gh/DragonetMC/Dragonet/128/artifacts/0/tmp/circle-artifacts.Yg6XZXj/dragonet-0.0.3-preR1.jar

**Comment by DefinitlyEvil** [comment]
I fixed that problem which was LoginPacket definition's problem, but now it always say client timeout and then disconnected. xD

**Comment by RandomAltThing** [comment]
I have school too

**Comment by TheDiamondYT1** [comment]
This issue will be left open for collaborators to talk about networking.

**Comment by TheDiamondYT1** [comment]
To confirm: server now shows up in world list.

**Comment by DefinitlyEvil** [comment]
But I am not sure why i can't join. :(

**Comment by RandomAltThingy** [comment]
Yeah your login packets and stuff probably arent correct for 0.12

**Comment by DefinitlyEvil** [comment]
I will check later.

**Comment by RandomAltThingy** [comment]
Look at PocketMine's packet changes

**Comment by DefinitlyEvil** [comment]
when

**Comment by RandomAltThingy** [comment]
@DefinitlyEvil  https://github.com/PocketMine/PocketMine-MP/commits/mcpe-0.12?page=2

**Comment by RandomAltThingy** [comment]
@DefinitlyEvil  Look at commits that have packet in the name or more changes.

**Comment by DefinitlyEvil** [comment]
I did update them.

**Comment by RandomAltThingy** [comment]
Well i have no clue

**Comment by RandomAltThingy** [comment]
NETBEANS IS WORKING WOOOO

**Comment by DefinitlyEvil** [comment]
okay xD I will update test server now.

**Comment by RandomAltThingy** [comment]
Can we do that idea i had about the remote repo?

**Comment by RandomAltThingy** [comment]
Idek how to use maven so @jython234 can do that.

**Comment by DefinitlyEvil** [comment]
Let's ask him. xD

**Comment by DefinitlyEvil** [comment]
@jython234 I fixed the spawning problem which I forgot a `return;` and it caches huge packets in JRakLib' recovery queue. But now the problem is server receives client's packets very late(more than 20 seconds).

**Comment by RandomAltThingy** [comment]
@DefinitlyEvil Haha

**Comment by RandomAltThingy** [comment]
@DefinitlyEvil Im porting Linux commands to Windows in batch files but adding the directory the PATH so you can access the commands anywhere in cmd.

**Comment by DefinitlyEvil** [comment]
@RandomAltThingy Okay. there's already something like that in git-scm for windows.

**Comment by RandomAltThingy** [comment]
@DefinitlyEvil Come on, who likes git bash (The bash.exe included). I use git bash but only for git. And it don't have apt-get. #SpoilerAlert

**Comment by DefinitlyEvil** [comment]
@RandomAltThingy You can use them outside bash.exe, you can use normal cmd. ;)

**Comment by mastercoms** [comment]
There something called cygwin.

**Comment by DefinitlyEvil** [comment]
@mastercoms @RandomAltThingy Please focus on the topic.

**Comment by alejzeis** [comment]
@DefinitlyEvil packets should be in the recovery queue to be resent when
needed. They are removed when an ACK for that packet is received.

On Sunday, October 11, 2015, The Evil Man notifications@github.com wrote:

> @mastercoms https://github.com/mastercoms @RandomAltThingy
> https://github.com/RandomAltThingy Please focus on the topic.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DragonetMC/Dragonet/issues/60#issuecomment-147205472.

##

**Comment by DefinitlyEvil** [comment]
@jython234 I know, I used to put the non-compressed ones in it and it caused heap memory full.

**Comment by alejzeis** [comment]
@DefinitlyEvil I used to send chunk packets uncompressed, never had a heap
full.

On Sunday, October 11, 2015, The Evil Man notifications@github.com wrote:

> @jython234 https://github.com/jython234 I know, I used to put the
> non-compressed ones in it and it caused heap memory full.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DragonetMC/Dragonet/issues/60#issuecomment-147213069.

##

**Comment by DefinitlyEvil** [comment]
@jython234 Now let's talk about packet lag problem. Packets are delayed to receive on server and idk why.

**Comment by alejzeis** [comment]
@DefinitlyEvil The problem is not JRakLib's fault, it's most likely not enough packets being handled on your side (handler.handlePacket())

**Comment by DefinitlyEvil** [comment]
I did handle all packets in every tick.

**Comment by DefinitlyEvil** [comment]
I used while(handle.handlePacket()){}

**Comment by DefinitlyEvil** [comment]
@jython234 Help!

**Comment by TheDiamondYT1** [comment]
@DefinitlyEvil Please give me access to the website repo

**Comment by DefinitlyEvil** [comment]
@RandomAltThingy What's about for?

**Comment by DefinitlyEvil** [comment]
It seems that the networking issue is fixed. :) Closing this issue.
