### ISSUE TITLE
I build it failure, how can i do it?

### ISSUE THREAD

**Issue by ghost** [DragonetMC/Dragonet-Legacy#63]
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.099 s
[INFO] Finished at: 2015-08-11T01:49:10+08:00
[INFO] Final Memory: 5M/123M
[INFO] ------------------------------------------------------------------------
[ERROR] No goals have been specified for this build. You must specify a valid li
fecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id

> :<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are
> : validate, initialize, generate-sources, process-sources, generate-resources, p
> rocess-resources, compile, process-classes, generate-test-sources, process-test-
> sources, generate-test-resources, process-test-resources, test-compile, process-
> test-classes, test, prepare-package, package, pre-integration-test, integration-
> test, post-integration-test, verify, install, deploy, pre-clean, clean, post-cle
> an, pre-site, site, post-site, site-deploy. -> [Help 1]
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
> ch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please rea
> d the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoGoalSpecifie
> dException
> C:\Users\Rainbow\Desktop\Dragonet-0.0.2-alpha>mvn package
> [INFO] Scanning for projects...
> Downloading: https://oss.sonatype.org/content/repositories/public/org/sonatype/o
> ss/oss-parent/9/oss-parent-9.pom
> Downloaded: https://oss.sonatype.org/content/repositories/public/org/sonatype/os
> s/oss-parent/9/oss-parent-9.pom (0 B at 0.0 KB/sec)
> [INFO]
> [INFO] ------------------------------------------------------------------------
> [INFO] Building Dragonet 0.0.2-preR6
> [INFO] ------------------------------------------------------------------------
> Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven
> -compiler-plugin/maven-metadata.xml
> Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-
> compiler-plugin/maven-metadata.xml (798 B at 0.7 KB/sec)
> Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven
> -enforcer-plugin/1.2/maven-enforcer-plugin-1.2.pom
> Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-
> enforcer-plugin/1.2/maven-enforcer-plugin-1.2.pom (6 KB at 15.4 KB/sec)
> Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/enforcer/enfo
> rcer/1.2/enforcer-1.2.pom
> Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/enforcer/enfor
> cer/1.2/enforcer-1.2.pom (11 KB at 29.4 KB/sec)
> Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven
> -enforcer-plugin/1.2/maven-enforcer-plugin-1.2.jar
> Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-
> enforcer-plugin/1.2/maven-enforcer-plugin-1.2.jar (25 KB at 42.9 KB/sec)
> Downloading: https://oss.sonatype.org/content/repositories/public/org/ow2/asm/as
> m-debug-all/5.0.3/asm-debug-all-5.0.3.pom
> Downloading: https://repo.maven.apache.org/maven2/org/ow2/asm/asm-debug-all/5.0.
> 3/asm-debug-all-5.0.3.pom
> Downloaded: https://repo.maven.apache.org/maven2/org/ow2/asm/asm-debug-all/5.0.3
> /asm-debug-all-5.0.3.pom (2 KB at 5.2 KB/sec)
> Downloading: https://oss.sonatype.org/content/repositories/public/org/ow2/asm/as
> m-parent/5.0.3/asm-parent-5.0.3.pom
> Downloading: https://repo.maven.apache.org/maven2/org/ow2/asm/asm-parent/5.0.3/a
> sm-parent-5.0.3.pom
> Downloaded: https://repo.maven.apache.org/maven2/org/ow2/asm/asm-parent/5.0.3/as
> m-parent-5.0.3.pom (6 KB at 12.9 KB/sec)
> Downloading: https://oss.sonatype.org/content/repositories/public/org/bukkit/buk
> kit/1.8.7-R0.1-SNAPSHOT/maven-metadata.xml
> Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/bukkit/
> bukkit/1.8.7-R0.1-SNAPSHOT/maven-metadata.xml
> Downloading: https://oss.sonatype.org/content/repositories/public/org/bukkit/buk
> kit/1.8.7-R0.1-SNAPSHOT/bukkit-1.8.7-R0.1-SNAPSHOT.pom
> Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/bukkit/
> bukkit/1.8.7-R0.1-SNAPSHOT/bukkit-1.8.7-R0.1-SNAPSHOT.pom
> [WARNING] The POM for org.bukkit:bukkit:jar:1.8.7-R0.1-SNAPSHOT is missing, no d
> ependency information available
> Downloading: https://oss.sonatype.org/content/repositories/snapshots/com/flowpow
> ered/flow-networking/1.0.0-SNAPSHOT/maven-metadata.xml
> Downloading: https://oss.sonatype.org/content/repositories/public/com/flowpowere
> d/flow-networking/1.0.0-SNAPSHOT/maven-metadata.xml
> Downloaded: https://oss.sonatype.org/content/repositories/public/com/flowpowered
> /flow-networking/1.0.0-SNAPSHOT/maven-metadata.xml (2 KB at 1.2 KB/sec)
> Downloaded: https://oss.sonatype.org/content/repositories/snapshots/com/flowpowe
> red/flow-networking/1.0.0-SNAPSHOT/maven-metadata.xml (2 KB at 1.1 KB/sec)
> Downloading: https://oss.sonatype.org/content/repositories/public/com/flowpowere
> d/flow-networking/1.0.0-SNAPSHOT/flow-networking-1.0.0-20140904.022354-7.pom
> Downloaded: https://oss.sonatype.org/content/repositories/public/com/flowpowered
> /flow-networking/1.0.0-SNAPSHOT/flow-networking-1.0.0-20140904.022354-7.pom (10
> KB at 18.1 KB/sec)
> Downloading: https://oss.sonatype.org/content/repositories/public/io/netty/netty
> -all/4.0.21.Final/netty-all-4.0.21.Final.pom
> Downloaded: https://oss.sonatype.org/content/repositories/public/io/netty/netty-
> all/4.0.21.Final/netty-all-4.0.21.Final.pom (17 KB at 20.8 KB/sec)
> Downloading: https://oss.sonatype.org/content/repositories/public/io/netty/netty
> -parent/4.0.21.Final/netty-parent-4.0.21.Final.pom
> Downloaded: https://oss.sonatype.org/content/repositories/public/io/netty/netty-
> parent/4.0.21.Final/netty-parent-4.0.21.Final.pom (41 KB at 42.5 KB/sec)
> Downloading: https://oss.sonatype.org/content/repositories/public/org/slf4j/slf4
> j-api/1.7.7/slf4j-api-1.7.7.pom
> Downloaded: https://oss.sonatype.org/content/repositories/public/org/slf4j/slf4j
> -api/1.7.7/slf4j-api-1.7.7.pom (3 KB at 4.5 KB/sec)
> Downloading: https://oss.sonatype.org/content/repositories/public/org/slf4j/slf4
> j-parent/1.7.7/slf4j-parent-1.7.7.pom
> Downloaded: https://oss.sonatype.org/content/repositories/public/org/slf4j/slf4j
> -parent/1.7.7/slf4j-parent-1.7.7.pom (12 KB at 21.6 KB/sec)
> Downloading: https://oss.sonatype.org/content/repositories/public/jline/jline/2.
> 11/jline-2.11.pom
> Downloaded: https://oss.sonatype.org/content/repositories/public/jline/jline/2.1
> 1/jline-2.11.pom (17 KB at 28.8 KB/sec)
> Downloading: https://oss.sonatype.org/content/repositories/public/org/projectlom
> bok/lombok/1.14.8/lombok-1.14.8.pom
> Downloaded: https://oss.sonatype.org/content/repositories/public/org/projectlomb
> ok/lombok/1.14.8/lombok-1.14.8.pom (2 KB at 2.7 KB/sec)
> Downloading: https://oss.sonatype.org/content/repositories/public/org/slf4j/slf4
> j-jdk14/1.7.7/slf4j-jdk14-1.7.7.pom
> Downloaded: https://oss.sonatype.org/content/repositories/public/org/slf4j/slf4j
> -jdk14/1.7.7/slf4j-jdk14-1.7.7.pom (2 KB at 2.4 KB/sec)
> Downloading: https://oss.sonatype.org/content/repositories/public/junit/junit/4.
> 11/junit-4.11.pom
> Downloaded: https://oss.sonatype.org/content/repositories/public/junit/junit/4.1
> 1/junit-4.11.pom (3 KB at 4.1 KB/sec)
> Downloading: https://oss.sonatype.org/content/repositories/public/org/hamcrest/h
> amcrest-core/1.3/hamcrest-core-1.3.pom
> Downloaded: https://oss.sonatype.org/content/repositories/public/org/hamcrest/ha
> mcrest-core/1.3/hamcrest-core-1.3.pom (766 B at 1.2 KB/sec)
> Downloading: https://oss.sonatype.org/content/repositories/public/org/hamcrest/h
> amcrest-parent/1.3/hamcrest-parent-1.3.pom
> Downloaded: https://oss.sonatype.org/content/repositories/public/org/hamcrest/ha
> mcrest-parent/1.3/hamcrest-parent-1.3.pom (2 KB at 3.5 KB/sec)
> Downloading: https://oss.sonatype.org/content/repositories/public/org/ow2/asm/as
> m-debug-all/5.0.3/asm-debug-all-5.0.3.jar
> Downloading: https://oss.sonatype.org/content/repositories/public/org/bukkit/buk
> kit/1.8.7-R0.1-SNAPSHOT/bukkit-1.8.7-R0.1-SNAPSHOT.jar
> Downloading: https://oss.sonatype.org/content/repositories/public/com/flowpowere
> d/flow-networking/1.0.0-SNAPSHOT/flow-networking-1.0.0-20140904.022354-7.jar
> Downloading: https://oss.sonatype.org/content/repositories/public/io/netty/netty
> -all/4.0.21.Final/netty-all-4.0.21.Final.jar
> Downloading: https://oss.sonatype.org/content/repositories/public/org/slf4j/slf4
> j-api/1.7.7/slf4j-api-1.7.7.jar
> Downloading: https://oss.sonatype.org/content/repositories/public/jline/jline/2.
> 11/jline-2.11.jar
> Downloading: https://oss.sonatype.org/content/repositories/public/org/projectlom
> bok/lombok/1.14.8/lombok-1.14.8.jar
> Downloaded: https://oss.sonatype.org/content/repositories/public/com/flowpowered
> /flow-networking/1.0.0-SNAPSHOT/flow-networking-1.0.0-20140904.022354-7.jar (45
> KB at 42.8 KB/sec)
> Downloading: https://oss.sonatype.org/content/repositories/public/org/slf4j/slf4
> j-jdk14/1.7.7/slf4j-jdk14-1.7.7.jar
> Downloaded: https://oss.sonatype.org/content/repositories/public/org/slf4j/slf4j
> -api/1.7.7/slf4j-api-1.7.7.jar (29 KB at 21.9 KB/sec)
> Downloading: https://oss.sonatype.org/content/repositories/public/junit/junit/4.
> 11/junit-4.11.jar
> Downloaded: https://oss.sonatype.org/content/repositories/public/org/slf4j/slf4j
> -jdk14/1.7.7/slf4j-jdk14-1.7.7.jar (8 KB at 5.0 KB/sec)
> Downloading: https://oss.sonatype.org/content/repositories/public/org/hamcrest/h
> amcrest-core/1.3/hamcrest-core-1.3.jar
> Downloaded: https://oss.sonatype.org/content/repositories/public/jline/jline/2.1
> 1/jline-2.11.jar (204 KB at 87.8 KB/sec)
> Downloaded: https://oss.sonatype.org/content/repositories/public/org/hamcrest/ha
> mcrest-core/1.3/hamcrest-core-1.3.jar (44 KB at 18.8 KB/sec)
> Downloaded: https://oss.sonatype.org/content/repositories/public/junit/junit/4.1
> 1/junit-4.11.jar (240 KB at 82.6 KB/sec)
> Downloaded: https://oss.sonatype.org/content/repositories/public/io/netty/netty-
> all/4.0.21.Final/netty-all-4.0.21.Final.jar (1691 KB at 318.3 KB/sec)
> Downloaded: https://oss.sonatype.org/content/repositories/public/org/projectlomb
> ok/lombok/1.14.8/lombok-1.14.8.jar (1159 KB at 178.1 KB/sec)
> Downloading: https://repo.maven.apache.org/maven2/org/ow2/asm/asm-debug-all/5.0.
> 3/asm-debug-all-5.0.3.jar
> Downloaded: https://repo.maven.apache.org/maven2/org/ow2/asm/asm-debug-all/5.0.3
> /asm-debug-all-5.0.3.jar (370 KB at 276.2 KB/sec)
> Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/bukkit/
> bukkit/1.8.7-R0.1-SNAPSHOT/bukkit-1.8.7-R0.1-SNAPSHOT.jar
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 29.018 s
> [INFO] Finished at: 2015-08-11T01:49:52+08:00
> [INFO] Final Memory: 8M/123M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal on project Dragonet: Could not resolve dependenci
> es for project org.dragonet:Dragonet:pom:0.0.2-preR6: Could not find artifact or
> g.bukkit:bukkit:jar:1.8.7-R0.1-SNAPSHOT in sonatype (https://oss.sonatype.org/co
> ntent/repositories/public/) -> [Help 1]
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
> ch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please rea
> d the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyReso
> lutionException
> D:\Development\Dragonet-0.0.2-alpha>

**Comment by mastercoms** [comment]
You didn't specify it to package, nor did you compile Glowkit.

From the Dragonet folder:

``` bash
cd Glowkit
mvn install
cd ..
cd Dragonet-core
mvn package
```
