### ISSUE TITLE
BUILD FAILURE

### ISSUE THREAD

**Issue by ghost** [DragonetMC/Dragonet-Legacy#64]
Downloading: https://repo.maven.apache.org/maven2/junit/junit/4.10/junit-4.10.po
m
Downloaded: https://repo.maven.apache.org/maven2/junit/junit/4.10/junit-4.10.pom
 (0 B at 0.0 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/hamcres
t/hamcrest-core/1.1/hamcrest-core-1.1.pom
Downloading: https://repo.maven.apache.org/maven2/org/hamcrest/hamcrest-core/1.1
/hamcrest-core-1.1.pom
Downloaded: https://repo.maven.apache.org/maven2/org/hamcrest/hamcrest-core/1.1/
hamcrest-core-1.1.pom (0 B at 0.0 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/hamcres
t/hamcrest-parent/1.1/hamcrest-parent-1.1.pom
Downloading: https://repo.maven.apache.org/maven2/org/hamcrest/hamcrest-parent/1
.1/hamcrest-parent-1.1.pom
Downloaded: https://repo.maven.apache.org/maven2/org/hamcrest/hamcrest-parent/1.
1/hamcrest-parent-1.1.pom (0 B at 0.0 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/com/google/
guava/guava/17.0/guava-17.0.pom
Downloading: https://repo.maven.apache.org/maven2/com/google/guava/guava/17.0/gu
ava-17.0.pom
Downloaded: https://repo.maven.apache.org/maven2/com/google/guava/guava/17.0/gua
va-17.0.pom (0 B at 0.0 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/com/google/
guava/guava-parent/17.0/guava-parent-17.0.pom
Downloading: https://repo.maven.apache.org/maven2/com/google/guava/guava-parent/
17.0/guava-parent-17.0.pom
Downloaded: https://repo.maven.apache.org/maven2/com/google/guava/guava-parent/1
7.0/guava-parent-17.0.pom (0 B at 0.0 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/com/google/
code/gson/gson/2.2.4/gson-2.2.4.pom
Downloading: https://repo.maven.apache.org/maven2/com/google/code/gson/gson/2.2.
4/gson-2.2.4.pom
Downloaded: https://repo.maven.apache.org/maven2/com/google/code/gson/gson/2.2.4
/gson-2.2.4.pom (0 B at 0.0 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/avaje/e
bean/2.8.1/ebean-2.8.1.pom
Downloading: https://repo.maven.apache.org/maven2/org/avaje/ebean/2.8.1/ebean-2.
8.1.pom
Downloaded: https://repo.maven.apache.org/maven2/org/avaje/ebean/2.8.1/ebean-2.8
.1.pom (0 B at 0.0 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/sonatyp
e/oss/oss-parent/5/oss-parent-5.pom
Downloading: https://repo.maven.apache.org/maven2/org/sonatype/oss/oss-parent/5/
oss-parent-5.pom
Downloaded: https://repo.maven.apache.org/maven2/org/sonatype/oss/oss-parent/5/o
ss-parent-5.pom (0 B at 0.0 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/javax/persi
stence/persistence-api/1.0/persistence-api-1.0.pom
Downloading: https://repo.maven.apache.org/maven2/javax/persistence/persistence-
api/1.0/persistence-api-1.0.pom
Downloaded: https://repo.maven.apache.org/maven2/javax/persistence/persistence-a
pi/1.0/persistence-api-1.0.pom (0 B at 0.0 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/yaml/sn
akeyaml/1.15/snakeyaml-1.15.pom
Downloading: https://repo.maven.apache.org/maven2/org/yaml/snakeyaml/1.15/snakey
aml-1.15.pom
Downloaded: https://repo.maven.apache.org/maven2/org/yaml/snakeyaml/1.15/snakeya
ml-1.15.pom (0 B at 0.0 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/junit/junit
/4.12/junit-4.12.pom
Downloading: https://repo.maven.apache.org/maven2/junit/junit/4.12/junit-4.12.po
m
Downloaded: https://repo.maven.apache.org/maven2/junit/junit/4.12/junit-4.12.pom
 (24 KB at 47.3 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/hamcres
t/hamcrest-core/1.3/hamcrest-core-1.3.pom
Downloading: https://repo.maven.apache.org/maven2/org/hamcrest/hamcrest-core/1.3
/hamcrest-core-1.3.pom
Downloaded: https://repo.maven.apache.org/maven2/org/hamcrest/hamcrest-core/1.3/
hamcrest-core-1.3.pom (0 B at 0.0 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/hamcres
t/hamcrest-parent/1.3/hamcrest-parent-1.3.pom
Downloading: https://repo.maven.apache.org/maven2/org/hamcrest/hamcrest-parent/1
.3/hamcrest-parent-1.3.pom
Downloaded: https://repo.maven.apache.org/maven2/org/hamcrest/hamcrest-parent/1.
3/hamcrest-parent-1.3.pom (0 B at 0.0 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/hamcres
t/hamcrest-library/1.3/hamcrest-library-1.3.pom
Downloading: https://repo.maven.apache.org/maven2/org/hamcrest/hamcrest-library/
1.3/hamcrest-library-1.3.pom
Downloaded: https://repo.maven.apache.org/maven2/org/hamcrest/hamcrest-library/1
.3/hamcrest-library-1.3.pom (820 B at 2.1 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/net/md-5/bu
ngeecord-config/1.8-SNAPSHOT/bungeecord-config-1.8-20150716.221140-83.jar
Downloading: https://oss.sonatype.org/content/repositories/snapshots/net/md-5/bu
ngeecord-protocol/1.8-SNAPSHOT/bungeecord-protocol-1.8-20150716.221203-83.jar
Downloading: https://oss.sonatype.org/content/repositories/snapshots/net/md-5/bu
ngeecord-event/1.8-SNAPSHOT/bungeecord-event-1.8-20150716.221151-83.jar
Downloading: https://oss.sonatype.org/content/repositories/snapshots/net/md-5/bu
ngeecord-api/1.8-SNAPSHOT/bungeecord-api-1.8-20150716.221217-83.jar
Downloading: https://oss.sonatype.org/content/repositories/snapshots/io/netty/ne
tty-codec/4.0.24.Final/netty-codec-4.0.24.Final.jar
Downloading: https://oss.sonatype.org/content/repositories/snapshots/io/netty/ne
tty-transport/4.0.24.Final/netty-transport-4.0.24.Final.jar
Downloaded: https://oss.sonatype.org/content/repositories/snapshots/net/md-5/bun
geecord-event/1.8-SNAPSHOT/bungeecord-event-1.8-20150716.221151-83.jar (8 KB at
6.8 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/io/netty/ne
tty-buffer/4.0.24.Final/netty-buffer-4.0.24.Final.jar
Downloaded: https://oss.sonatype.org/content/repositories/snapshots/net/md-5/bun
geecord-config/1.8-SNAPSHOT/bungeecord-config-1.8-20150716.221140-83.jar (10 KB
at 7.3 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/io/netty/ne
tty-common/4.0.24.Final/netty-common-4.0.24.Final.jar
Downloading: https://oss.sonatype.org/content/repositories/snapshots/net/sf/trov
e4j/trove4j/3.0.3/trove4j-3.0.3.jar
Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/apache/
commons/commons-lang3/3.4/commons-lang3-3.4.jar
Downloading: https://oss.sonatype.org/content/repositories/snapshots/net/md-5/bu
ngeecord-chat/1.8-SNAPSHOT/bungeecord-chat-1.8-20150716.221126-85.jar
Downloaded: https://oss.sonatype.org/content/repositories/snapshots/net/md-5/bun
geecord-protocol/1.8-SNAPSHOT/bungeecord-protocol-1.8-20150716.221203-83.jar (76
 KB at 39.7 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/junit/junit
/4.12/junit-4.12.jar
Downloaded: https://oss.sonatype.org/content/repositories/snapshots/net/md-5/bun
geecord-api/1.8-SNAPSHOT/bungeecord-api-1.8-20150716.221217-83.jar (85 KB at 42.
7 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/hamcres
t/hamcrest-core/1.3/hamcrest-core-1.3.jar
Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/hamcres
t/hamcrest-library/1.3/hamcrest-library-1.3.jar
Downloaded: https://oss.sonatype.org/content/repositories/snapshots/net/md-5/bun
geecord-chat/1.8-SNAPSHOT/bungeecord-chat-1.8-20150716.221126-85.jar (55 KB at 1
6.8 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/io/netty/netty-codec/4.0.24.Fi
nal/netty-codec-4.0.24.Final.jar
Downloading: https://repo.maven.apache.org/maven2/io/netty/netty-transport/4.0.2
4.Final/netty-transport-4.0.24.Final.jar
Downloading: https://repo.maven.apache.org/maven2/net/sf/trove4j/trove4j/3.0.3/t
rove4j-3.0.3.jar
Downloading: https://repo.maven.apache.org/maven2/io/netty/netty-common/4.0.24.F
inal/netty-common-4.0.24.Final.jar
Downloading: https://repo.maven.apache.org/maven2/io/netty/netty-buffer/4.0.24.F
inal/netty-buffer-4.0.24.Final.jar
Downloaded: https://repo.maven.apache.org/maven2/io/netty/netty-transport/4.0.24
.Final/netty-transport-4.0.24.Final.jar (304 KB at 207.1 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/commons/commons-lan
g3/3.4/commons-lang3-3.4.jar
Downloaded: https://repo.maven.apache.org/maven2/io/netty/netty-codec/4.0.24.Fin
al/netty-codec-4.0.24.Final.jar (138 KB at 82.0 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/junit/junit/4.12/junit-4.12.ja
r
Downloaded: https://repo.maven.apache.org/maven2/io/netty/netty-buffer/4.0.24.Fi
nal/netty-buffer-4.0.24.Final.jar (163 KB at 93.1 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/hamcrest/hamcrest-core/1.3
/hamcrest-core-1.3.jar
Downloaded: https://repo.maven.apache.org/maven2/org/hamcrest/hamcrest-core/1.3/
hamcrest-core-1.3.jar (0 B at 0.0 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/hamcrest/hamcrest-library/
1.3/hamcrest-library-1.3.jar
Downloaded: https://repo.maven.apache.org/maven2/io/netty/netty-common/4.0.24.Fi
nal/netty-common-4.0.24.Final.jar (400 KB at 159.7 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/org/apache/commons/commons-lang
3/3.4/commons-lang3-3.4.jar (425 KB at 141.9 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/junit/junit/4.12/junit-4.12.jar
 (308 KB at 99.1 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/org/hamcrest/hamcrest-library/1
.3/hamcrest-library-1.3.jar (52 KB at 16.0 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/net/sf/trove4j/trove4j/3.0.3/tr
ove4j-3.0.3.jar (2465 KB at 301.2 KB/sec)
[INFO]
## [INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ glowkit --

[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\Rainbow\Dragonet\Glowkit\src
\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ glowkit ---
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-com
piler-api/1.8.1/plexus-compiler-api-1.8.1.pom
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-comp
iler-api/1.8.1/plexus-compiler-api-1.8.1.pom (805 B at 2.3 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-com
piler/1.8.1/plexus-compiler-1.8.1.pom
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-comp
iler/1.8.1/plexus-compiler-1.8.1.pom (4 KB at 9.6 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-com
piler-manager/1.8.1/plexus-compiler-manager-1.8.1.pom
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-comp
iler-manager/1.8.1/plexus-compiler-manager-1.8.1.pom (713 B at 2.0 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-com
piler-javac/1.8.1/plexus-compiler-javac-1.8.1.pom
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-comp
iler-javac/1.8.1/plexus-compiler-javac-1.8.1.pom (710 B at 1.9 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-com
pilers/1.8.1/plexus-compilers-1.8.1.pom
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-comp
ilers/1.8.1/plexus-compilers-1.8.1.pom (2 KB at 3.2 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-com
piler-api/1.8.1/plexus-compiler-api-1.8.1.jar
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-com
piler-javac/1.8.1/plexus-compiler-javac-1.8.1.jar
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-com
piler-manager/1.8.1/plexus-compiler-manager-1.8.1.jar
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-comp
iler-javac/1.8.1/plexus-compiler-javac-1.8.1.jar (13 KB at 33.0 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-comp
iler-api/1.8.1/plexus-compiler-api-1.8.1.jar (20 KB at 49.5 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-comp
iler-manager/1.8.1/plexus-compiler-manager-1.8.1.jar (6 KB at 10.0 KB/sec)
[INFO] Compiling 692 source files to C:\Users\Rainbow\Dragonet\Glowkit\target\cl
asses
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] Unable to locate the Javac Compiler in:
  D:\Program Files\Java\jdk1.8.0_51..\lib\tools.jar
Please ensure you are using JDK 1.4 or above and
not a JRE (the com.sun.tools.javac.Main class is required).
In most cases you can change the location of your Java
installation by setting the JAVA_HOME environment variable.
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:10 min
[INFO] Finished at: 2015-08-11T11:58:51+08:00
[INFO] Final Memory: 9M/91M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.
3.2:compile (default-compile) on project glowkit: Compilation failure
[ERROR] Unable to locate the Javac Compiler in:
[ERROR] D:\Program Files\Java\jdk1.8.0_51..\lib\tools.jar
[ERROR] Please ensure you are using JDK 1.4 or above and
[ERROR] not a JRE (the com.sun.tools.javac.Main class is required).
[ERROR] In most cases you can change the location of your Java
[ERROR] installation by setting the JAVA_HOME environment variable.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption
C:\Users\Rainbow\Dragonet\Glowkit>mvn install
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Glowkit 1.8.8-R0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven
-install-plugin/2.4/maven-install-plugin-2.4.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-
install-plugin/2.4/maven-install-plugin-2.4.pom (7 KB at 2.3 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven
-install-plugin/2.4/maven-install-plugin-2.4.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-
install-plugin/2.4/maven-install-plugin-2.4.jar (27 KB at 26.6 KB/sec)
[INFO]
## [INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ glowkit --

[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\Rainbow\Dragonet\Glowkit\src
\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ glowkit ---
[INFO] Compiling 692 source files to C:\Users\Rainbow\Dragonet\Glowkit\target\cl
asses
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] Unable to locate the Javac Compiler in:
  D:\Program Files\Java\jdk1.8.0_51..\lib\tools.jar
Please ensure you are using JDK 1.4 or above and
not a JRE (the com.sun.tools.javac.Main class is required).
In most cases you can change the location of your Java
installation by setting the JAVA_HOME environment variable.
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.367 s
[INFO] Finished at: 2015-08-11T12:00:19+08:00
[INFO] Final Memory: 10M/114M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.
3.2:compile (default-compile) on project glowkit: Compilation failure
[ERROR] Unable to locate the Javac Compiler in:
[ERROR] D:\Program Files\Java\jdk1.8.0_51..\lib\tools.jar
[ERROR] Please ensure you are using JDK 1.4 or above and
[ERROR] not a JRE (the com.sun.tools.javac.Main class is required).
[ERROR] In most cases you can change the location of your Java
[ERROR] installation by setting the JAVA_HOME environment variable.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption

**Comment by DefinitlyEvil** [comment]
Simple error, you must install Java JDK 8, not JRE 8.
