### ISSUE TITLE
Still BUILD FAILURE

### ISSUE THREAD

**Issue by ghost** [DragonetMC/Dragonet-Legacy#65]
I use this command to build:
cd Glowkit
mvn install
cd ..
cd Dragonet-core
mvn package

But it always BUILD FAILURE:

[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Dragonet 0.0.3-preR1
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.bukkit:bukkit:jar:1.8.7-R0.1-SNAPSHOT is missing, no d
ependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.129 s
[INFO] Finished at: 2015-08-11T12:34:22+08:00
[INFO] Final Memory: 6M/123M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project dragonet: Could not resolve dependenci
es for project org.dragonet:dragonet:jar:0.0.3-preR1: Failure to find org.bukkit
:bukkit:jar:1.8.7-R0.1-SNAPSHOT in https://oss.sonatype.org/content/repositories
/public/ was cached in the local repository, resolution will not be reattempted
until the update interval of sonatype has elapsed or updates are forced -> [Help
 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyReso
lutionException

**Comment by DefinitlyEvil** [comment]
@mastercoms Help! I can successfully build by using NetBeans and load both projects.

**Comment by mastercoms** [comment]
Fixed in https://github.com/DragonetMC/Dragonet/commit/04b61c0a555d0fc24b9f0e12981bd788817bee8a.

Pull from git and

``` bash
cd Dragonet-core
mvn package
```

EDIT: there was another issue, fixed in https://github.com/DragonetMC/Dragonet/commit/721976b246d62daaded9343f7a8a333930e89b27.

**Comment by mastercoms** [comment]
It will still fail, Dragonet hasn't been updated to 1.8.8. Just update from GlowstonePlusPlus.

**Comment by DefinitlyEvil** [comment]
@mastercoms  okay. ;)

**Comment by ghost** [comment]
@mastercoms I build Dragonet-Core success.
But, I build Glowkit always got this error:

[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Glowkit 1.8.8-R0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: https://oss.sonatype.org/content/repositories/snapshots/net/md-5/bu
ngeecord-api/1.8-SNAPSHOT/maven-metadata.xml
Downloaded: https://oss.sonatype.org/content/repositories/snapshots/net/md-5/bun
geecord-api/1.8-SNAPSHOT/maven-metadata.xml (2 KB at 0.4 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/net/md-5/bu
ngeecord-parent/1.8-SNAPSHOT/maven-metadata.xml
Downloaded: https://oss.sonatype.org/content/repositories/snapshots/net/md-5/bun
geecord-parent/1.8-SNAPSHOT/maven-metadata.xml (600 B at 1.0 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/net/md-5/bu
ngeecord-chat/1.8-SNAPSHOT/maven-metadata.xml
Downloading: https://oss.sonatype.org/content/repositories/snapshots/net/md-5/bu
ngeecord-chat/1.8-SNAPSHOT/maven-metadata.xml
Downloaded: https://oss.sonatype.org/content/repositories/snapshots/net/md-5/bun
geecord-chat/1.8-SNAPSHOT/maven-metadata.xml (2 KB at 1.8 KB/sec)
Downloaded: https://oss.sonatype.org/content/repositories/snapshots/net/md-5/bun
geecord-chat/1.8-SNAPSHOT/maven-metadata.xml (2 KB at 0.5 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/net/md-5/bu
ngeecord-config/1.8-SNAPSHOT/maven-metadata.xml
Downloading: https://oss.sonatype.org/content/repositories/snapshots/net/md-5/bu
ngeecord-config/1.8-SNAPSHOT/maven-metadata.xml
Downloaded: https://oss.sonatype.org/content/repositories/snapshots/net/md-5/bun
geecord-config/1.8-SNAPSHOT/maven-metadata.xml (2 KB at 0.4 KB/sec)
Downloaded: https://oss.sonatype.org/content/repositories/snapshots/net/md-5/bun
geecord-config/1.8-SNAPSHOT/maven-metadata.xml (2 KB at 0.4 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/net/md-5/bu
ngeecord-event/1.8-SNAPSHOT/maven-metadata.xml
Downloading: https://oss.sonatype.org/content/repositories/snapshots/net/md-5/bu
ngeecord-event/1.8-SNAPSHOT/maven-metadata.xml
Downloaded: https://oss.sonatype.org/content/repositories/snapshots/net/md-5/bun
geecord-event/1.8-SNAPSHOT/maven-metadata.xml (2 KB at 1.8 KB/sec)
Downloaded: https://oss.sonatype.org/content/repositories/snapshots/net/md-5/bun
geecord-event/1.8-SNAPSHOT/maven-metadata.xml (2 KB at 1.8 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/net/md-5/bu
ngeecord-protocol/1.8-SNAPSHOT/maven-metadata.xml
Downloading: https://oss.sonatype.org/content/repositories/snapshots/net/md-5/bu
ngeecord-protocol/1.8-SNAPSHOT/maven-metadata.xml
Downloaded: https://oss.sonatype.org/content/repositories/snapshots/net/md-5/bun
geecord-protocol/1.8-SNAPSHOT/maven-metadata.xml (2 KB at 2.0 KB/sec)
Downloaded: https://oss.sonatype.org/content/repositories/snapshots/net/md-5/bun
geecord-protocol/1.8-SNAPSHOT/maven-metadata.xml (2 KB at 1.8 KB/sec)
[INFO]

## [INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ glowkit --

[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\Rainbow\Dragonet\Glowkit\src
\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ glowkit ---
[INFO] Compiling 692 source files to C:\Users\Rainbow\Dragonet\Glowkit\target\cl
asses
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] Unable to locate the Javac Compiler in:
  D:\Program Files\Java\jdk1.8.0_51..\lib\tools.jar
Please ensure you are using JDK 1.4 or above and
not a JRE (the com.sun.tools.javac.Main class is required).
In most cases you can change the location of your Java
installation by setting the JAVA_HOME environment variable.
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 24.731 s
[INFO] Finished at: 2015-08-12T01:14:30+08:00
[INFO] Final Memory: 11M/172M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.
3.2:compile (default-compile) on project glowkit: Compilation failure
[ERROR] Unable to locate the Javac Compiler in:
[ERROR] D:\Program Files\Java\jdk1.8.0_51..\lib\tools.jar
[ERROR] Please ensure you are using JDK 1.4 or above and
[ERROR] not a JRE (the com.sun.tools.javac.Main class is required).
[ERROR] In most cases you can change the location of your Java
[ERROR] installation by setting the JAVA_HOME environment variable.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption

I'm using JDK 1.8.......Why it told me "Please ensure you are using JDK 1.4 or above and not a JRE (the com.sun.tools.javac.Main class is required)."..........

**Comment by mastercoms** [comment]
Are you using an IDE?

**Comment by ghost** [comment]
No, only JDK.
Build with command.

**Comment by mastercoms** [comment]
How are you building Dragonet-core successfully if you have not compiled Glowkit?

**Comment by ghost** [comment]
....Oh, this is a problem...I don't know, just ... success...

**Comment by mastercoms** [comment]
Could you send the log for dragonet?

As well as your PATH, please.

**Comment by mastercoms** [comment]
It seems like the problem is solved now, authme can build dragonet now, and that's what he wanted.
