### ISSUE TITLE
0.0.3 Dev Build Test Needed

### ISSUE THREAD

**Issue by DefinitlyEvil** [DragonetMC/Dragonet-Legacy#68]
## Dragonet Dev Build Test Needed

My phone is unable to instal MCPE 0.12.1 beta builds so I need testers to compile the code(or download the jar which currently is not ready) and test the dev builds.

**Comment by RandomAltThing** [comment]
Search youtube for "mcpe 0.12.0 build 8 apk" then download it form one of the Spanish or Portuguese or some shit videos.

**Comment by jython234** [comment]
@RandomAltThing Lol, that's how I got a 0.6.1 APK so I could test with my raspberry pi edition server.

**Comment by RandomAltThing** [comment]
@jython234 If you can't find it then search aptoide

**Comment by DefinitlyEvil** [comment]
@RandomAltThing @jython234 I can get the APK but I can't install, it said faild to parse manifest.

**Comment by jython234** [comment]
Then your probably out of luck. Use an emulAtor on the computer?

On Friday, August 14, 2015, The Evil Man <notifications@github.com> wrote:

> @RandomAltThing <https://github.com/RandomAltThing> @jython234
> <https://github.com/jython234> I can get the APK but I can't install, it
> said faild to parse manifest.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DragonetMC/Dragonet/issues/68#issuecomment-131150640>.
>


--

**Comment by DefinitlyEvil** [comment]
@jython234 Too laggy.

**Comment by RandomAltThing** [comment]
@DefinitlyEvil Try another apk. Sometimes it gets fucked up

**Comment by RandomAltThing** [comment]
@DefinitlyEvil If you could port forward it then give me IP (doubt you will) then I could test with build 8

**Comment by jython234** [comment]
No lag on my emulator, that's how I test the betas as I Do not have an
android device.

On Friday, August 14, 2015, RandomAltThing <notifications@github.com> wrote:

> @DefinitlyEvil <https://github.com/DefinitlyEvil> If you could port
> forward it then give me IP (doubt you will) then I could test with build 8
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DragonetMC/Dragonet/issues/68#issuecomment-131156053>.
>


--

**Comment by TheMCPEGamer** [comment]
@jython234 What emulator do you use?

**Comment by DefinitlyEvil** [comment]
I'm gonna run that on the demo server tomorrow, I will tell you when done.

**Comment by jython234** [comment]
I use andyroid.

On Friday, August 14, 2015, The Evil Man <notifications@github.com> wrote:

> I'm gonna run that on the demo server tomorrow, I will tell you when done.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DragonetMC/Dragonet/issues/68#issuecomment-131272374>.
>


--

**Comment by authme** [comment]
But I can't using 0.12.1 to join the 0.0.3...

**Comment by DefinitlyEvil** [comment]
@authme Have you built the latest source?

**Comment by spideyroc1** [comment]
I just tried it but the problem I am having is that I cannot find the server on my phone or emulator. So i cannot join it. Although I can find it/join it on the PC

EDIT:
Ok so I think I need to compile the new jar, but gradle isn't working. I have no idea. Can anyone add me on skype to help me. Skype: spideyroc1

**Comment by gaoyichuan** [comment]
@DefinitlyEvil I can help to perform the test. But I can't compline the jar. So can you give me a jar, please?

**Comment by DefinitlyEvil** [comment]
@gaoyichuan Try to use NetBeans with both Glowkit and Dragonet loaded and build.

**Comment by RandomAltThing** [comment]
Do you guys have java 8?
You need that.

**Comment by RandomAltThing** [comment]
@DefinitlyEvil Could you create a test server? :)

**Comment by DefinitlyEvil** [comment]
I already have one check out README.MD file, but it is still running 0.0.2.

**Comment by spideyroc1** [comment]
When I get home I will compile you the latest jar

**Comment by RandomAltThing** [comment]
@DefinitlyEvil That server does not work on mcpe

**Comment by DefinitlyEvil** [comment]
@RandomAltThing It does, but only for MCPE 0.11.x.

**Comment by DefinitlyEvil** [comment]
@RandomAltThing @jython234 I just updated Dragoent to 0.0.3 dev build on our test server, check out the readme file to get info.

**Comment by RandomAltThing** [comment]
@DefinitlyEvil It says the error is it can't retrieve dependencies from
http://repo.blockserver.org/snapshots

**Comment by DefinitlyEvil** [comment]
@jython234 ^^

**Comment by RandomAltThing** [comment]
@DefinitlyEvil MCPE: Server doesn't show as online in world list and I tried connecting on 0.12 and 0.11 but still don't work. You obviously did something wrong :P

**Comment by RandomAltThing** [comment]
@DefinitlyEvil @Jython234 Simple fix: upload JRakLib (Or whatever the blockserver repo is for) to the dragonet organization :)

**Comment by DefinitlyEvil** [comment]
@RandomAltThing Which MCPE build?

**Comment by RandomAltThing** [comment]
@DefinitlyEvil 0.11.1, and 0.12.1 build 11

**Comment by DefinitlyEvil** [comment]
To @RandomAltThing : I guess it's JRakLib's problem. 
To @jython234 : I've setup everything as told in your doc but it's still not working, help!

**Comment by RandomAltThing** [comment]
@DefinitlyEvil #BlameJython!

**Comment by RandomAltThing** [comment]
@DefinitlyEvil What do you need doing exactly Non-Network wise? Its hard for me to make commits because this project confuses me.

**Comment by DefinitlyEvil** [comment]
@RandomAltThing Hmm, adding Enchantment translations for MCPE maybe? But first of all we should solve the networking issues which are the basic things we should have done.

**Comment by alejzeis** [comment]
The server LAN issue was fixed, I forgot to add a part in the getting
started guide about setting the server MOTD. DefinitlyEvil updated the code.

On Thursday, August 27, 2015, The Evil Man notifications@github.com wrote:

> @RandomAltThing https://github.com/RandomAltThing Hmm, adding
> Enchantment translations for MCPE maybe? But first of all we should solve
> the networking issues which are the basic things we should have done.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DragonetMC/Dragonet/issues/68#issuecomment-135625061.

##

**Comment by DefinitlyEvil** [comment]
@jython234 But the server seems unable to receive and send packets. :(

**Comment by jython234** [comment]
@DefinitlyEvil best to talk on irc (freenode) try channel #redstonelamp or #blockserverproject

**Comment by DefinitlyEvil** [comment]
@jython234 Let's go on Gitter.

**Comment by DefinitlyEvil** [comment]
Test server updated with latest jar!

**Comment by DefinitlyEvil** [comment]
@DragonetMC Can anyone successfully connect to the demo server?

**Comment by RandomAltThing** [comment]
@DefinitlyEvil Nope

**Comment by RandomAltThing** [comment]
@DefinitlyEvil http://m.imgur.com/hIWyeMd,RDi5Tsu

**Comment by DefinitlyEvil** [comment]
@RandomAltThing You should be able to receive ping from it which I've already tested.

**Comment by RandomAltThing** [comment]
@DefinitlyEvil Can't run on iOS http://m.imgur.com/ZmKp5D3

**Comment by DefinitlyEvil** [comment]
Can someone even ping successfully to the demo server? @DragonetMC/watchers

**Comment by RandomAltThing** [comment]
No

**Comment by DefinitlyEvil** [comment]
@RandomAltThing But I can when I pinging my test server in my LAN. 
@jython234 Have you updated JRakLib to fit MCPE 0.12?

**Comment by alejzeis** [comment]
@DefinitlyEvil due to my experience with RedstoneLamp, the identifier
string must be absolutely correct to allow it to show up. I will do some
testing today.

On Tuesday, September 1, 2015, The Evil Man notifications@github.com
wrote:

> @RandomAltThing https://github.com/RandomAltThing But I can when I
> pinging my test server in my LAN.
> @jython234 https://github.com/jython234 Have you updated JRakLib to fit
> MCPE 0.12?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DragonetMC/Dragonet/issues/68#issuecomment-136767429.

##

**Comment by DefinitlyEvil** [comment]
@jython234 Okay. xD Make sure you using `strA.equals(strB)` instead of `strA == strB` or it can never be true.

**Comment by RandomAltThing** [comment]
I don't even get the different but ok

**Comment by mastercoms** [comment]
== checks to see if they are the same object, but .equals() checks if they are logically equal.

**Comment by alejzeis** [comment]
0.12 has been released, I consider this issue closed.
