### ISSUE TITLE
Error while Pulsing

### ISSUE THREAD

**Issue by L3ice** [DragonetMC/Dragonet-Legacy#7]
There are issues but its still awesome :+1: 
http://pastebin.com/QbX8gB7L

**Comment by DefinitlyEvil** [comment]
I think I already fixed this issue, I will publish the update soon. :)

**Comment by L3ice** [comment]
Its fixed :)
Should I close it?

**Comment by DefinitlyEvil** [comment]
Yes, I will do it for you. :)
