### ISSUE TITLE
Tab auto-completetion

### ISSUE THREAD

**Issue by Sasszem** [DragonetMC/Dragonet-Legacy#71]
I read the wiki, but I didn't see ANY functions that can be used to register commands w/ parameterlist, to use tab-completetion in JS. Is this possible w/ this?
If not, can you add this feature?
Thanks in advance!

**Comment by RandomAltThing** [comment]
Try reading the source.

**Comment by DefinitlyEvil** [comment]
@Sasszem This feature is not added yet, but now our current mission is to support MCPE 0.12 so the feature you said might be added later.

**Comment by Sasszem** [comment]
Thanks!

2015.08.18. 10:42 keltezéssel, The Evil Man írta:
