### ISSUE TITLE
Chunks

### ISSUE THREAD

**Issue by spideyroc1** [DragonetMC/Dragonet-Legacy#72]
When I join the server with mcpe, I spawn with no chunks and cannot move. I assumed that this was just my part but I am unable to on a latest compiled jar, OR the latest released build.

**Comment by DefinitlyEvil** [comment]
Dragonet 0.0.1 is not perfect, please look forward to 0.0.2. ;)

**Comment by spideyroc1** [comment]
I tried 0.0.2, but my question wasn't even answered either. So spawning with chunks is not supported yet? Correct or not. Sorry you kind of avoided the question it seemed.

**Comment by DefinitlyEvil** [comment]
@spideyroc1 0.0.2 is not finished yet and players even can not spawn, 0.0.1 is only for MCPE 0.10.4 and it supports spawning but networking issues can sometimes cause the unablility to join.
