### ISSUE TITLE
No monsters and animals?

### ISSUE THREAD

**Issue by uiue** [DragonetMC/Dragonet-Legacy#73]
No monsters and animals?

**Comment by RandomAltThing** [comment]
Apparently not. Not everything is implemented yet.

**Comment by ethsmith** [comment]
This is very new and under heavy development it is made clear in the README :P

**Comment by alejzeis** [comment]
This is not an issue, please do not open issues for features that are not implemented.

**Comment by TheDiamondYT1** [comment]
Mobs and entities will be added in [GlowStonePlusPlus](https://github.com/GlowstonePlusPlus/GlowstonePlusPlus) then merged into Dragonet.
