### ISSUE TITLE
Chat spam

### ISSUE THREAD

**Issue by Darkhax** [DragonetMC/Dragonet-Legacy#75]
Experienced this issue when using version 0.0.2 alpha. I sent a chat message from my test IOS client running version 0.11.1 of PE, and the chat message was repeatedly displayed to my PC client running 1.8.8. The message was only sent once from the client, but was sent numerous times on the client, and only stopped on server restart.

**Comment by RandomAltThing** [comment]
It will stop before that, just leave it a bit.

**Comment by RandomAltThing** [comment]
@DefinitlyEvil I believe this is a bug?

**Comment by Darkhax** [comment]
I didn't want to leave it running for too long, for reasons explained in #76. I had it going for roughly 10 minutes though.

**Comment by DefinitlyEvil** [comment]
@darkhax 0.0.2 is outdated and no longer maintained due to we made a huge networking update in 0.0.3, please try out 0.0.3 because it should fix all of the networking issues. ;)

**Comment by alejzeis** [comment]
I used to have this in the old BlockServer code, before JRakLib. It's
caused by duplicate packets being sent, and still being handled despite the
messageIndex. This is fixed in JRakLib.

On Thursday, August 27, 2015, The Evil Man notifications@github.com wrote:

> @darkhax https://github.com/darkhax 0.0.2 is outdated and no longer
> maintained due to we made a huge networking update in 0.0.3, please try out
> 0.0.3 because it should fix all of the networking issues. ;)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DragonetMC/Dragonet/issues/75#issuecomment-135624957.

##

**Comment by DefinitlyEvil** [comment]
@jython234 JRakLib is not working in Dragonet, I've checked everything and the code is same as in your wiki. xD

**Comment by alejzeis** [comment]
I'll debug as soon as I can, I just woke up.

On Thursday, August 27, 2015, The Evil Man notifications@github.com wrote:

> @jython234 https://github.com/jython234 JRakLib is not working in
> Dragonet, I've checked everything and the code is same as in your wiki. xD
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DragonetMC/Dragonet/issues/75#issuecomment-135625326.

##
