### ISSUE TITLE
Network connection goes offline. 

### ISSUE THREAD

**Issue by Darkhax** [DragonetMC/Dragonet-Legacy#76]
When using the server software on my home network, almost all network resources seem to be consumed. Almost all outgoing notwork connections (voip, irc, web) seem do be severely delayed. By running this server software I can effectively lock down any communication on my home network. Some basic info about this home network, 25mbps down and 10 mbps up, and 512mb ram on the modem. Connections with the server don't seem to be affected though. 

Edit: After further testing, I have determined that this does not start until a PE user connects to the server, as soon as this happens the network gets locked down. Testing was done using the public 0.0.2 build and the 0.11.1 pe version on an IOS device.

**Comment by ethsmith** [comment]
Memory leaks are common on Glowstone++ and since Dragonet is built on that this software will probly have the same problems.

**Comment by Darkhax** [comment]
@TekkitCommando I have updated the main post with some additional info. As for the memory leak issue, that could definitely be the case, however the physical memory on the machine running the server is doing fine. I have noticed a lot of packet spam though, which would definitely explain this, I assume that's what you were referring to?

**Comment by alejzeis** [comment]
@darkhax This packet spam is UDP correct? Could you use wireshark and post a dump of it here for us?

**Comment by mastercoms** [comment]
These are definitely not bugs with Glowstone++. We fixed all known memory leaks already, and the networking is stable and efficient. It must be the changes made in Dragonet that causes these issues.

**Comment by Darkhax** [comment]
@jython234 Yes, I can definitely share a dump from my network. I tried to disconnect every unrelated device connected to the network in order to cut down on noise, but there may still be a little in there. It's a fairly large file, so it will take a few minutes for the upload to process. [download](https://dl.dropboxusercontent.com/u/38575752/Network%20Dump%20Dragonnet.pcapng)

Edit: While running this capture I was periodically trying to connect to google, each attempt was met with a timeout and these attempts don't seem to be logged.

**Comment by alejzeis** [comment]
@darkhax What version of MCPE are you using?

**Comment by alejzeis** [comment]
@darkhax Also, which IP is the server and which is the client?

**Comment by RandomAltThing** [comment]
@Jython234 He is probably on localhost

**Comment by Darkhax** [comment]
@jython234 I am using version 0.11.1 Alpha on the IOS. This is the latest build available for IOS. The host is 192.168.1.91 and the client is 192.168.1.64.

**Comment by alejzeis** [comment]
@darkhax Thanks. It seems like the server is sending excessive amounts of UpdateBlockPacket (0x91). Since dragonet only translates Glowstone packets to PE, I think it is Glowstone sending them.

**Comment by Darkhax** [comment]
I am not very familiar with the glowstone server software, but I will try and set it up in a moment here. This should hopefully help us determine what is going on.

**Comment by Darkhax** [comment]
I performed a small test using the latest public release of Glowstone and Glowstone++, both seem to work very well and no network issues were encountered. Is there a special fork of Glowstone that is targeted towards PE clients rather than PC clients?

**Comment by alejzeis** [comment]
@darkhax Glowstone is only for PC clients, which is why dragonet wraps around them and wraps the PC packets to PE packets to send to Pocket Edition clients. I think you might need @DefinitlyEvil to look into the issue.

**Comment by Darkhax** [comment]
@jython234 @DefinitlyEvil Okay, I will be around until then.

**Comment by Darkhax** [comment]
Would I be able to get a runnable version of 0.0.3? I could build from the repo but it seems to be in a non-running state.

**Comment by alejzeis** [comment]
@darkhax non running?

**Comment by mastercoms** [comment]
I think he means the builds have been failing. The reason for the failed builds is that the blockserver.org domain has expired. repo.blockserver.org was used to fetch some dependencies for Dragonet.

**Comment by Darkhax** [comment]
@jython234 @mastercoms Yes, sorry. That is what I meant. I have not been able to build the project. While I could probably hack it all together, it would probably be best to renew the blockserver domain or update the project to use a valid location.

**Comment by alejzeis** [comment]
Oh that's right! I'll commit a fix.

On Thursday, August 27, 2015, Tyler Hancock notifications@github.com
wrote:

> @jython234 https://github.com/jython234 @mastercoms
> https://github.com/mastercoms Yes, sorry. That is what I meant. I have
> not been able to build the project. While I could probably hack it all
> together, it would probably be best to renew the blockserver domain or
> update the project to use a valid location.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DragonetMC/Dragonet/issues/76#issuecomment-135603637.

##

**Comment by DefinitlyEvil** [comment]
@darkhax All versions of Dragonet 0.0.2 is very buggy due to bad UDP networking code, but in 0.0.3 it should be fixed as we switched to JRakLib by @jython234 .

**Comment by Darkhax** [comment]
Okay, now that the build issues have been resolved, I have set up a new environment using this build. Unfortunately I have not been able to test, as the latest server build makes use of 0.12.1 for the PE. From what I understand, this version of the PE game is only available for windows 10 clients, so I am at a stand still until these latest versions come to IOS/Android. I will close the issue for now, once IOS/Android devices are capable of connecting to the latest build, I will update this post.

**Comment by DefinitlyEvil** [comment]
@darkhax No, it also have Android builds which you can get one somewhere on the Internet.

**Comment by Darkhax** [comment]
@DefinitlyEvil I just realized this. I was basing my previous comment off of Minecraft wiki, but apparently they haven't updated it with this information yet. Unfortunately I don't have an android device (which I agree, is strange, especially for a java dev). I could test it using an emulator/VM, however any testing done through those methods would likely be unreliable.

**Comment by DefinitlyEvil** [comment]
@darkhax xD
