### ISSUE TITLE
Can you add a place to download new builds as they are created

### ISSUE THREAD

**Issue by Krutonium** [DragonetMC/Dragonet-Legacy#77]
As in each time a PR is merged, run a build (CircleCI I see you have for example) and upload the resulting files somewhere where we can pull down the latest "Development" build.

**Comment by RandomAltThing** [comment]
No

**Comment by RandomAltThing** [comment]
That's why they made a [releases](http://github.com/dragonetmc/dragonet) page. Not everyone has the time to compile, or has the resources to to so. Try doing it yourself ;)

**Comment by RandomAltThing** [comment]
And also the it would be a bit cluttered it we made a build for EVERY commit.

**Comment by RandomAltThing** [comment]
Ask @DefinitlyEvil

**Comment by DefinitlyEvil** [comment]
@PFCKrutonium CircleCI has download area, click `Artifaces` tab and bam!

**Comment by RandomAltThing** [comment]
Well why did you ask someone to build it for 0.0.3 if CI does it?

**Comment by alejzeis** [comment]
My project RedstoneLamp runs a build and uploads it via ftp every travis ci
build success. We clear out the folder when there are too many builds,
manually.

On Monday, August 31, 2015, RandomAltThing notifications@github.com wrote:

> Well why did you ask someone to build it for 0.0.3 if CI does it?
> On 31 Aug 2015 10:47, "The Evil Man" <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> 
> > @PFCKrutonium https://github.com/PFCKrutonium CircleCI has download
> > area, click Artifaces tab and bam!
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/DragonetMC/Dragonet/issues/77#issuecomment-136317641
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DragonetMC/Dragonet/issues/77#issuecomment-136324156.

##

**Comment by RandomAltThing** [comment]
I'm gonna try run it on my jailbroken ios I'm downloading the jar

**Comment by RandomAltThing** [comment]
Can i please have the latest (or one of) the jars that work with 0.11.1?

**Comment by RandomAltThing** [comment]
I can't compiler it on ios :)

**Comment by RandomAltThing** [comment]
And for releases add the jar aswell as zip and tar.gz

**Comment by RandomAltThing** [comment]
@jython234 @DefinitlyEvil

**Comment by DefinitlyEvil** [comment]
@RandomAltThing Download from CircleCI. ;)

**Comment by RandomAltThing** [comment]
@DefinitlyEvil I can't find the download page link please

**Comment by Krutonium** [comment]
I also can not find the download link in Artifacts.

**Comment by mastercoms** [comment]
I can find it. You need to login to Circle CI using GitHub to see artifacts.
