### ISSUE TITLE
Organisation Invite

### ISSUE THREAD

**Issue by TheDiamondYT1** [DragonetMC/Dragonet-Legacy#79]
So I had to delete my old account for _"reasons"_ that will not be mentioned here. Please can someone in @DragonetMC/Developers invite me back. Thanks.

**Comment by DefinitlyEvil** [comment]
Can you please identify yourself?

**Comment by TheDiamondYT1** [comment]
How exactly would you want me to do that?

**Comment by TheDiamondYT1** [comment]
You do know my twitter right?

**Comment by TheDiamondYT1** [comment]
Btw check my email its [REMOVED] its always been that

**Comment by DefinitlyEvil** [comment]
Okay. 
PS: Personal info removed.

**Comment by TheDiamondYT1** [comment]
I don't really care if my email is out there you can see it by adding .patch to the end of a commit

**Comment by DefinitlyEvil** [comment]
Okay. xD
