### ISSUE TITLE
Project Dieing? Or Just on Vacation?

### ISSUE THREAD

**Issue by TheDiamondYT1** [DragonetMC/Dragonet-Legacy#80]
_I don't know why I said Vacation, I say Holiday :P_

This project doesn't really get very many commits and when it does it doesn't have a huge am mount of code in them.

**Comment by TheDiamondYT1** [comment]
What I mean by Vacation is are you taking a break from this project to do school or something?

**Comment by DefinitlyEvil** [comment]
Project is not dead and will not be dead at all, I am just tired. I need a break and I am doing other projects now, personal projects.
