### ISSUE TITLE
[RFC] Folder Structure

### ISSUE THREAD

**Issue by TheDiamondYT1** [DragonetMC/Dragonet-Legacy#82]
I have come up with an idea that may (or may not) fix the task of trying to merge glowstone into Dragonet. 

---

We upload GlowStonePlusPlus to the Dragonet organisation and add the repo as a dependency in pom.xml therefore fixing the folder structure problem.

We delete the net/glowstone folder in this repo as it would become a dependency in a remote repo. Then to merge the changes from Glowstone we can simply just push the changes straight to the remote repo 

By doing this, I believe we can remove GlowKit aswell as it is in GlowStonePlusPlus as a remote repo.

**Comment by TheDiamondYT1** [comment]
@DragonetMC/developers

**Comment by TheDiamondYT1** [comment]
Anyone?

**Comment by DefinitlyEvil** [comment]
Will it be complicated?

**Comment by TheDiamondYT1** [comment]
@DefinitlyEvil It is litteraly uploading GlowStone to a seperate repo in this organisation and adding it as a maven dependency.

**Comment by TheDiamondYT1** [comment]
@DefinitlyEvil I know you want to keep the folder structure but this is easier for everyone

**Comment by TheDiamondYT1** [comment]
@jython234 @mastercoms Do you think this is a good idea?

P.S Eclipse aint working and i cant start netbeans... will try and do this after if you guys want it.

**Comment by DefinitlyEvil** [comment]
But projects can not depend on each other.

**Comment by TheDiamondYT1** [comment]
Good point. Add it as a subrepo or remote or whatever tf its called like GlowKit is in GlowStone and RakLib in PocketMine

**Comment by RandomAltThingy** [comment]
@DefinitlyEvil  Can you give me access to create repo's?

**Comment by RandomAltThingy** [comment]
@DefinitlyEvil I will make the changes [here](https://github.com/DragonetMC/Dragonet/tree/folder-structure)

**Comment by TheDiamondYT1** [comment]
@DefinitlyEvil Give me admin access on this organisation for a while so i can do stuff...

**Comment by TheDiamondYT1** [comment]
Alright, what I am going to do is create a PR for people to contribute and fix any errors (The thousands that will occur).

**Comment by TheDiamondYT1** [comment]
@DefinitlyEvil I need you to create a repo where you upload the newest Dragonet build everytime. (And development build). I can upload too from Travis (Every few builds of course). It must be called Dragonet-latest.jar so I can use it in the C# installer for windows and Linux I'm creating.

**Comment by TheDiamondYT1** [comment]
**_ASAP**_

**Comment by mastercoms** [comment]
I'm pretty sure CircleCI makes Dragonet every commit.

**Comment by TheDiamondYT1** [comment]
@mastercoms  It does but im not sure how to download from there due to the file name

**Comment by mastercoms** [comment]
What?

**Comment by DefinitlyEvil** [comment]
@RandomAltThingy Click `Artifaces` after you download and get the first jar.

**Comment by RandomAltThingy** [comment]
You don't get it...

**Comment by mastercoms** [comment]
I don't understand. You go here: https://circleci.com/gh/DragonetMC/Dragonet/143 and then you click sign in at the top right corner, and then it signs you in with GitHub. Then, you click Artifacts, and then click [dragonet-0.0.3-preR2.jar](https://circle-artifacts.com/gh/DragonetMC/Dragonet/143/artifacts/0/tmp/circle-artifacts.aB8VXei/dragonet-0.0.3-preR2.jar)

If you want to get the jar file programmatically, CircleCI provides an API for that.

**Comment by RandomAltThingy** [comment]
Oooh

**Comment by TheDiamondYT1** [comment]
@DefinitlyEvil What happened to @TheMCPEGamer?

**Comment by DefinitlyEvil** [comment]
@RandomAltThingy idk. Probably being busy with his study. XD

**Comment by wordandahalf** [comment]
@RandomAltThingy @DefinitlyEvil Yep :(

Over the weekend, I'll add some new methods to the JS API to make it more compatible with 0.12.x.

**Comment by TheDiamondYT1** [comment]
@TheMCPEGamer I can do that if you want.

And **_PLEASE**_ make a GlowStonePlusPlus repo and give me write access.

**Comment by wordandahalf** [comment]
@RandomAltThingy I'll do the API stuff, and I just created a GlowstonePlusPlus repository (https://github.com/DragonetMC/GlowstonePlusPlus), you should have write access and if you don't please tell me.

**Comment by TheDiamondYT1** [comment]
@TheMCPEGamer I do. I will now push the GlowStone code from Dragonet and delete the org/glowstone folder in the branch folder-structure.

**Comment by wordandahalf** [comment]
@RandomAltThingy Thanks :D

**Comment by TheDiamondYT1** [comment]
@TheMCPEGamer Shit can you delete all branches a sec

**Comment by wordandahalf** [comment]
@RandomAltThingy Delete all the branches in the Glowstone++ repo?

**Comment by TheDiamondYT1** [comment]
@TheMCPEGamer IN DRAGONET

**Comment by wordandahalf** [comment]
@RandomAltThingy Done.

**Comment by TheDiamondYT1** [comment]
@TheMCPEGamer Please add the remote at. https://github.com/DragonetMC/GlowstonePlusPlus to the folder-structure branch. It won't let me :P.

**Comment by DefinitlyEvil** [comment]
I've changed some Glowstone++ code to access some Dragonet classes, so how do we solve this problem? Some classes imported Glostone classes.

**Comment by TheDiamondYT1** [comment]
@DefinitlyEvil Look at PocketMine and RakLib. And GlowStonePlusPlus and GlowKit. They are remote repos (The second ones I said). I'm assuming you can import from a remote, right?

Just put the remote outside of the src folder.

**Comment by DefinitlyEvil** [comment]
You mean using a sub-module?

**Comment by TheDiamondYT1** [comment]
Whatever just like in GlowStonePlusPlus with the glow kit thing.

**Comment by DefinitlyEvil** [comment]
@RandomAltThingy That should be possible. xD I just don't know how.

**Comment by TheDiamondYT1** [comment]
@mastercoms Please do this xD. Read my above comment (The long one)

**Comment by DefinitlyEvil** [comment]
@RandomAltThingy I don't know how. XD

**Comment by TheDiamondYT1** [comment]
@DragonetMC/developers as of commit https://github.com/DragonetMC/Dragonet/commit/c434c0e42a2f2365423fcea3512c21ff60935341 you can no longer push GlowStone code to this repository. I am working as fast as I can to restore everything. I have a backup of the repo before.

**Comment by TheDiamondYT1** [comment]
@DragonetMC/developers I NEED SOME IDEAS. I'm assuming GlowStone imports Dragonet. Couldn't we add Dragonet as a sub module in GlowStone repo? Or does a submodule get access to the dragonet repo anyway?. The current error is to do with net.glowstone.Glowkit.

**Comment by TheDiamondYT1** [comment]
Done in latest commit! Compiled mvn package and ran the server.

**Comment by DefinitlyEvil** [comment]
And now it fails building. wtf! @RandomAltThingy

**Comment by TheDiamondYT1** [comment]
@DefinitlyEvil #BlameCircle

It does not download the GlowStone repo (We need to do manually with git clone --recursive) but circle I can't figure hoe to do that.

**Comment by DefinitlyEvil** [comment]
@RandomAltThingy I knew and I've done that, but the folder for Glowstone is weird: `Dragonet-core/src/main/java/GlowstonePlusPlus/src/main/java/org/glowstone` and which confuses NetBeans.

**Comment by alejzeis** [comment]
I think @RandomAltThingy put it in the wrong place. I'll fix it up as soon
as I can, I know how to use submodules.

On Wednesday, October 7, 2015, The Evil Man notifications@github.com
wrote:

> @RandomAltThingy https://github.com/RandomAltThingy I knew and I've
> done that, but the folder for Glowstone is weird:
> Dragonet-core/src/main/java/GlowstonePlusPlus/src/main/java/org/glowstone
> and which confuses NetBeans.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DragonetMC/Dragonet/issues/82#issuecomment-146144949.

##

**Comment by TheDiamondYT1** [comment]
@Jython234 :P. At least I got it working.

**Comment by DefinitlyEvil** [comment]
@jython234 So nice are you! :D

**Comment by mastercoms** [comment]
It has been fixed, just needs an update to your GlowstonePlusPlus, and it will build fine.

EDIT: no, someone just added the + signs from a git diff by accident, so the code had unexpected plus signs and failed to compile.

**Comment by mastercoms** [comment]
First, in the GlowstonePlusPlus folder, setup the upstream repo. You only need to do this once.
`git remote add upstream https://github.com/GlowstonePlusPlus/GlowstonePlusPlus.git`

Now, every time you want to update, do this:

```
git pull upstream
git merge upstream/master
```

I'm not going to do this because it is too much work for me.

**Comment by RandomAltThingy** [comment]
Too much work? Fuck off lol.

**Comment by mastercoms** [comment]
I have Glowstone++ to do, I'm not going to do Dragonet also. That's your job.

**Comment by mastercoms** [comment]
Well, I had to redo everything, but I fixed it.

**Comment by DefinitlyEvil** [comment]
Thx for ur time. XD
