### ISSUE TITLE
Spam... 

### ISSUE THREAD

**Issue by TheDiamondYT1** [DragonetMC/Dragonet-Legacy#83]
```
Microsoft Windows [Version 6.1.7600]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\someone\r>cd Downloads

C:\Users\someone\Downloads>java -jar dragonet.jar
16:25:37 [INFO] This server is running Dragonet version BlueSky(0.0.3) preR2 (Im
plementing API version Bukkit API 1.8.8-R0.1-SNAPSHOT)
16:25:37 [INFO] Creating default config: config\glowstone.yml
16:25:39 [INFO] Recipes: 295 shaped, 63 shapeless, 24 furnace, 10 dynamic, 14 fu
els.
16:25:40 [INFO] Downloading sqlite-jdbc 3.7.2...
16:25:47 [INFO] Downloading mysql-connector-java 5.1.34...
16:25:48 [INFO] Scanning plugins...
16:25:48 [INFO] Starting Dragonet Server version BlueSky(0.0.3) preR2...
16:25:48 [WARNING] ** This is a snapshot or an un-official build of Dragonet, yo
u may expirence bugs and errors!
16:25:48 [INFO] Current Minecraft PC Version: 1.8.8
16:25:48 [INFO] Current Minecraft: Pocket Edition Version: 0.12.1
16:25:48 [INFO] Trying to bind on UDP address 0.0.0.0:19132...
16:25:49 [INFO] JRakLib Server started on: /0.0.0.0:19132
16:25:49 [INFO] Loading DAPIS scripts...
16:26:03 [INFO] Loading PHP scripts
16:26:03 [WARNING] ** PHP plugin support isn't finished yet, plugins written in
PHP won't load.
16:26:03 [INFO] Dragonet successfully initialized!
16:26:03 [INFO] Scanning plugins...
16:26:03 [INFO] Created default config: config\help.yml
16:26:05 [INFO] Preparing spawn for world...
16:26:22 [INFO] Preparing spawn for world: 0%
16:26:24 [INFO] Preparing spawn for world: 0%
16:26:26 [INFO] Preparing spawn for world: 1%
16:26:27 [INFO] Preparing spawn for world: 1%
16:26:29 [INFO] Preparing spawn for world: 2%
16:26:30 [INFO] Preparing spawn for world: 2%
16:26:31 [INFO] Preparing spawn for world: 2%
16:26:32 [INFO] Preparing spawn for world: 2%
16:26:34 [INFO] Preparing spawn for world: 2%
16:26:35 [INFO] Preparing spawn for world: 3%
16:26:36 [INFO] Preparing spawn for world: 3%
16:26:37 [INFO] Preparing spawn for world: 3%
16:26:39 [INFO] Preparing spawn for world: 3%
16:26:40 [INFO] Preparing spawn for world: 4%
16:26:41 [INFO] Preparing spawn for world: 4%
16:26:43 [INFO] Preparing spawn for world: 4%
16:26:44 [INFO] Preparing spawn for world: 4%
16:26:45 [INFO] Preparing spawn for world: 4%
16:26:47 [INFO] Preparing spawn for world: 6%
16:26:48 [INFO] Preparing spawn for world: 6%
16:26:49 [INFO] Preparing spawn for world: 7%
16:26:50 [INFO] Preparing spawn for world: 8%
16:26:52 [INFO] Preparing spawn for world: 9%
16:26:54 [INFO] Preparing spawn for world: 11%
16:26:55 [INFO] Preparing spawn for world: 12%
16:26:56 [INFO] Preparing spawn for world: 13%
16:26:57 [INFO] Preparing spawn for world: 14%
16:26:59 [INFO] Preparing spawn for world: 14%
16:27:00 [INFO] Preparing spawn for world: 15%
16:27:01 [INFO] Preparing spawn for world: 16%
16:27:02 [INFO] Preparing spawn for world: 17%
16:27:03 [INFO] Preparing spawn for world: 18%
16:27:06 [INFO] Preparing spawn for world: 19%
16:27:07 [INFO] Preparing spawn for world: 20%
16:27:08 [INFO] Preparing spawn for world: 21%
16:27:09 [INFO] Preparing spawn for world: 22%
16:27:10 [INFO] Preparing spawn for world: 23%
16:27:12 [INFO] Preparing spawn for world: 24%
16:27:13 [INFO] Preparing spawn for world: 25%
16:27:14 [INFO] Preparing spawn for world: 26%
16:27:15 [INFO] Preparing spawn for world: 26%
16:27:17 [INFO] Preparing spawn for world: 28%
16:27:19 [INFO] Preparing spawn for world: 28%
16:27:21 [INFO] Preparing spawn for world: 29%
16:27:22 [INFO] Preparing spawn for world: 30%
16:27:23 [INFO] Preparing spawn for world: 31%
16:27:24 [INFO] Preparing spawn for world: 33%
16:27:26 [INFO] Preparing spawn for world: 33%
16:27:27 [INFO] Preparing spawn for world: 34%
16:27:28 [INFO] Preparing spawn for world: 35%
16:27:29 [INFO] Preparing spawn for world: 36%
16:27:30 [INFO] Preparing spawn for world: 37%
16:27:32 [INFO] Preparing spawn for world: 38%
16:27:34 [INFO] Preparing spawn for world: 39%
16:27:35 [INFO] Preparing spawn for world: 40%
16:27:36 [INFO] Preparing spawn for world: 41%
16:27:37 [INFO] Preparing spawn for world: 42%
>@echo off
16:27:39 [INFO] Preparing spawn for world: 43%
16:27:40 [INFO] Preparing spawn for world: 44%
16:27:41 [INFO] Preparing spawn for world: 45%
>echo h
16:27:42 [INFO] Preparing spawn for world: 46%
16:27:43 [INFO] Preparing spawn for world: 47%
>uwehfuahwfuia
16:27:45 [INFO] Preparing spawn for world: 47%
16:27:46 [INFO] Preparing spawn for world: 48%
>Test
16:27:48 [INFO] Preparing spawn for world: 50%
16:27:49 [INFO] Preparing spawn for world: 51%
16:27:50 [INFO] Preparing spawn for world: 52%
16:27:51 [INFO] Preparing spawn for world: 52%
16:27:52 [INFO] Preparing spawn for world: 53%
>ipconfig
16:27:53 [INFO] Preparing spawn for world: 54%
16:27:55 [INFO] Preparing spawn for world: 56%
16:27:56 [INFO] Preparing spawn for world: 57%
16:27:57 [INFO] Preparing spawn for world: 57%
16:27:58 [INFO] Preparing spawn for world: 58%
16:27:59 [INFO] Preparing spawn for world: 60%
16:28:00 [INFO] Preparing spawn for world: 61%
>taskkill /IM cmd.exe
16:28:02 [INFO] Preparing spawn for world: 62%
16:28:03 [INFO] Preparing spawn for world: 63%
>powershell
16:28:05 [INFO] Preparing spawn for world: 64%
>color 1
16:28:06 [INFO] Preparing spawn for world: 65%
16:28:07 [INFO] Preparing spawn for world: 66%
16:28:08 [INFO] Preparing spawn for world: 66%
16:28:09 [INFO] Preparing spawn for world: 69%
16:28:11 [INFO] Preparing spawn for world: 71%
16:28:12 [INFO] Preparing spawn for world: 71%
16:28:13 [INFO] Preparing spawn for world: 73%
16:28:14 [INFO] Preparing spawn for world: 75%
16:28:15 [INFO] Preparing spawn for world: 76%
16:28:16 [INFO] Preparing spawn for world: 78%
16:28:17 [INFO] Preparing spawn for world: 80%
16:28:19 [INFO] Preparing spawn for world: 81%
16:28:20 [INFO] Preparing spawn for world: 83%
16:28:21 [INFO] Preparing spawn for world: 85%
16:28:22 [INFO] Preparing spawn for world: 85%
16:28:23 [INFO] Preparing spawn for world: 87%
16:28:25 [INFO] Preparing spawn for world: 89%
16:28:26 [INFO] Preparing spawn for world: 90%
16:28:27 [INFO] Preparing spawn for world: 92%
16:28:28 [INFO] Preparing spawn for world: 94%
16:28:29 [INFO] Preparing spawn for world: 95%
16:28:31 [INFO] Preparing spawn for world: 97%
16:28:32 [INFO] Preparing spawn for world: 99%
16:28:32 [INFO] Preparing spawn for world: done
16:28:32 [INFO] Preparing spawn for world_nether...
16:28:33 [INFO] Preparing spawn for world_nether: done
16:28:33 [INFO] Preparing spawn for world_the_end...
16:28:33 [INFO] Preparing spawn for world_the_end: done
16:28:33 [INFO] Created default config: config\commands.yml
16:28:34 [INFO] Created default config: config\permissions.yml
16:28:34 [INFO] Binding to address: 0.0.0.0/0.0.0.0:25565...
16:28:34 [INFO] (192.168.1.103:19132) New session with clientID: 634067167262209
3568
16:28:34 [INFO] (192.168.1.103:19132) PACKET IN: 92 00 00 04 7C 78 DA DD 98 CB 6
F 4D 41 1C C7 47 6C A4 2A A9 88 45 77 8D 58 54 D0 B8 F5 2C 89 85 68 EC 6C 3C 82
85 20 2A 2A 29 B1 21 A2 89 85 3D 0B 3B B1 10 21 B1 F2 07 10 B1 91 94 45 89 47 44
 3D 52 11 2C 8A 05 9B 5A B8 E7 B8 DF B9 E7 7B 7C CF AF 73 EE C3 3D D2 CB 24 BF C
E 9C 39 33 73 7E 9F DF 63 66 6E 9D EB D9 77 D1 2D D8 79 74 68 EB F0 C1 91 13 C7
0F EF DD B9 DE 39 B7 04 72 72 9B 9B FF E6 F2 E9 55 77 76 BF BE B4 F4 D3 99 F7 2F
 DE 7E FD F0 66 E5 F1 6B 6E 51 69 A0 BF AF B4 6E 43 5F A9 AF B4 6A CD C6 D2 40 6
9 75 BF EB 9A 77 EF E4 CB 65 B7 2F 2C 7A 7A 65 FF F6 F3 13 5B 26 5D 8F 8B A5 54
56 9C 51 0F 9F 7B E8 65 CF C8 AD 60 5B 25 D4 DF 6A 71 05 94 26 BE 95 69 93 1F 5C
 2A BB 8F DD 8C 77 1C B9 11 0F 9D BD 9F 61 B7 82 FE 26 3E DF 56 FC EA 7F B0 2A 1
7 9F 51 E7 B1 53 FE 25 FE 50 69 C4 FF B6 1F 75 BB F8 BF A5 8F 27 FC 96 2B 4F 34
2E FE 07 7E 1B FF 36 0F C8 98 E7 7F C8 6C B2 FF 4D FF 33 F7 EB E5 7F BB F3 BB 64
 9F 57 61 3F F9 F5 6C 53 BF E7 89 BE 9F 4D F6 46 F8 EB 9D DF CD BC B7 F1 D0 C8 D
C A2 38 FF B4 D4 3A BB EB C5 B7 8E D1 3D AF D6 7D 29 70 3F 68 0B 7E 9B E3 9A DF
FD 9B 0F 79 A1 DE 7C B6 4C 98 A3 7B A4 7D CF 6F F0 3B ED C0 9F 77 76 51 4F CB 0F
 BD 9B E5 0F 9D 1F 5C BB 5D F8 1B 39 E3 F9 4E EF 37 F5 EE 3F D6 3E B6 DD 2E FC B
5 F2 5B FB 34 0F EC 99 10 BA FF 84 EE 8D 6A A3 D9 E6 2F 6A FF B3 FE 0F ED 8D A1
B9 ED C0 DF EC EF DB 03 A7 EE 36 74 0E 36 72 6E CE 36 7F 7A 11 88 E2 78 6A EA 4B
 3C 3A 3A 9A 11 67 EE 46 BB 2A 72 0F 72 C0 C5 AB 93 BE 28 8A 92 45 CA F1 F7 6F D
F 52 71 73 E6 66 9E 55 62 CC A9 C8 8F E9 69 2F 5F 3E 7F 8E A3 72 D9 AF 15 55 D6
89 CB A8 53 D5 FC DA 68 70 3E E7 30 9F 28 D9 52 AE 7B CF AA EA 5E 1D D7 08 BF 1F
 1F 89 5E D1 4F 3F 9F BA 92 DB 0A 74 7D 37 39 E9 F5 FE F4 F1 63 C6 06 0F C6 C6 D
2 B6 81 16 1D AB 05 F3 75 AE E5 A7 26 55 3B 86 CB 8B EB D9 6B 61 04 86 06 FD 1F
50 CF F3 97 E3 EA 1A D0 09 BC D0 F3 F9 B3 67 BE 66 1C 80 1B 82 31 B0 C5 6F E6 C8
 DB C7 73 C5 E5 AC EE 51 55 BC 97 2A 7F EC 3C CB 9F C6 4A 32 DE 96 27 57 5D 26 E
7 2C 47 3D 7E D5 49 73 A7 5A 97 53 7E B0 43 D4 1E EA 3B B4 95 1B B5 B7 4D 12 E7
F6 1B 8C 01 F0 BF 9A 98 48 EB 50 FC FF 8E C6 6C FC E7 6D 01 AD 08 75 87 3E D0 1F
 35 78 19 EB F4 3F 58 C9 0E BD 91 EB E4 57 C1 3C 88 DD 2F 98 33 98 A7 B6 B4 F9 A
0 73 B0 5E 1D F6 42 F8 A9 C3 A3 F1 F1 34 FF A9 27 9F E9 73 8E C7 7B 8E D7 18 08
B1 EB 9E C7 7D 8F 73 2C AF F6 2B BF DA C1 3C B7 24 FC 26 7C CA 9C A7 FF A1 03 9F
 C1 4A FD 69 07 08 C6 71 0D FA 38 C4 8D F5 B1 16 C7 FB B3 A2 22 6A 3B AE 9D DD 4
F FE 2E 7F C8 1F 79 FE 27 1F FB 39 8F 77 01 C6 39 9F 75 6D F4 A7 4C 49 9C D3 0E
BA 26 73 04 F6 AA EE 27 33 F9 D5 06 AD F2 E3 5B 9A EB 9A FF DC 03 35 FE A9 2F 99
 94 97 7C CA AF E7 06 BF A1 CF 9A 3F BA 6E 5E FC 5B 1B 14 91 FF 7A A7 21 2F FD 0
F 5D 34 FE 69 07 E6 87 E6 7C 47 47 87 17 8D 0D 0A E3 DD E6 08 BF C1 1C 64 3F DA
79 FC 45 C6 BF EE 4B D4 DB FF DF 2F 39 E3 B9 FF 33 57 39 8E CC CC 67 B2 AB 0D 74
 BF E4 5C FA 5E EF 52 EA 6F 9E 43 A9 4F 6A 94 B5 1D 9B 0A C9 7F EA C7 18 E0 D9 8
6 7E DC ED 60 0F CB AF F9 AA BE 87 74 76 76 66 F6 3D BD 33 A8 BF 6D DC DB 33 21
94 FF 45 FB 9F 7E 24 B3 B6 E9 23 C6 2F 73 93 3E D7 F3 1C DC 3C FB D1 C6 7B E4 12
 F7 0B 9B DB 96 5B 6D A2 B6 B0 65 61 57 57 46 5A E5 87 7F D4 E7 3E E7 12 5F F1 F
E AB 3E A4 30 9F 69 23 E6 82 72 68 5C B1 D6 58 0F C5 C0 8C DF 59 75 F8 BB BB BB
BD E8 6F F3 5A 7D DA 8F 36 7D C9 F3 8D DC 10 DD 9F 94 99 1C 9A D3 5C 47 CF B9 D0
 EF BB 66 A5 16 FF 8A E5 CB E3 DE DE DE 96 84 5C 7A 47 41 A1 1D 6C 6E 72 BF C2 7
9 A0 B5 EE 89 2A 45 F3 B3 0C 0E 0E C6 0B 16 3F 8E 7F 01 91 05 64 EA
16:28:39 [INFO] Successfully bound to: /0:0:0:0:0:0:0:0:25565
16:28:39 [INFO] Ready for connections.
'''
```

**Comment by alejzeis** [comment]
What's the spam? It seems fine to me.

On Saturday, September 12, 2015, RandomAltThingy notifications@github.com
wrote:

> '''
> Microsoft Windows [Version 6.1.7600]
> Copyright (c) 2009 Microsoft Corporation. All rights reserved.
> 
> C:\Users\someone\r>cd Downloads
> 
> C:\Users\someone\Downloads>java -jar dragonet.jar
> 16:25:37 [INFO] This server is running Dragonet version BlueSky(0.0.3)
> preR2 (Im
> plementing API version Bukkit API 1.8.8-R0.1-SNAPSHOT)
> 16:25:37 [INFO] Creating default config: config\glowstone.yml
> 16:25:39 [INFO] Recipes: 295 shaped, 63 shapeless, 24 furnace, 10 dynamic,
> 14 fu
> els.
> 16:25:40 [INFO] Downloading sqlite-jdbc 3.7.2...
> 16:25:47 [INFO] Downloading mysql-connector-java 5.1.34...
> 16:25:48 [INFO] Scanning plugins...
> 16:25:48 [INFO] Starting Dragonet Server version BlueSky(0.0.3) preR2...
> 16:25:48 [WARNING] *\* This is a snapshot or an un-official build of
> Dragonet, yo
> u may expirence bugs and errors!
> 16:25:48 [INFO] Current Minecraft PC Version: 1.8.8
> 16:25:48 [INFO] Current Minecraft: Pocket Edition Version: 0.12.1
> 16:25:48 [INFO] Trying to bind on UDP address 0.0.0.0:19132...
> 16:25:49 [INFO] JRakLib Server started on: /0.0.0.0:19132
> 16:25:49 [INFO] Loading DAPIS scripts...
> 16:26:03 [INFO] Loading PHP scripts
> 16:26:03 [WARNING] *\* PHP plugin support isn't finished yet, plugins
> written in
> PHP won't load.
> 16:26:03 [INFO] Dragonet successfully initialized!
> 16:26:03 [INFO] Scanning plugins...
> 16:26:03 [INFO] Created default config: config\help.yml
> 16:26:05 [INFO] Preparing spawn for world...
> 16:26:22 [INFO] Preparing spawn for world: 0%
> 16:26:24 [INFO] Preparing spawn for world: 0%
> 16:26:26 [INFO] Preparing spawn for world: 1%
> 16:26:27 [INFO] Preparing spawn for world: 1%
> 16:26:29 [INFO] Preparing spawn for world: 2%
> 16:26:30 [INFO] Preparing spawn for world: 2%
> 16:26:31 [INFO] Preparing spawn for world: 2%
> 16:26:32 [INFO] Preparing spawn for world: 2%
> 16:26:34 [INFO] Preparing spawn for world: 2%
> 16:26:35 [INFO] Preparing spawn for world: 3%
> 16:26:36 [INFO] Preparing spawn for world: 3%
> 16:26:37 [INFO] Preparing spawn for world: 3%
> 16:26:39 [INFO] Preparing spawn for world: 3%
> 16:26:40 [INFO] Preparing spawn for world: 4%
> 16:26:41 [INFO] Preparing spawn for world: 4%
> 16:26:43 [INFO] Preparing spawn for world: 4%
> 16:26:44 [INFO] Preparing spawn for world: 4%
> 16:26:45 [INFO] Preparing spawn for world: 4%
> 16:26:47 [INFO] Preparing spawn for world: 6%
> 16:26:48 [INFO] Preparing spawn for world: 6%
> 16:26:49 [INFO] Preparing spawn for world: 7%
> 16:26:50 [INFO] Preparing spawn for world: 8%
> 16:26:52 [INFO] Preparing spawn for world: 9%
> 16:26:54 [INFO] Preparing spawn for world: 11%
> 16:26:55 [INFO] Preparing spawn for world: 12%
> 16:26:56 [INFO] Preparing spawn for world: 13%
> 16:26:57 [INFO] Preparing spawn for world: 14%
> 16:26:59 [INFO] Preparing spawn for world: 14%
> 16:27:00 [INFO] Preparing spawn for world: 15%
> 16:27:01 [INFO] Preparing spawn for world: 16%
> 16:27:02 [INFO] Preparing spawn for world: 17%
> 16:27:03 [INFO] Preparing spawn for world: 18%
> 16:27:06 [INFO] Preparing spawn for world: 19%
> 16:27:07 [INFO] Preparing spawn for world: 20%
> 16:27:08 [INFO] Preparing spawn for world: 21%
> 16:27:09 [INFO] Preparing spawn for world: 22%
> 16:27:10 [INFO] Preparing spawn for world: 23%
> 16:27:12 [INFO] Preparing spawn for world: 24%
> 16:27:13 [INFO] Preparing spawn for world: 25%
> 16:27:14 [INFO] Preparing spawn for world: 26%
> 16:27:15 [INFO] Preparing spawn for world: 26%
> 16:27:17 [INFO] Preparing spawn for world: 28%
> 16:27:19 [INFO] Preparing spawn for world: 28%
> 16:27:21 [INFO] Preparing spawn for world: 29%
> 16:27:22 [INFO] Preparing spawn for world: 30%
> 16:27:23 [INFO] Preparing spawn for world: 31%
> 16:27:24 [INFO] Preparing spawn for world: 33%
> 16:27:26 [INFO] Preparing spawn for world: 33%
> 16:27:27 [INFO] Preparing spawn for world: 34%
> 16:27:28 [INFO] Preparing spawn for world: 35%
> 16:27:29 [INFO] Preparing spawn for world: 36%
> 16:27:30 [INFO] Preparing spawn for world: 37%
> 16:27:32 [INFO] Preparing spawn for world: 38%
> 16:27:34 [INFO] Preparing spawn for world: 39%
> 16:27:35 [INFO] Preparing spawn for world: 40%
> 16:27:36 [INFO] Preparing spawn for world: 41%
> 16:27:37 [INFO] Preparing spawn for world: 42%
> 
> @echo https://github.com/echo off
> 16:27:39 [INFO] Preparing spawn for world: 43%
> 16:27:40 [INFO] Preparing spawn for world: 44%
> 16:27:41 [INFO] Preparing spawn for world: 45%
> echo h
> 16:27:42 [INFO] Preparing spawn for world: 46%
> 16:27:43 [INFO] Preparing spawn for world: 47%
> uwehfuahwfuia
> 16:27:45 [INFO] Preparing spawn for world: 47%
> 16:27:46 [INFO] Preparing spawn for world: 48%
> Test
> 16:27:48 [INFO] Preparing spawn for world: 50%
> 16:27:49 [INFO] Preparing spawn for world: 51%
> 16:27:50 [INFO] Preparing spawn for world: 52%
> 16:27:51 [INFO] Preparing spawn for world: 52%
> 16:27:52 [INFO] Preparing spawn for world: 53%
> ipconfig
> 16:27:53 [INFO] Preparing spawn for world: 54%
> 16:27:55 [INFO] Preparing spawn for world: 56%
> 16:27:56 [INFO] Preparing spawn for world: 57%
> 16:27:57 [INFO] Preparing spawn for world: 57%
> 16:27:58 [INFO] Preparing spawn for world: 58%
> 16:27:59 [INFO] Preparing spawn for world: 60%
> 16:28:00 [INFO] Preparing spawn for world: 61%
> taskkill /IM cmd.exe
> 16:28:02 [INFO] Preparing spawn for world: 62%
> 16:28:03 [INFO] Preparing spawn for world: 63%
> powershell
> 16:28:05 [INFO] Preparing spawn for world: 64%
> color 1
> 16:28:06 [INFO] Preparing spawn for world: 65%
> 16:28:07 [INFO] Preparing spawn for world: 66%
> 16:28:08 [INFO] Preparing spawn for world: 66%
> 16:28:09 [INFO] Preparing spawn for world: 69%
> 16:28:11 [INFO] Preparing spawn for world: 71%
> 16:28:12 [INFO] Preparing spawn for world: 71%
> 16:28:13 [INFO] Preparing spawn for world: 73%
> 16:28:14 [INFO] Preparing spawn for world: 75%
> 16:28:15 [INFO] Preparing spawn for world: 76%
> 16:28:16 [INFO] Preparing spawn for world: 78%
> 16:28:17 [INFO] Preparing spawn for world: 80%
> 16:28:19 [INFO] Preparing spawn for world: 81%
> 16:28:20 [INFO] Preparing spawn for world: 83%
> 16:28:21 [INFO] Preparing spawn for world: 85%
> 16:28:22 [INFO] Preparing spawn for world: 85%
> 16:28:23 [INFO] Preparing spawn for world: 87%
> 16:28:25 [INFO] Preparing spawn for world: 89%
> 16:28:26 [INFO] Preparing spawn for world: 90%
> 16:28:27 [INFO] Preparing spawn for world: 92%
> 16:28:28 [INFO] Preparing spawn for world: 94%
> 16:28:29 [INFO] Preparing spawn for world: 95%
> 16:28:31 [INFO] Preparing spawn for world: 97%
> 16:28:32 [INFO] Preparing spawn for world: 99%
> 16:28:32 [INFO] Preparing spawn for world: done
> 16:28:32 [INFO] Preparing spawn for world_nether...
> 16:28:33 [INFO] Preparing spawn for world_nether: done
> 16:28:33 [INFO] Preparing spawn for world_the_end...
> 16:28:33 [INFO] Preparing spawn for world_the_end: done
> 16:28:33 [INFO] Created default config: config\commands.yml
> 16:28:34 [INFO] Created default config: config\permissions.yml
> 16:28:34 [INFO] Binding to address: 0.0.0.0/0.0.0.0:25565...
> 16:28:34 INFO New session with clientID: 634067167262209
> 3568
> 16:28:34 INFO PACKET IN: 92 00 00 04 7C 78 DA DD 98 CB 6
> F 4D 41 1C C7 47 6C A4 2A A9 88 45 77 8D 58 54 D0 B8 F5 2C 89 85 68 EC 6C
> 3C 82
> 85 20 2A 2A 29 B1 21 A2 89 85 3D 0B 3B B1 10 21 B1 F2 07 10 B1 91 94 45 89
> 47 44
> 3D 52 11 2C 8A 05 9B 5A B8 E7 B8 DF B9 E7 7B 7C CF AF 73 EE C3 3D D2 CB 24
> BF C
> E 9C 39 33 73 7E 9F DF 63 66 6E 9D EB D9 77 D1 2D D8 79 74 68 EB F0 C1 91
> 13 C7
> 0F EF DD B9 DE 39 B7 04 72 72 9B 9B FF E6 F2 E9 55 77 76 BF BE B4 F4 D3 99
> F7 2F
> DE 7E FD F0 66 E5 F1 6B 6E 51 69 A0 BF AF B4 6E 43 5F A9 AF B4 6A CD C6 D2
> 40 6
> 9 75 BF EB 9A 77 EF E4 CB 65 B7 2F 2C 7A 7A 65 FF F6 F3 13 5B 26 5D 8F 8B
> A5 54
> 56 9C 51 0F 9F 7B E8 65 CF C8 AD 60 5B 25 D4 DF 6A 71 05 94 26 BE 95 69 93
> 1F 5C
> 2A BB 8F DD 8C 77 1C B9 11 0F 9D BD 9F 61 B7 82 FE 26 3E DF 56 FC EA 7F B0
> 2A 1
> 7 9F 51 E7 B1 53 FE 25 FE 50 69 C4 FF B6 1F 75 BB F8 BF A5 8F 27 FC 96 2B
> 4F 34
> 2E FE 07 7E 1B FF 36 0F C8 98 E7 7F C8 6C B2 FF 4D FF 33 F7 EB E5 7F BB F3
> BB 64
> 9F 57 61 3F F9 F5 6C 53 BF E7 89 BE 9F 4D F6 46 F8 EB 9D DF CD BC B7 F1 D0
> C8 D
> C A2 38 FF B4 D4 3A BB EB C5 B7 8E D1 3D AF D6 7D 29 70 3F 68 0B 7E 9B E3
> 9A DF
> FD 9B 0F 79 A1 DE 7C B6 4C 98 A3 7B A4 7D CF 6F F0 3B ED C0 9F 77 76 51 4F
> CB 0F
> BD 9B E5 0F 9D 1F 5C BB 5D F8 1B 39 E3 F9 4E EF 37 F5 EE 3F D6 3E B6 DD 2E
> FC B
> 5 F2 5B FB 34 0F EC 99 10 BA FF 84 EE 8D 6A A3 D9 E6 2F 6A FF B3 FE 0F ED
> 8D A1
> B9 ED C0 DF EC EF DB 03 A7 EE 36 74 0E 36 72 6E CE 36 7F 7A 11 88 E2 78 6A
> EA 4B
> 3C 3A 3A 9A 11 67 EE 46 BB 2A 72 0F 72 C0 C5 AB 93 BE 28 8A 92 45 CA F1 F7
> 6F D
> F 52 71 73 E6 66 9E 55 62 CC A9 C8 8F E9 69 2F 5F 3E 7F 8E A3 72 D9 AF 15
> 55 D6
> 89 CB A8 53 D5 FC DA 68 70 3E E7 30 9F 28 D9 52 AE 7B CF AA EA 5E 1D D7 08
> BF 1F
> 1F 89 5E D1 4F 3F 9F BA 92 DB 0A 74 7D 37 39 E9 F5 FE F4 F1 63 C6 06 0F C6
> C6 D
> 2 B6 81 16 1D AB 05 F3 75 AE E5 A7 26 55 3B 86 CB 8B EB D9 6B 61 04 86 06
> FD 1F
> 50 CF F3 97 E3 EA 1A D0 09 BC D0 F3 F9 B3 67 BE 66 1C 80 1B 82 31 B0 C5 6F
> E6 C8
> DB C7 73 C5 E5 AC EE 51 55 BC 97 2A 7F EC 3C CB 9F C6 4A 32 DE 96 27 57 5D
> 26 E
> 7 2C 47 3D 7E D5 49 73 A7 5A 97 53 7E B0 43 D4 1E EA 3B B4 95 1B B5 B7 4D
> 12 E7
> F6 1B 8C 01 F0 BF 9A 98 48 EB 50 FC FF 8E C6 6C FC E7 6D 01 AD 08 75 87 3E
> D0 1F
> 35 78 19 EB F4 3F 58 C9 0E BD 91 EB E4 57 C1 3C 88 DD 2F 98 33 98 A7 B6 B4
> F9 A
> 0 73 B0 5E 1D F6 42 F8 A9 C3 A3 F1 F1 34 FF A9 27 9F E9 73 8E C7 7B 8E D7
> 18 08
> B1 EB 9E C7 7D 8F 73 2C AF F6 2B BF DA C1 3C B7 24 FC 26 7C CA 9C A7 FF A1
> 03 9F
> C1 4A FD 69 07 08 C6 71 0D FA 38 C4 8D F5 B1 16 C7 FB B3 A2 22 6A 3B AE 9D
> DD 4
> F FE 2E 7F C8 1F 79 FE 27 1F FB 39 8F 77 01 C6 39 9F 75 6D F4 A7 4C 49 9C
> D3 0E
> BA 26 73 04 F6 AA EE 27 33 F9 D5 06 AD F2 E3 5B 9A EB 9A FF DC 03 35 FE A9
> 2F 99
> 94 97 7C CA AF E7 06 BF A1 CF 9A 3F BA 6E 5E FC 5B 1B 14 91 FF 7A A7 21 2F
> FD 0
> F 5D 34 FE 69 07 E6 87 E6 7C 47 47 87 17 8D 0D 0A E3 DD E6 08 BF C1 1C 64
> 3F DA
> 79 FC 45 C6 BF EE 4B D4 DB FF DF 2F 39 E3 B9 FF 33 57 39 8E CC CC 67 B2 AB
> 0D 74
> BF E4 5C FA 5E EF 52 EA 6F 9E 43 A9 4F 6A 94 B5 1D 9B 0A C9 7F EA C7 18 E0
> D9 8
> 6 7E DC ED 60 0F CB AF F9 AA BE 87 74 76 76 66 F6 3D BD 33 A8 BF 6D DC DB
> 33 21
> 94 FF 45 FB 9F 7E 24 B3 B6 E9 23 C6 2F 73 93 3E D7 F3 1C DC 3C FB D1 C6 7B
> E4 12
> F7 0B 9B DB 96 5B 6D A2 B6 B0 65 61 57 57 46 5A E5 87 7F D4 E7 3E E7 12 5F
> F1 F
> E AB 3E A4 30 9F 69 23 E6 82 72 68 5C B1 D6 58 0F C5 C0 8C DF 59 75 F8 BB
> BB BB
> BD E8 6F F3 5A 7D DA 8F 36 7D C9 F3 8D DC 10 DD 9F 94 99 1C 9A D3 5C 47 CF
> B9 D0
> EF BB 66 A5 16 FF 8A E5 CB E3 DE DE DE 96 84 5C 7A 47 41 A1 1D 6C 6E 72 BF
> C2 7
> 9 A0 B5 EE 89 2A 45 F3 B3 0C 0E 0E C6 0B 16 3F 8E 7F 01 91 05 64 EA
> 16:28:39 [INFO] Successfully bound to: /0:0:0:0:0:0:0:0:25565
> 16:28:39 [INFO] Ready for connections.
> '''
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DragonetMC/Dragonet/issues/83.

##

**Comment by DefinitlyEvil** [comment]
It's normal, I printed out the packet data in order to debug.

**Comment by TheDiamondYT1** [comment]
Why not make it so it does

```
[INFO] Generating spawn terrain in background
```

and for packet thing make it a debug message.

**Comment by DefinitlyEvil** [comment]
That message should be removed when release so it's easier to just put them in [INFO] not DEBUG.

**Comment by mastercoms** [comment]
The percentages are done once every 2 seconds I believe, they aren't spammy.

**Comment by TheDiamondYT1** [comment]
For slow internets and/or computers it spams

**Comment by mastercoms** [comment]
I would not call it spam, as the rate of messaging is not fast. It does not depend on slow Internet, only slow computers.
