### ISSUE TITLE
Plugin event handlers

### ISSUE THREAD

**Issue by Sasszem** [DragonetMC/Dragonet-Legacy#85]
I've read the Scripting docs, & I've found that there's a less amount of event-handler functions, & we can't create complex plugins.
There should be event handlers such as, ChatMessage, PlayerUseItem, EntityAttackEntity & a lot more!
Check out this list: https://github.com/walterhiggins/ScriptCraft/blob/master/docs/API-Reference.md#events-helper-module-canary-version

And please, add more functions to plugins(create entities, open inventories, and a way to runtime set up event handlers)

Check out the https://github.com/walterhiggins/ScriptCraft/blob/master/docs/API-Reference.md page!
I think a server needs this possiblities, to modify the entire physics with plugins.

I hope I gave some good ideas.

**Comment by wordandahalf** [comment]
I will _eventually_ add more event handlers and functions, all it takes is time, which is something I have an infinitesimally small amount of.

**Comment by wordandahalf** [comment]
I also forgot to mention that in the `onLoad` hook, there is an instance of the script's Bukkit plugin sent in the parameters, so you actually have access to every BukkitAPI method.
See https://github.com/DragonetMC/Dragonet/wiki/Dragonet-JavaScript-Plugin-Scripting

**Comment by Sasszem** [comment]
It's similar to me:
When I got a good idea, I haven't got time to write a program.
When I got time, my friend calls me on skype to play TF2.
When I'm alone at home, none of my friends is online, then [BSOD | mysterious syntax error in an empty line | PyOpenGL NullFunctionErrors or GL_INVALID_OPERATION].

Now I have got the plans for a private OGL & SDL-based engine, just to understand the mechanic of them, but I haven't got time, becouse of freakin' school... 

And when I start coding at 20:00, there's ALWAYS GL_INVALID_OPERATION for nothing...

The coding is the easiest part of programming. If you don't work as a programmer, you never got enought time.

I hope that it's differen't for you, and you can always code what you want.

**Comment by TheDiamondYT1** [comment]
I will add some more events **_BUT**_ I need the @DragonetMC/developers to help in the folder-structure branch and add [DragonetMC/GlowStonePlusPlus](http://github.com/DragonetMC/GlowStonePlusPlus) as a subrepo

**Comment by DefinitlyEvil** [comment]
@RandomAltThingy We should fix the networking first. XD I'm waiting for JRakLibPlus fixed.

**Comment by alejzeis** [comment]
@DefinitlyEvil I'm possibly discontinuing JRakLibPlus, regular JRakLib
works fine now with 0.12.

On Tuesday, September 29, 2015, The Evil Man notifications@github.com
wrote:

> @RandomAltThingy https://github.com/RandomAltThingy We should fix the
> networking first. XD I'm waiting for JRakLibPlus fixed.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DragonetMC/Dragonet/issues/85#issuecomment-144218560.

##

**Comment by mastercoms** [comment]
Sorry, but aren't both projects yours?

**Comment by TheDiamondYT1** [comment]
@jython234 So android connect works?

**Comment by alejzeis** [comment]
@RandomAltThingy RedstoneLamp works fine with ios and W10, I don't have
android but I assume it works.

On Wednesday, September 30, 2015, RandomAltThingy notifications@github.com
wrote:

> @jython234 https://github.com/jython234 So android connect works?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DragonetMC/Dragonet/issues/85#issuecomment-144291574.

##

**Comment by TheDiamondYT1** [comment]
@jython234 Testing now

**Comment by TheDiamondYT1** [comment]
@jython234 Oh wait I'm stuck to 3g whoops. Nvm.

**Comment by DefinitlyEvil** [comment]
@jython234 Okay, I got it. ;)
