### ISSUE TITLE
spawning issue

### ISSUE THREAD

**Issue by DefinitlyEvil** [DragonetMC/Dragonet-Legacy#86]
Now the JRakLib works smoothly but now there are more problems.
- Players can't spawn, chunks sent but client seems won't receive. 
- Spamming UpdateBlockPacket

We need help, guys if you found any solution, tell meh please! 
@jython234 @RandomAltThingy 
@DragonetMC/developers

**Comment by DefinitlyEvil** [comment]
@mastercoms Do you have any ideas why server always sends block change messages? It's like spamming.

**Comment by mastercoms** [comment]
I'm investigating the problem. Glowstone is not checking properly to see if blocks have changed.

**Comment by DefinitlyEvil** [comment]
@mastercoms Thx.

**Comment by TheDiamondYT1** [comment]
This is not a JRakLib bug. It works on @RedstoneLamp. It must be your
packet sending/translation.

@jython234

**Comment by TheDiamondYT1** [comment]
Quick question @jython234:

_How can I create a program to just to use JRakLib and broadcast to the server list? Just the bare minimum needed to broadcast to server list. I'm going to make a piece of software for people to broadcast to server list stuffs_

**Comment by TheDiamondYT1** [comment]
@DragonetMC @DragonetMC/developers @GlowStonePlusPlus

Please could somebody add a subrepo (Or whatever its called) to the folder structure branch? The repo needed to be added is http://github.com/DragonetMC/GlowStonePlusPlus. Like @PocketMine with the subrepo for RakLib. Thanks.

**Comment by alejzeis** [comment]
@RandomAltThingy Look at the JRakLib wiki.

On Tuesday, October 6, 2015, RandomAltThingy notifications@github.com
wrote:

> @DragonetMC/watchers @DragonetMC/developers
> https://github.com/orgs/DragonetMC/teams/developers
> @GlowStonePlusPlus/Owners
> 
> Please could somebody add a subrepo (Or whatever its called) to the folder
> structure branch? The repo needed to be added is
> http://github.com/DragonetMC/GlowStonePlusPlus
> https://github.com/DragonetMC/GlowStonePlusPlus. Like @PocketMine
> https://github.com/PocketMine with the subrepo for RakLib. Thanks.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DragonetMC/Dragonet/issues/86#issuecomment-145796096.

##

**Comment by DefinitlyEvil** [comment]
@RandomAltThingy @jython234 I knew that wasn't JRakLib's bug, I am just asking for help, Idk where my code bug is... :(

**Comment by alejzeis** [comment]
@DefinitlyEvil Chunk format has changed, that may be it. look at
SubprotocolV34 in RedstoneLamp for help.

On Tuesday, October 6, 2015, The Evil Man notifications@github.com wrote:

> @RandomAltThingy https://github.com/RandomAltThingy @jython234
> https://github.com/jython234 I knew that wasn't JRakLib's bug, I am
> just asking for help, Idk where my code bug is... :(
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DragonetMC/Dragonet/issues/86#issuecomment-146056781.

##

**Comment by DefinitlyEvil** [comment]
@jython234 I saw it adds an `extra data` thing, is that the only one changed?

**Comment by alejzeis** [comment]
@DefinitlyEvil Yes, after the biomeColors comes a uint32 (unsigned 32 bit integer) which has the length of the extra data (byte[], NBT I think)

**Comment by DefinitlyEvil** [comment]
@jython234 I think I already added it. Anything else changed except for packets?

**Comment by TheDiamondYT1** [comment]
**Closed**
