### ISSUE TITLE
But, how to compile Dragonet now?

### ISSUE THREAD

**Issue by ghost** [DragonetMC/Dragonet-Legacy#87]
I have a lot of errors, can't find program package, can't find a lot of package...
I compiled GlowKit and installed it, what should I do next?
Thanks!

**Comment by TheDiamondYT1** [comment]
Use git bash:

<code>git clone --recursive https://github.com/DragonetMC/Dragonet</code>

Then, using maven, cd to the.root project directory and type
<code>mvn package</code>

**Comment by mastercoms** [comment]
```
git clone --recursive https://github.com/DragonetMC/Dragonet
cd GlowstonePlusPlus/Glowkit
mvn install
cd ../..
```

Move GlowstonePlusPlus folder's src folder content to the root src folder.

```
mvn package
```

**Comment by TheDiamondYT1** [comment]
@mastercoms Why? --recursive clones all repos. Just mvn package in the root it also builds sub modules. Well, for me on maven 3 anyway.

**Comment by TheDiamondYT1** [comment]
Maybe I should make a installer in C#. Or maybe just a batch file.

**Comment by wordandahalf** [comment]
@RandomAltThingy Or Java...

**Comment by mastercoms** [comment]
Because Dragonet and Glowstone++ depend on each other.

You don't need to make an installer, people can download from CircleCI.

**Comment by TheDiamondYT1** [comment]
@TheMCPEGamer java would work multi-platorm but I like making .exe files. Maybe I could make 2 like most things.

**Comment by DefinitlyEvil** [comment]
@RandomAltThingy People can download snapshots for every commit at CircleCI.

**Comment by TheDiamondYT1** [comment]
@DefinitlyEvil But you need to be logged in and ppl are stupid

**Comment by mastercoms** [comment]
But we can just put a download link on the website that uses Javascript to get the latest download URL.

**Comment by TheDiamondYT1** [comment]
Teh website is shit. Use custom CSS :P

**Comment by TheDiamondYT1** [comment]
I can do if you want

**Comment by ethsmith** [comment]
Speaking of websites the CircuitSoft home page looks pretty fancy @mastercoms

**Comment by DefinitlyEvil** [comment]
@TekkitCommando @mastercoms @RandomAltThingy I've fixed everything related to building, now you only need to type:
`mvn package` and you do N0T need to copy files anymore. LOL!!

**Comment by TheDiamondYT1** [comment]
?

**Comment by TheDiamondYT1** [comment]
I did that anyway. It builds all submodules.

**Comment by TheDiamondYT1** [comment]
@DefinitlyEvil What did you type before lol? Its always been <code>mvn package</code> noob lol

**Comment by DefinitlyEvil** [comment]
@RandomAltThingy I added a source location to pom's build-helper thingy so it can combine two directories together.
