### ISSUE TITLE
When client join to the server, the client always show: Building terrain.

### ISSUE THREAD

**Issue by ghost** [DragonetMC/Dragonet-Legacy#88]
Client always show "Building terrain" when join the server, and then join fails, server crashed...
So what should I do or I overlooked something?

**Comment by TheDiamondYT1** [comment]
Currently joining is bugged. Speak to @jython234 about networking.

**Comment by authme** [comment]
.....I tried a morning, I thought it was my problem ......

**Comment by ghost** [comment]
I treid a morning, I thought it was my problem ...... But now seems not ......

**Comment by DefinitlyEvil** [comment]
That's the problem I was talking about. :(

**Comment by ghost** [comment]
So is the new version of the client changed something? Or we overlooked something?... I read code but I can't find any problem for send package...

**Comment by DefinitlyEvil** [comment]
Now players can at least join. ;)

**Comment by DefinitlyEvil** [comment]
Now players can at least join. ;)
