### ISSUE TITLE
The BungeeCord Port

### ISSUE THREAD

**Issue by TheDiamondYT1** [DragonetMC/Dragonet-Legacy#89]
I will be porting BungeeCord (Currently awaiting permission to use the name, if I don't get it I will rename the project) to Minecraft: Pocket Edition.

BungeeCord is a server software in itself, so I need packet sending. That's why I need help from @jython234. I would like the PocketMine style as @PEMapModder's style uses alot of files and is quite complicated. Basically I need the BinaryBuffer code and packet sending code. I can do the rest.

I may change it up a bit and use the [RedstoneLamp API](http://github.com/RedstoneLamp/RedstoneLamp) or [Dragonet](http://github.com/DragonetMC/Dragonet). I will see what you guys would want.

It will query the server, like BungeeCord, and return any kick messages in chat before connecting. This should be possibly with some serious java skills.

---

This will be a java **Library** and not a project. A bit like [JRakLib](https://github.com/BlockServerProject/JRakLib), so developers can use it in their projects.

**Comment by DefinitlyEvil** [comment]
@RandomAltThingy See DragonPortal. ;)

**Comment by RandomAltThingy** [comment]
No code

**Comment by RandomAltThingy** [comment]
I have started the port of PocketBungee. It will be a fast, lightweight server software.

**Comment by RandomAltThingy** [comment]
Pushing source to my PocketBungee repo check it out in 10 mins

**Comment by Creeperface01** [comment]
So other server software for MCPE?

**Comment by RandomAltThingy** [comment]
@Creeperface01 Yes, but with a proxy like BungeeCord for pc. And I WILL do this software correctly.

**Comment by Creeperface01** [comment]
But without PC support right?

**Comment by TekkitCommando** [comment]
So its bungee cord for pocket edition clients, fancy

**Comment by RandomAltThingy** [comment]
No. No PC support.

**Comment by RandomAltThingy** [comment]
Pushing very initial source. Feel free to contribute.

**Comment by TekkitCommando** [comment]
If its Bungee Cord for Pocket Edition, Name it Pocket Bungee xD

**Comment by Creeperface01** [comment]
Wait.. Bungee cord is the server like craft bukkit or pocketmine?

**Comment by RandomAltThingy** [comment]
I did

**Comment by TekkitCommando** [comment]
Bungee Cord is a server software with a proxy used to forward clients to other servers @Creeperface01

**Comment by iNevet** [comment]
Basically BinaryBuffer is ByteBuffer

**Comment by TekkitCommando** [comment]
:+1:

**Comment by jython234** [comment]
@iNevet BinaryBuffer can read/write more types than a regular ByteBuffer
(for example, int24).

On Saturday, October 10, 2015, iNevet <notifications@github.com> wrote:

> Basically BinaryBuffer is ByteBuffer
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DragonetMC/Dragonet/issues/89#issuecomment-147093618>.
>


--

**Comment by RandomAltThingy** [comment]
@TekkitCommando BungeeCord is **NOT*** a server software. It is a proxy. The project strucure does however look like a server software.

**Comment by TekkitCommando** [comment]
It is a proxy used for forwarding clients to servers, therefore i consider it a server software xD

**Comment by RandomAltThingy** [comment]
@DragonetMC/developers I need you to truthuly answer a question: *Do you want a custom, ground up server software supporting PC and PE? Not like Dragonet using bukkit API and glow stone.*

**Comment by RandomAltThingy** [comment]
@DefinitlyEvil Great idea: I work on DragonPortal xD

**Comment by RandomAltThingy** [comment]
I will make PocketBungee a library instead.

**Comment by DefinitlyEvil** [comment]
@RandomAltThingy And you have to do tons of wok to update networking thingy such as switching to JRakLib.

**Comment by RandomAltThingy** [comment]
@DefinitlyEvil If PocketBungee succeeds as a library, would you use it?

**Comment by DefinitlyEvil** [comment]
@RandomAltThingy You should add the networking interface thing for MCPE<->Portal networking and Portal<=>Dragonet networking, and for P<=>D networking we can use some TCP links to make transfer more stable. So we can support connecting to MCPE original server or Dragonet server. The reason why we need to customize a networking interface for Dragonet is because it will be more efficent(although users can still connect to Dragonet servers as normal MCPE servers).

**Comment by DefinitlyEvil** [comment]
@RandomAltThingy Of course I will use it. xD

**Comment by RandomAltThingy** [comment]
@DefinitlyEvil Right now im coding the pe version of MineServer. ... hours of hardcore coding ahead of me today.

**Comment by RandomAltThingy** [comment]
#IntellijFtw

**Comment by DefinitlyEvil** [comment]
@RandomAltThingy Good luck to ya. xD

**Comment by mastercoms** [comment]
Make sure to commit and push often.

**Comment by RandomAltThingy** [comment]
@DragonetMC/developers I have this error http://paste.ubuntu.com/12740545/

When running my server software

**Comment by mastercoms** [comment]
You aren't shading your dependencies in the jar file, so the classes can't be accessed. Use maven-shade-plugin.

**Comment by RandomAltThingy** [comment]
I get an error again NullPointerException.

**Comment by RandomAltThingy** [comment]
Found out why.

**Comment by TheDiamondYT1** [comment]
@mastercoms Pom.xml. It don't let me do import org.apache. I fixed this before but didn't save and cant remember how.

**pom.xml (Main one)**

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.mineserver</groupId>
    <artifactId>MineServer</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <modules>
        <module>MCPE-Server</module>
    </modules>

    <dependencies>
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>2.4</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <!-- Build an executable JAR -->
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>2.4</version>
                <configuration>
                    <archive>
                        <manifest>
                            <addClasspath>true</addClasspath>
                            <classpathPrefix>lib/</classpathPrefix>
                            <mainClass>org.mineserver.pe.Main</mainClass>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>2.3</version>
                <executions>
                    <!-- Run shade goal on package phase -->
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <transformers>
                                <!-- add Main-Class to manifest file -->
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>org.mineserver.pe.Main</mainClass>
                                </transformer>
                            </transformers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
```

**pom.xml (Module one)**

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.mineserver</groupId>
        <artifactId>MineServer</artifactId>
        <version>1.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <groupId>org.mineserver</groupId>
    <artifactId>MCPE-Server</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>2.4</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <!-- Build an executable JAR -->
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>2.4</version>
                <configuration>
                    <archive>
                        <manifest>
                            <addClasspath>true</addClasspath>
                            <classpathPrefix>lib/</classpathPrefix>
                            <mainClass>org.mineserver.pe.Main</mainClass>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>2.3</version>
                <executions>
                    <!-- Run shade goal on package phase -->
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <transformers>
                                <!-- add Main-Class to manifest file -->
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>org.mineserver.pe.Main</mainClass>
                                </transformer>
                            </transformers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
```

**Comment by TheDiamondYT1** [comment]
Temporarily closing
