### ISSUE TITLE
Plugins for servers hosting

### ISSUE THREAD

**Issue by Jelly9912** [DragonetMC/Dragonet-Legacy#90]
So good luck :)

**Comment by RandomAltThingy** [comment]
Dragonet and GlowStonePlusPlus are not finished yet. However, you can code plugins using the Bukkit API. We are all too busy to code plugins for you guys.

**Comment by Jelly9912** [comment]
I understand :) so good luck, I keep my fingers crossed for you

**Comment by mastercoms** [comment]
@Jelly9912 What was your question? @RandomAltThingy should only speak for himself.

**Comment by TheDiamondYT1** [comment]
If anyone would like to make pluigns, please submit to this issue and you will be given credit and published to the temporary Dragonet forums

**Comment by TheDiamondYT1** [comment]
Closing. This is not currently on our TODO list. Will keep open though.
