### ISSUE TITLE
I found a lot of problems.

### ISSUE THREAD

**Issue by ghost** [DragonetMC/Dragonet-Legacy#91]
- PE users can not see the PC  user, but they can see "a ball of fire" and that is PC users.
- PC  user can see the PC user, but PC users see is the PE users is always stuck in the birth point, even if they have moved position.
- PC and PE user can not see each other placed the block.
- There is more than one user at the same time joined to the server will lead to stuck. PC and PE terminal can not synchronize data, and when shut down the server, the map can not be saved properly, and the point of birth will somehow changed.

I used four different computers and four different phones to test.
So this is now the case, we can not put into use. :(
But I think the most important issue is the PC and PE data can not be synchronized.

**Comment by DefinitlyEvil** [comment]
I said in the release this is just a update to prove we are not dead.

**Comment by mastercoms** [comment]
But this is still an issue and a valid bug report, why did you close it?

**Comment by DefinitlyEvil** [comment]
I will eventually fix them. xD

**Comment by DefinitlyEvil** [comment]
I guess we can regard this as a todo list.

**Comment by TheDiamondYT1** [comment]
Developers, please use the strikethrough markdown (I'm not sure how myself, will google) when an issue is fixed.

**Comment by DefinitlyEvil** [comment]
All of this except the first one(added in the to-do list, #98) are fixed, closing this issue.
