### ISSUE TITLE
PC and PE data can not be synchronized or very slow

### ISSUE THREAD

**Issue by ghost** [DragonetMC/Dragonet-Legacy#92]
This problem also exists in version 0.0.2, so please fix it. :D

**Comment by DefinitlyEvil** [comment]
I know this problem. It is caused by the delay of packet handling.

**Comment by DefinitlyEvil** [comment]
Good News: Once MCPE switches to TCP, everything will be solved smoothly! :D

**Comment by DefinitlyEvil** [comment]
Player synchronization problem solved, although player can not be displayed properly.
