### ISSUE TITLE
Can not save OP information

### ISSUE THREAD

**Issue by ghost** [DragonetMC/Dragonet-Legacy#93]
Error reading from: config\ops.json
java.lang.NullPointerException
at net.glowstone.util.bans.JsonListFile.load(JsonListFile.java:52)
at net.glowstone.GlowServer.start(GlowServer.java:464)
at net.glowstone.GlowServer.main(GlowServer.java:121)

What...:(...

**Comment by TheDiamondYT1** [comment]
Please report to @mastercoms

**Comment by ghost** [comment]
[{"name":null,"uuid":"530fa97a-357f-3c19-94d3-0c5c65c18fe8"}]
My user name is "test", but...op.json suddenly become this...and then second start can not be loaded...

**Comment by TheDiamondYT1** [comment]
This is a GlowStonePlusPlus bug. Please report it to @mastercoms on the @GlowStonePlusPlus GlowStonePlusPlus repo
