### ISSUE TITLE
After closing the server show this

### ISSUE THREAD

**Issue by ghost** [DragonetMC/Dragonet-Legacy#94]
00:03:14 [INFO] CONSOLE: Stopping the server..
00:03:14 [INFO] The server is shutting down...
00:03:14 [INFO] Stopping Dragonet server...
00:03:14 [INFO] Saving world: world
00:03:15 [INFO] Saving world: world_nether
00:03:16 [INFO] Saving world: world_the_end
00:03:25 [WARN] Still running after shutdown, finding rogue threads...
00:03:25 [WARN] Rogue thread: Thread[Netty IO Thread #0,5,main]
00:03:25 [WARN]     at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
00:03:25 [WARN]     at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source)
00:03:25 [WARN]     at sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source)
00:03:25 [WARN]     at sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source)
00:03:25 [WARN]     at sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
00:03:25 [WARN]     at sun.nio.ch.SelectorImpl.select(Unknown Source)
00:03:25 [WARN]     at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:622)
00:03:25 [WARN]     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:310)
00:03:25 [WARN]     at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
00:03:25 [WARN]     at java.lang.Thread.run(Unknown Source)
00:03:26 [WARN] Rogue thread: Thread[JRakLib Thread #30,5,main]
00:03:26 [WARN]     at java.lang.Object.wait(Native Method)
00:03:26 [WARN]     at java.lang.Object.wait(Unknown Source)
00:03:26 [WARN]     at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:255)
00:03:26 [WARN]     at io.netty.channel.DefaultChannelPromise.await(DefaultChannelPromise.java:129)
00:03:26 [WARN]     at io.netty.channel.DefaultChannelPromise.await(DefaultChannelPromise.java:28)
00:03:26 [WARN]     at net.beaconpe.jraklib.server.UDPServerSocket.<init>(UDPServerSocket.java:124)
00:03:26 [WARN]     at net.beaconpe.jraklib.server.JRakLibServer.run(JRakLibServer.java:139)
00:03:26 [WARN] java.lang.InterruptedException
00:03:26 [WARN]         at java.lang.Object.wait(Native Method)
00:03:26 [WARN]         at java.lang.Object.wait(Unknown Source)
00:03:26 [WARN]         at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:255)
00:03:26 [WARN]         at io.netty.channel.DefaultChannelPromise.await(DefaultChannelPromise.java:129)
00:03:26 [WARN]         at io.netty.channel.DefaultChannelPromise.await(DefaultChannelPromise.java:28)
00:03:26 [WARN]         at net.beaconpe.jraklib.server.UDPServerSocket.<init>(UDPServerSocket.java:124)
00:03:26 [WARN]         at net.beaconpe.jraklib.server.JRakLibServer.run(JRakLibServer.java:139)
No more.

**Comment by mastercoms** [comment]
That's fine. This is just saying that there were some running tasks that were stopped forcefully when the server stopped.

**Comment by alejzeis** [comment]
JRakLib needs to be shutdown before exit (use handler.shutdown()). It also needs time to process the shutdown packet internally.
