### ISSUE TITLE
I want to host Demo Server

### ISSUE THREAD

**Issue by U-siro** [DragonetMC/Dragonet-Legacy#96]
i have a many server(because i am small hosting company), so i want to host this project's demo server because this project is interesting.
You can contact me: castarnet@gmail.com

**Comment by ethsmith** [comment]
I messaged him so closing this

**Comment by TheDiamondYT1** [comment]
I am going to host it xD
@DefinitlyEvil plz

**Comment by ethsmith** [comment]
@RandomAltThingy byte powered is hosting the demo server atm

**Comment by TekkitCommando** [comment]
@RandomAltThingy
